import {
  Activity,
  ArrowDown,
  BoxSelect,
  Brush,
  ChevronsRight,
  CircleDashed,
  CloudFog,
  Cuboid,
  Dna,
  Droplets,
  Fan,
  Feather,
  Flower2,
  Grid3x3,
  Hexagon,
  Infinity as InfinityIcon,
  LucideIcon,
  Magnet,
  Mountain,
  MoveUp,
  MoveVertical,
  Orbit,
  RefreshCw,
  RotateCw,
  ScanSearch,
  ScatterChart,
  Shell,
  Sigma,
  Sparkles,
  Split,
  Sprout,
  Tornado,
  TreePine,
  Waves,
  Wind,
  Zap,
} from 'lucide-react';
import type { Layer2Type } from '../types';
import { MOTION_GROUPS } from './motionCatalog';
import { getModeExecutionManifestEntry } from '../lib/executionManifest';
import { getMotionArchitecture } from '../lib/motionArchitecture';

const MOTION_OPTION_OVERRIDES: Partial<Record<Layer2Type, { label: string; icon: LucideIcon }>> = {
  flow: { label: 'Flow', icon: Activity },
  wind: { label: 'Wind', icon: Wind },
  aero: { label: 'Aero', icon: Fan },
  curl: { label: 'Curl', icon: Wind },
  noise: { label: 'Noise', icon: CloudFog },
  ridged_mf: { label: 'Ridged', icon: Mountain },
  field: { label: 'Field', icon: Grid3x3 },
  euler: { label: 'Euler', icon: Split },
  orbit: { label: 'Orbit', icon: RotateCw },
  orbit_swarm: { label: 'O-Swarm', icon: RotateCw },
  spiral_motion: { label: 'Spiral', icon: Shell },
  helix: { label: 'Helix', icon: Dna },
  pendulum: { label: 'Pend', icon: MoveVertical },
  phyllotaxis: { label: 'Phyllo', icon: Sprout },
  rose_curve: { label: 'Rose', icon: Flower2 },
  lissajous: { label: 'Lissaj', icon: InfinityIcon },
  toroidal: { label: 'Toroid', icon: Orbit },
  lattice: { label: 'Lattice', icon: Grid3x3 },
  epicycle: { label: 'Epicycle', icon: RotateCw },
  gyre: { label: 'Gyre', icon: Tornado },
  crystal: { label: 'Crystal', icon: Hexagon },
  ripple_ring: { label: 'Ripple', icon: Waves },
  fold: { label: 'Fold', icon: Split },
  collapse_fracture: { label: 'Collapse', icon: Split },
  orbit_fracture: { label: 'O-Fract', icon: RotateCw },
  kaleidoscope: { label: 'Kaleido', icon: Flower2 },
  braid: { label: 'Braid', icon: Dna },
  braid_stream: { label: 'B-Stream', icon: Dna },
  arc_wave: { label: 'ArcWave', icon: Waves },
  web: { label: 'Web', icon: Grid3x3 },
  pulse_shell: { label: 'Pulse', icon: Shell },
  mandala: { label: 'Mandala', icon: Flower2 },
  ribbon: { label: 'Ribbon', icon: Dna },
  shear: { label: 'Shear', icon: Split },
  spokes: { label: 'Spokes', icon: RotateCw },
  breathing: { label: 'Breath', icon: Activity },
  pulse_breathing: { label: 'P-Breath', icon: Activity },
  torus_knot: { label: 'T-Knot', icon: Orbit },
  clifford: { label: 'Clifford', icon: InfinityIcon },
  hopalong: { label: 'Hopalong', icon: ScatterChart },
  cellular: { label: 'Cellular', icon: Grid3x3 },
  cyclone: { label: 'Cyclone', icon: Tornado },
  petals: { label: 'Petals', icon: Flower2 },
  sheet: { label: 'Sheet', icon: BoxSelect },
  flare: { label: 'Flare', icon: CircleDashed },
  moebius: { label: 'Moebius', icon: Orbit },
  interference_wave: { label: 'Interfere', icon: Waves },
  signal_braid: { label: 'S-Braid', icon: Dna },
  harmonic: { label: 'Harmonic', icon: Waves },
  starburst: { label: 'Star', icon: CircleDashed },
  grid_wave: { label: 'G-Wave', icon: Grid3x3 },
  helio: { label: 'Helio', icon: RotateCw },
  zigzag: { label: 'Zigzag', icon: Split },
  shockwave: { label: 'Shock', icon: CircleDashed },
  filament: { label: 'Filament', icon: Feather },
  mirror_fold: { label: 'Mirror', icon: Split },
  radial_steps: { label: 'R-Steps', icon: RotateCw },
  coil: { label: 'Coil', icon: Dna },
  labyrinth: { label: 'Maze', icon: Grid3x3 },
  gyro: { label: 'Gyro', icon: RotateCw },
  echo_ring: { label: 'Echo', icon: Waves },
  braidshell: { label: 'B-Shell', icon: Dna },
  crosscurrent: { label: 'Cross', icon: Wind },
  prism: { label: 'Prism', icon: Hexagon },
  tessellate: { label: 'Tessel', icon: Grid3x3 },
  pulse_grid: { label: 'P-Grid', icon: Activity },
  tidal: { label: 'Tidal', icon: Waves },
  beacon: { label: 'Beacon', icon: CircleDashed },
  caustic: { label: 'Caustic', icon: Waves },
  pinwheel: { label: 'Pinwheel', icon: RotateCw },
  nebula: { label: 'Nebula', icon: CloudFog },
  fronds: { label: 'Fronds', icon: Sprout },
  gyroflower: { label: 'GyroFlwr', icon: Flower2 },
  monolith: { label: 'Monolith', icon: BoxSelect },
  runes: { label: 'Runes', icon: Sigma },
  fanout: { label: 'Fanout', icon: Fan },
  eddy: { label: 'Eddy', icon: Tornado },
  nova: { label: 'Nova', icon: CircleDashed },
  surface_shell: { label: 'Shell', icon: Shell },
  surface_patch: { label: 'Patch', icon: BoxSelect },
  mirror_skin: { label: 'MirrorSkin', icon: Shell },
  membrane_pollen: { label: 'MemPollen', icon: Shell },
  brush_surface: { label: 'BrushSurf', icon: Brush },
  fiber_field: { label: 'Fiber', icon: Feather },
  nerve_web: { label: 'NerveWeb', icon: Feather },
  cinder_web: { label: 'CinderWeb', icon: Feather },
  spectral_mesh: { label: 'SpecMesh', icon: Hexagon },
  ember_lace: { label: 'EmberLace', icon: Sparkles },
  growth_field: { label: 'Growth', icon: TreePine },
  deposition_field: { label: 'Deposition', icon: Mountain },
  tremor_lattice: { label: 'Tremor', icon: Waves },
  crystal_aggregate: { label: 'CrystalAgg', icon: Hexagon },
  erosion_trail: { label: 'Erosion', icon: Waves },
  voxel_lattice: { label: 'Voxel', icon: Cuboid },
  crystal_deposition: { label: 'CrystDep', icon: Hexagon },
  reaction_diffusion: { label: 'Reaction', icon: ScanSearch },
  volume_fog: { label: 'Fog', icon: CloudFog },
  soot_veil: { label: 'SootVeil', icon: CloudFog },
  charge_veil: { label: 'ChargeVeil', icon: Zap },
  ribbon_veil: { label: 'R-Veil', icon: Brush },
  shard_debris: { label: 'Shards', icon: Hexagon },
  stipple_field: { label: 'Stipple', icon: ScanSearch },
  drift_glyph_dust: { label: 'GlyphDust', icon: Sigma },
  aura_shell: { label: 'Aura', icon: Shell },
  liquid_smear: { label: 'L-Smear', icon: Droplets },
  plasma_thread: { label: 'Plasma', icon: Zap },
  ashfall: { label: 'Ashfall', icon: CloudFog },
  bloom_spores: { label: 'Spores', icon: Sparkles },
  pollen_storm: { label: 'Pollen', icon: Sparkles },
  echo_rings: { label: 'ERings', icon: Waves },
  skin_lattice: { label: 'SkinLat', icon: Cuboid },
  mist_ribbon: { label: 'MistRib', icon: Brush },
  foam_drift: { label: 'Foam', icon: Waves },
  prism_smoke: { label: 'PrismSmoke', icon: Hexagon },
  spore_halo: { label: 'SporeHalo', icon: Sparkles },
  calcified_skin: { label: 'CalcSkin', icon: Shell },
  rune_smoke: { label: 'RuneSmoke', icon: Sigma },
  aurora_threads: { label: 'AuroraThr', icon: Zap },
  residue_skin: { label: 'ResidueSkin', icon: Shell },
  sigil_dust: { label: 'SigilDust', icon: Sigma },
  frost_lattice: { label: 'FrostLat', icon: Cuboid },
  mirage_smoke: { label: 'Mirage', icon: CloudFog },
  lorenz: { label: 'Lorenz', icon: InfinityIcon },
  aizawa: { label: 'Aizawa', icon: Sigma },
  rossler: { label: 'Rössler', icon: Tornado },
  thomas: { label: 'Thomas', icon: Orbit },
  attractor: { label: 'Attr', icon: Magnet },
  swirl: { label: 'Swirl', icon: Tornado },
  vortex: { label: 'Vortex', icon: RefreshCw },
  wave: { label: 'Wave', icon: Waves },
  morph: { label: 'Morph', icon: Hexagon },
  liquid: { label: 'Liquid', icon: Droplets },
  smoke: { label: 'Smoke', icon: MoveUp },
  gravity: { label: 'Gravity', icon: ArrowDown },
  spring: { label: 'Spring', icon: MoveVertical },
  explosion: { label: 'Burst', icon: CircleDashed },
  linear: { label: 'Linear', icon: ChevronsRight },
  uniform: { label: 'Uniform', icon: BoxSelect },
  gaussian: { label: 'Gauss', icon: ScatterChart },
  brownian: { label: 'Brownian', icon: Split },
  crawl_seep: { label: 'C-Seep', icon: Feather },
  aux: { label: 'Drift', icon: Feather },
  biofilm_skin: { label: 'Biofilm', icon: Shell },
  bloom_torrent: { label: 'BloomFlow', icon: Sparkles },
  branch_propagation: { label: 'BranchProp', icon: TreePine },
  contour_echo: { label: 'Contour', icon: Waves },
  dust_plume: { label: 'DustPlume', icon: CloudFog },
  eclipse_halo: { label: 'Eclipse', icon: Shell },
  ember_drift: { label: 'EmberDrift', icon: Sparkles },
  ember_swarm: { label: 'EmberSwarm', icon: Sparkles },
  flock_drift: { label: 'Flock', icon: Feather },
  fracture_bloom: { label: 'FracBloom', icon: Sparkles },
  fracture_pollen: { label: 'FracPollen', icon: Sparkles },
  glyph_weave: { label: 'GlyphWeave', icon: Sigma },
  halo_bloom: { label: 'HaloBloom', icon: Sparkles },
  ink_bleed: { label: 'InkBleed', icon: Brush },
  ion_rain: { label: 'IonRain', icon: Zap },
  lattice_surge: { label: 'LatSurge', icon: Cuboid },
  mesh_weave: { label: 'MeshWeave', icon: Grid3x3 },
  pollen_lattice: { label: 'PollenLat', icon: Cuboid },
  prism_threads: { label: 'PrismThr', icon: Hexagon },
  resin_shell: { label: 'ResinShell', icon: Shell },
  resonance_flux: { label: 'ResFlux', icon: Waves },
  seep_fracture: { label: 'SeepFrac', icon: Brush },
  shell_script: { label: 'ShellScript', icon: Shell },
  standing_interference: { label: 'StandInt', icon: Waves },
  static_lace: { label: 'StaticLace', icon: Feather },
  static_smoke: { label: 'StaticSmoke', icon: CloudFog },
  tidal_lock: { label: 'TidalLock', icon: Orbit },
  vapor_canopy: { label: 'Vapor', icon: CloudFog },
  velvet_ash: { label: 'VelvetAsh', icon: CloudFog },
  vortex_sheet: { label: 'VortexSheet', icon: Brush },
  cloth_membrane: { label: 'Cloth', icon: BoxSelect },
  viscous_flow: { label: 'Viscous', icon: Droplets },
  elastic_sheet: { label: 'Elastic', icon: BoxSelect },
  capillary_sheet: { label: 'Capillary', icon: Droplets },
  sediment_stack: { label: 'Sediment', icon: Mountain },
  cellular_front: { label: 'CellFront', icon: ScanSearch },
  elastic_lattice: { label: 'ElasticLat', icon: Cuboid },
  viscoelastic_membrane: { label: 'ViscoMem', icon: BoxSelect },
  percolation_sheet: { label: 'Percolate', icon: Droplets },
  talus_heap: { label: 'Talus', icon: Mountain },
  corrosion_front: { label: 'Corrode', icon: ScanSearch },
  creep_lattice: { label: 'CreepLat', icon: Cuboid },
  advection_flow: { label: 'Advect', icon: Wind },
  vortex_transport: { label: 'V-Trans', icon: Tornado },
  pressure_cells: { label: 'PCell', icon: Grid3x3 },
  avalanche_field: { label: 'Avalanche', icon: Mountain },
  jammed_pack: { label: 'Jammed', icon: BoxSelect },
  melt_front: { label: 'MeltFront', icon: Droplets },
  freeze_skin: { label: 'FreezeSkin', icon: Shell },
  condense_field: { label: 'Condense', icon: CloudFog },
  evaporative_sheet: { label: 'Evaporate', icon: Droplets },
  sublimate_cloud: { label: 'Sublimate', icon: CloudFog },
  granular_fall: { label: 'Granular', icon: ArrowDown },
  fracture_grammar: { label: 'FracGrammar', icon: Split },
  growth_grammar: { label: 'GrowGrammar', icon: TreePine },
};

const MOTION_GROUP_ICONS: Record<(typeof MOTION_GROUPS)[number]['label'], LucideIcon> = {
  Fluid: Wind,
  Chaos: InfinityIcon,
  Orbit: RotateCw,
  Pattern: Flower2,
  Structure: Grid3x3,
  Pulse: Activity,
  Transform: Split,
};

export const DRIVER_LABELS: Record<ReturnType<typeof getMotionArchitecture>['driver'], string> = {
  field: 'Field',
  orbit: 'Orbit',
  oscillation: 'Oscillation',
  chaos: 'Chaos',
  structural: 'Structure',
  transform: 'Transform',
  growth: 'Growth',
  deposition: 'Deposition',
  volumetric: 'Volume',
};

export const EDITING_PROFILE_LABELS: Record<ReturnType<typeof getMotionArchitecture>['editingProfile'], string> = {
  explore: 'Explore',
  shape: 'Shape',
  weave: 'Weave',
  grow: 'Grow',
  accumulate: 'Accumulate',
  atmosphere: 'Atmosphere',
};

export const DRIVER_SECTION_ORDER: ReturnType<typeof getMotionArchitecture>['driver'][] = [
  'volumetric',
  'growth',
  'deposition',
  'structural',
  'transform',
  'field',
  'orbit',
  'oscillation',
  'chaos',
];

function formatMotionLabel(id: Layer2Type) {
  return id
    .split('_')
    .map((token) => token.slice(0, 1).toUpperCase() + token.slice(1))
    .join(' ');
}

export const MOTION_OPTIONS: { id: Layer2Type; label: string; icon: LucideIcon }[] = MOTION_GROUPS.flatMap((group) =>
  group.ids.map((id) => {
    const override = MOTION_OPTION_OVERRIDES[id];
    return {
      id,
      label: override?.label ?? formatMotionLabel(id),
      icon: override?.icon ?? MOTION_GROUP_ICONS[group.label],
    };
  }),
);

export const MOTION_OPTIONS_BY_ID = new Map(MOTION_OPTIONS.map((option) => [option.id, option]));

export function motionOptionMatchesQuery(id: Layer2Type, query: string, groupLabel: string) {
  if (query.length === 0) return true;
  const option = MOTION_OPTIONS_BY_ID.get(id);
  if (!option) return false;
  const architecture = getMotionArchitecture(option.id);
  const manifest = getModeExecutionManifestEntry(option.id);
  return `${option.label} ${option.id} ${groupLabel} ${architecture.driver} ${architecture.depictionHint} ${architecture.editingProfile} ${architecture.editingFocus.join(' ')} ${manifest.requestedEngineId} ${manifest.pathId} ${manifest.adapterId} ${manifest.sourceFieldKind} ${manifest.sourceFieldMode}`
    .toLowerCase()
    .includes(query);
}
