import type { ProceduralGuide, ProceduralMode } from './proceduralModeSettingsTypes';

export const PROCEDURAL_LABELS: Partial<Record<ProceduralMode, string>> = {
  sheet: 'Membrane Surface',
  surface_shell: 'Surface Shell',
  surface_patch: 'Surface Patch',
  brush_surface: 'Brush Surface',
  fiber_field: 'Fiber Field',
  growth_field: 'Growth Field',
  deposition_field: 'Deposition Field',
  crystal_aggregate: 'Crystal Aggregate',
  erosion_trail: 'Erosion Trail',
  voxel_lattice: 'Voxel Lattice',
  crystal_deposition: 'Crystal Deposition',
  reaction_diffusion: 'Reaction Diffusion',
  volume_fog: 'Volume Fog',
  cloth_membrane: 'Cloth Membrane',
  viscous_flow: 'Viscous Flow',
  granular_fall: 'Granular Fall',
  fracture_grammar: 'Fracture Grammar',
  growth_grammar: 'Growth Grammar',
  elastic_sheet: 'Elastic Sheet',
  capillary_sheet: 'Capillary Sheet',
  sediment_stack: 'Sediment Stack',
  cellular_front: 'Cellular Front',
  biofilm_skin: 'Biofilm Skin',
  elastic_lattice: 'Elastic Lattice',
  viscoelastic_membrane: 'Viscoelastic Membrane',
  percolation_sheet: 'Percolation Sheet',
  talus_heap: 'Talus Heap',
  corrosion_front: 'Corrosion Front',
  creep_lattice: 'Creep Lattice',
  advection_flow: 'Advection Flow',
  vortex_transport: 'Vortex Transport',
  pressure_cells: 'Pressure Cells',
  avalanche_field: 'Avalanche Field',
  jammed_pack: 'Jammed Pack',
  melt_front: 'Melt Front',
  freeze_skin: 'Freeze Skin',
  condense_field: 'Condense Field',
  evaporative_sheet: 'Evaporative Sheet',
  sublimate_cloud: 'Sublimate Cloud',
};

export const PROCEDURAL_GUIDES: Partial<Record<ProceduralMode, ProceduralGuide>> = {
  sheet: {
    summary: '膜・布・板のような面表現。構造を見せたい時の基準形です。',
    bestSources: ['plane', 'grid', 'text'],
    useCases: ['膜面', '図版的な平面', '透過シート'],
    tips: ['Fresnel を上げると輪郭が見えやすくなります。', 'Wireframe は構造寄り、Glass は空間寄りです。'],
    recommendedRanges: [
      { label: 'Opacity', value: '0.35–0.80' },
      { label: 'Fresnel', value: '0.30–0.85' },
      { label: 'Audio', value: '0.00–0.35' },
    ],
  },
  surface_shell: {
    summary: '外殻・ハル系。輪郭と厚みを見せる表現に向いています。',
    bestSources: ['sphere', 'cube'],
    useCases: ['外殻', '物体表面', '建築的ボリューム'],
    tips: ['Point Budget は見た目と負荷の両方に効きます。', 'Jitter を上げすぎると殻の印象が崩れます。'],
    recommendedRanges: [
      { label: 'Opacity', value: '0.30–0.75' },
      { label: 'Point Budget', value: '768–4096' },
      { label: 'Jitter', value: '0.03–0.18' },
    ],
  },
  surface_patch: {
    summary: 'パネルや布片のような面分割表現です。',
    bestSources: ['plane', 'text'],
    useCases: ['パッチ面', '柔らかい構造', '分節表現'],
    tips: ['Resolution は上げすぎると重くなります。', 'Relax は 0.2–0.5 が扱いやすいです。'],
    recommendedRanges: [
      { label: 'Resolution', value: '24–72' },
      { label: 'Relax', value: '0.15–0.50' },
      { label: 'Opacity', value: '0.40–0.85' },
    ],
  },
  brush_surface: {
    summary: '筆致・塗膜系。画材感を足したい時の面表現です。',
    bestSources: ['plane', 'text', 'image'],
    useCases: ['画材感', '絵画的表面', '荒れた皮膜'],
    tips: ['Layers と Jitter を一緒に上げると筆致感が強くなります。', 'Scale は 0.8–1.6 から始めると崩れにくいです。'],
    recommendedRanges: [
      { label: 'Layers', value: '3–8' },
      { label: 'Jitter', value: '0.10–0.40' },
      { label: 'Scale', value: '0.80–1.60' },
    ],
  },
  fiber_field: {
    summary: '繊維・糸・束のような線群表現です。',
    bestSources: ['cylinder', 'sphere'],
    useCases: ['糸束', '神経線維', '流線'],
    tips: ['Length と Curl を同時に上げると暴れやすいです。', 'Density は 0.35–0.65 が基準です。'],
    recommendedRanges: [
      { label: 'Length', value: '0.45–1.10' },
      { label: 'Density', value: '0.30–0.65' },
      { label: 'Curl', value: '0.15–0.50' },
    ],
  },
  growth_field: {
    summary: '枝分かれ・増殖・樹状構造に向いた表現です。',
    bestSources: ['sphere', 'plane'],
    useCases: ['樹状構造', '神経網', '増殖場'],
    tips: ['Branches を増やしたら Count を少し下げると破綻しにくいです。', 'Spread は 0.35–0.60 が基準です。'],
    recommendedRanges: [
      { label: 'Branches', value: '4–9' },
      { label: 'Length', value: '0.70–1.15' },
      { label: 'Spread', value: '0.30–0.60' },
    ],
  },
  deposition_field: {
    summary: '堆積・地層・表面累積系の表現です。',
    bestSources: ['plane', 'image'],
    useCases: ['堆積層', '地形', '積層面'],
    tips: ['Relief を上げすぎると輪郭が潰れやすいです。', 'Bands は 4–7 が見やすいです。'],
    recommendedRanges: [
      { label: 'Relief', value: '0.25–0.65' },
      { label: 'Erosion', value: '0.10–0.35' },
      { label: 'Bands', value: '3–7' },
    ],
  },
  crystal_aggregate: {
    summary: '結晶塊・クラスター表現です。',
    bestSources: ['sphere', 'cube'],
    useCases: ['結晶群', '鉱物感', '凝集体'],
    tips: ['Scale と Density を上げすぎると塊感が失われます。', 'Glass か Chrome が相性良好です。'],
    recommendedRanges: [
      { label: 'Scale', value: '0.90–1.60' },
      { label: 'Density', value: '0.35–0.70' },
      { label: 'Spread', value: '0.18–0.45' },
    ],
  },
  erosion_trail: {
    summary: '風化痕・侵食痕・流れ跡のような痕跡表現です。',
    bestSources: ['plane', 'text'],
    useCases: ['痕跡', '風化', '擦過線'],
    tips: ['Length を上げたら Drift は控えめが安定です。', 'Density は 0.4–0.6 から始めると見やすいです。'],
    recommendedRanges: [
      { label: 'Density', value: '0.35–0.65' },
      { label: 'Length', value: '0.60–1.10' },
      { label: 'Drift', value: '0.12–0.38' },
    ],
  },
  voxel_lattice: {
    summary: '格子・ブロック・足場構造の表現です。',
    bestSources: ['cube', 'plane'],
    useCases: ['格子体', '足場', '構造モデル'],
    tips: ['Snap を高めるとブロック感が強くなります。', 'Wireframe は構造閲覧向きです。'],
    recommendedRanges: [
      { label: 'Scale', value: '1.00–1.40' },
      { label: 'Density', value: '0.30–0.55' },
      { label: 'Snap', value: '0.55–0.85' },
    ],
  },
  crystal_deposition: {
    summary: '堆積面に結晶が生える混成表現です。',
    bestSources: ['plane', 'image'],
    useCases: ['鉱化表面', '析出', '地質皮膜'],
    tips: ['Relief と Crystal Scale の両方を上げすぎない方が見やすいです。', 'Density は 0.45–0.65 が基準です。'],
    recommendedRanges: [
      { label: 'Crystal Scale', value: '1.05–1.50' },
      { label: 'Density', value: '0.42–0.66' },
      { label: 'Relief', value: '0.30–0.58' },
    ],
  },
  reaction_diffusion: {
    summary: '反応拡散の模様形成表現です。',
    bestSources: ['plane', 'text'],
    useCases: ['皮膚模様', '有機パターン', 'セル状面'],
    tips: ['Feed と Kill は近い値でも模様が大きく変わります。', 'Scale は 0.9–1.4 が安定です。'],
    recommendedRanges: [
      { label: 'Feed', value: '0.020–0.036' },
      { label: 'Kill', value: '0.045–0.062' },
      { label: 'Warp', value: '0.10–0.32' },
    ],
  },
  volume_fog: {
    summary: '霧・煙・大気層のような体積表現です。',
    bestSources: ['sphere', 'cube'],
    useCases: ['霧層', '気配', '空間密度'],
    tips: ['Opacity は低めから始めると破綻しにくいです。', 'Slices は 14–28 が実用域です。'],
    recommendedRanges: [
      { label: 'Density', value: '0.18–0.42' },
      { label: 'Depth', value: '0.45–0.90' },
      { label: 'Slices', value: '14–28' },
    ],
  },

  cloth_membrane: {
    summary: '布や膜がたわみながら保持される物理寄りの面表現です。',
    bestSources: ['plane', 'text', 'cylinder'],
    useCases: ['布膜', '帆布', '折れと垂れ'],
    tips: ['Fresnel を上げると縁の布感が見えやすくなります。', 'Opacity を少し下げると drape と fold が追いやすくなります。'],
    recommendedRanges: [
      { label: 'Opacity', value: '0.38–0.78' },
      { label: 'Fresnel', value: '0.32–0.82' },
      { label: 'Audio', value: '0.00–0.28' },
    ],
  },
  viscous_flow: {
    summary: '粘性を持つ液膜や流れ跡のような表面表現です。',
    bestSources: ['plane', 'image', 'video'],
    useCases: ['液だれ', '粘性塗膜', '流体的な引きずり'],
    tips: ['Layers と Jitter を上げすぎると smear よりノイズに寄ります。', 'Scale と Opacity を少し高めると pooling が見えやすくなります。'],
    recommendedRanges: [
      { label: 'Layers', value: '4–9' },
      { label: 'Jitter', value: '0.10–0.34' },
      { label: 'Scale', value: '0.95–1.45' },
    ],
  },
  granular_fall: {
    summary: '砂・灰・粒状体が落下し堆積するような結晶寄り粒子表現です。',
    bestSources: ['sphere', 'plane', 'video'],
    useCases: ['砂山', '灰の落下', '粒状堆積'],
    tips: ['Spread を上げると pile 感が減るので Density と併用してください。', 'Halftone や Classic が粒状感を確認しやすいです。'],
    recommendedRanges: [
      { label: 'Scale', value: '0.78–1.25' },
      { label: 'Density', value: '0.48–0.82' },
      { label: 'Spread', value: '0.18–0.40' },
    ],
  },
  fracture_grammar: {
    summary: '割れの文法で枝と亀裂を生成する構造表現です。',
    bestSources: ['plane', 'text', 'grid'],
    useCases: ['亀裂網', '破断記法', 'plate fracture'],
    tips: ['Branches は多すぎると growth に寄るため、Spread を狭めると fracture 感が保てます。', 'Grid source では syntax 感が強く出ます。'],
    recommendedRanges: [
      { label: 'Branches', value: '4–8' },
      { label: 'Length', value: '0.60–1.00' },
      { label: 'Spread', value: '0.20–0.46' },
    ],
  },
  growth_grammar: {
    summary: '再帰的な成長文法で枝・梢・接続を増やす構造表現です。',
    bestSources: ['sphere', 'plane', 'text'],
    useCases: ['樹状増殖', '成長記法', 'recursive scaffold'],
    tips: ['Length と Branches を一緒に上げると grammar 感が増します。', 'Sphere source では arbor、Text source では script 的な伸長が追えます。'],
    recommendedRanges: [
      { label: 'Branches', value: '5–10' },
      { label: 'Length', value: '0.72–1.18' },
      { label: 'Spread', value: '0.32–0.62' },
    ],
  },
  elastic_sheet: {
    summary: '張力と反発をもつ弾性シート表現です。',
    bestSources: ['plane', 'cylinder', 'text'],
    useCases: ['張力膜', '反発面', 'elastic rebound'],
    tips: ['Fresnel は高め、Opacity はやや低めから始めると反発差が見えます。'],
    recommendedRanges: [
      { label: 'Opacity', value: '0.40–0.78' },
      { label: 'Fresnel', value: '0.36–0.86' },
      { label: 'Audio', value: '0.00–0.30' },
    ],
  },
  capillary_sheet: {
    summary: '吸い上げと浸潤をもつ受け皿面です。',
    bestSources: ['text', 'image', 'plane'],
    useCases: ['吸い込み面', 'capillary ledger', '受け皿'],
    tips: ['Relief と Bands を少し高めると soak band が見やすいです。'],
    recommendedRanges: [
      { label: 'Relief', value: '0.28–0.62' },
      { label: 'Erosion', value: '0.08–0.28' },
      { label: 'Bands', value: '4–8' },
    ],
  },
  sediment_stack: {
    summary: '層理と滑り面を持つ堆積体です。',
    bestSources: ['plane', 'sphere', 'grid'],
    useCases: ['地層体', 'pile strata', '堆積塊'],
    tips: ['Density を少し高め、Spread を抑えると stack 感が保てます。'],
    recommendedRanges: [
      { label: 'Scale', value: '0.72–1.08' },
      { label: 'Density', value: '0.56–0.84' },
      { label: 'Spread', value: '0.12–0.28' },
    ],
  },
  cellular_front: {
    summary: '前線状に進行し分岐するセル表現です。',
    bestSources: ['grid', 'text', 'plane'],
    useCases: ['front edge', 'cellular automata', '分岐前線'],
    tips: ['Feed/Kill を小さく変えるだけでも front の性質が変わります。'],
    recommendedRanges: [
      { label: 'Feed', value: '0.020–0.034' },
      { label: 'Kill', value: '0.044–0.058' },
      { label: 'Warp', value: '0.10–0.28' },
    ],
  },
  biofilm_skin: {
    summary: '湿り気を帯びた群体膜が広がる、生物皮膜寄りの反応拡散面です。',
    bestSources: ['image', 'video', 'plane'],
    useCases: ['biofilm colony', '濡れた群体膜', 'living skin surface'],
    tips: ['Image / Video source を使うと colony pooling が見えやすくなります。', 'Warp を少し高めると湿った縁と瘢痕の差が出やすくなります。'],
    recommendedRanges: [
      { label: 'Feed', value: '0.018–0.030' },
      { label: 'Kill', value: '0.038–0.050' },
      { label: 'Warp', value: '0.18–0.40' },
    ],
  },
  elastic_lattice: {
    summary: '弾性をもつ格子足場表現です。',
    bestSources: ['grid', 'cube', 'cylinder'],
    useCases: ['elastic scaffold', 'span beam', '張力格子'],
    tips: ['Snap は中程度、Scale は少し高めが span 差を見やすくします。'],
    recommendedRanges: [
      { label: 'Scale', value: '1.00–1.28' },
      { label: 'Density', value: '0.28–0.52' },
      { label: 'Snap', value: '0.38–0.72' },
    ],
  },
  viscoelastic_membrane: {
    summary: '記憶を持つ粘弾性膜で、垂れと反発が同居する面表現です。',
    bestSources: ['plane', 'cylinder', 'text'],
    useCases: ['粘弾性膜', '遅れて戻る皮膜', 'memory sheet'],
    tips: ['Fresnel を高め、Audio を低中域にすると rebound lag が見やすくなります。'],
    recommendedRanges: [
      { label: 'Opacity', value: '0.42–0.78' },
      { label: 'Fresnel', value: '0.42–0.86' },
      { label: 'Audio', value: '0.04–0.30' },
    ],
  },
  percolation_sheet: {
    summary: '浸透経路が枝分かれしながら広がる受け皿面です。',
    bestSources: ['text', 'image', 'plane'],
    useCases: ['浸潤面', 'percolation ledger', 'channel soak'],
    tips: ['Relief と Bands を少し高め、Erosion を低めにすると channel 差が見やすいです。'],
    recommendedRanges: [
      { label: 'Relief', value: '0.34–0.68' },
      { label: 'Erosion', value: '0.06–0.24' },
      { label: 'Bands', value: '5–9' },
    ],
  },
  talus_heap: {
    summary: '斜面で崩積した角張った粒塊表現です。',
    bestSources: ['plane', 'sphere', 'grid'],
    useCases: ['talus slope', '崩積斜面', 'angular pile'],
    tips: ['Spread を低め、Density を高めにすると heap 感が保てます。'],
    recommendedRanges: [
      { label: 'Scale', value: '0.62–1.02' },
      { label: 'Density', value: '0.62–0.90' },
      { label: 'Spread', value: '0.10–0.24' },
    ],
  },
  corrosion_front: {
    summary: '腐食が前線として這い、穴食いと縁食いが進む表現です。',
    bestSources: ['grid', 'text', 'plane'],
    useCases: ['etch front', '腐食面', 'pitted plate'],
    tips: ['Feed/Kill を近づけると front edge が強く、Warp を上げると pit が増えます。'],
    recommendedRanges: [
      { label: 'Feed', value: '0.018–0.030' },
      { label: 'Kill', value: '0.040–0.054' },
      { label: 'Warp', value: '0.14–0.34' },
    ],
  },
  creep_lattice: {
    summary: 'ゆっくりたわみながら流れるように変形する格子足場です。',
    bestSources: ['grid', 'cube', 'cylinder'],
    useCases: ['creeping scaffold', '梁のたわみ', 'slow span drift'],
    tips: ['Snap をやや低め、Scale を高めると creep が見やすくなります。'],
    recommendedRanges: [
      { label: 'Scale', value: '1.02–1.34' },
      { label: 'Density', value: '0.26–0.48' },
      { label: 'Snap', value: '0.24–0.56' },
    ],
  },
};
