import { Color, Vector2, Vector3, Vector4 } from 'three';
import type { ParticleConfig } from '../types';
import { MAX_INTER_LAYER_COLLIDERS } from '../lib/appStateCollision';

export function createParticleUniforms(config: ParticleConfig, isAux: boolean) {
  return {
    uTime: { value: 0 },
    uOpacity: { value: config.opacity },
    uColor: { value: new Color('#ffffff') },
    uHueShift: { value: 0 },
    uContrast: { value: config.contrast },
    uInkMode: { value: config.particleColor === 'black' ? 1 : 0 },
    uSoftness: { value: config.particleSoftness },
    uGlow: { value: config.particleGlow },
    uAudioBass: { value: 0 },
    uAudioTreble: { value: 0 },
    uAudioBassMotion: { value: 0 },
    uAudioTrebleMotion: { value: 0 },
    uAudioBassSize: { value: 0 },
    uAudioTrebleSize: { value: 0 },
    uAudioBassAlpha: { value: 0 },
    uAudioTrebleAlpha: { value: 0 },
    uAudioBassLine: { value: 0 },
    uAudioTrebleLine: { value: 0 },
    uAudioBandAMotion: { value: 0 },
    uAudioBandASize: { value: 0 },
    uAudioBandAAlpha: { value: 0 },
    uAudioBandBMotion: { value: 0 },
    uAudioBandBSize: { value: 0 },
    uAudioBandBAlpha: { value: 0 },
    uAudioPulse: { value: 0 },
    uAudioMorph: { value: 0 },
    uAudioShatter: { value: 0 },
    uAudioTwist: { value: 0 },
    uAudioBend: { value: 0 },
    uAudioWarp: { value: 0 },
    uGlobalSpeed: { value: 1.0 },
    uGlobalAmp: { value: 1.0 },
    uGlobalNoiseScale: { value: 1.0 },
    uGlobalComplexity: { value: 1.0 },
    uGlobalEvolution: { value: 1.0 },
    uGlobalFidelity: { value: 1.0 },
    uGlobalOctaveMult: { value: 1.0 },
    uGlobalFreq: { value: 1.0 },
    uGlobalRadius: { value: 100.0 },
    uGlobalSize: { value: 1.0 },
    uGravity: { value: 0 },
    uWind: { value: new Vector3(0, 0, 0) },
    uSpin: { value: new Vector3(0, 0, 0) },
    uBoundaryY: { value: 0 },
    uBoundaryEnabled: { value: 0 },
    uBoundaryBounce: { value: 0 },
    uViscosity: { value: 0 },
    uFluidForce: { value: 0 },
    uResistance: { value: 0 },
    uMoveWithWind: { value: 0 },
    uNeighborForce: { value: 0 },
    uCollisionMode: { value: 0 },
    uCollisionRadius: { value: 20 },
    uRepulsion: { value: 10 },
    uTrail: { value: 0 },
    uLife: { value: 0 },
    uLifeSpread: { value: 0 },
    uLifeSizeBoost: { value: 0 },
    uLifeSizeTaper: { value: 0 },
    uBurst: { value: 0 },
    uBurstPhase: { value: 0 },
    uBurstMode: { value: 0 },
    uBurstWaveform: { value: 0 },
    uBurstSweepSpeed: { value: 1 },
    uBurstSweepTilt: { value: 0.35 },
    uBurstConeWidth: { value: 0.4 },
    uEmitterOrbitSpeed: { value: 0 },
    uEmitterOrbitRadius: { value: 0 },
    uEmitterPulseAmount: { value: 0 },
    uTrailDrag: { value: 0 },
    uTrailTurbulence: { value: 0 },
    uTrailDrift: { value: 0 },
    uVelocityGlow: { value: 0 },
    uVelocityAlpha: { value: 0 },
    uFlickerAmount: { value: 0 },
    uFlickerSpeed: { value: 1 },
    uStreak: { value: 0 },
    uSpriteMode: { value: 0 },
    uAuxLife: { value: 100 },
    uIsAux: { value: isAux ? 1 : 0 },
    uAffectPos: { value: 1.0 },
    uMouse: { value: new Vector2(0, 0) },
    uMouseForce: { value: 0 },
    uMouseRadius: { value: 100 },
    uIsOrthographic: { value: 0 },
    uInterLayerEnabled: { value: 0 },
    uInterLayerColliderCount: { value: 0 },
    uInterLayerColliders: { value: Array.from({ length: MAX_INTER_LAYER_COLLIDERS }, () => new Vector4(0, 0, 0, 0)) },
    uInterLayerStrength: { value: 0 },
    uInterLayerPadding: { value: 0 },
    uSdfEnabled: { value: 0 },
    uSdfShape: { value: 0 },
    uSdfLight: { value: new Vector2(0.5, 0.7) },
    uSdfSpecular: { value: 0.8 },
    uSdfShininess: { value: 16.0 },
    uSdfAmbient: { value: 0.3 },
    uInstanced3D: { value: 0 },
    uInstanced3DScale: { value: 1.0 },
    uMediaReactive: { value: 0 },
    uMediaSizeBoost: { value: 0 },
    uMediaAlphaBoost: { value: 0 },
    uMediaGlyphInstancing: { value: 0 },
    uMediaGlyphDepthBoost: { value: 0 },
    uMediaGlyphTwist: { value: 0 },
    uMediaGlyphQuantize: { value: 0 },
  };
}
