import type { ParticleConfig } from '../types';
import { AUDIO_ARCHITECTURE_VERSION, AUDIO_FEATURE_FRAME_VERSION, createDefaultAudioRoutes } from './audioReactiveConfig';

export const APP_STATE_DEFAULT_AUDIO_SYNTH: Partial<ParticleConfig> = {
  // Audio
  audioEnabled: false,
  audioSourceMode: 'microphone',
  audioSensitivity: 1.0,
  audioBeatScale: 0.5,
  audioJitterScale: 0.5,
  audioGateThreshold: 0.04,
  audioResponseCurve: 0.85,
  audioPulseDecay: 0.18,
  audioArchitectureVersion: AUDIO_ARCHITECTURE_VERSION,
  audioFeatureFrameVersion: AUDIO_FEATURE_FRAME_VERSION,
  audioRoutesEnabled: false,
  audioRoutes: createDefaultAudioRoutes(),
  audioCurationHistory: [],
  audioCurationQueueFilterMode: 'hide-curated',
  audioLegacySliderVisibilityMode: 'retired-safe',
  audioSequenceEnterThreshold: 0.6,
  audioSequenceExitThreshold: 0.28,
  audioSequenceStepAdvanceCooldownMs: 320,
  audioSequenceCrossfadeCooldownMs: 420,
  audioSequenceRandomizeSeedCooldownMs: 900,
  audioSequenceSeedMutationStrength: 0.72,
  audioSequenceSeedMutationScope: 'hybrid',
  audioBassMotionScale: 1.2,
  audioBassSizeScale: 1.35,
  audioBassAlphaScale: 1.15,
  audioTrebleMotionScale: 1.15,
  audioTrebleSizeScale: 1.1,
  audioTrebleAlphaScale: 1.1,
  audioPulseScale: 1.35,
  audioBurstScale: 1.25,
  audioScreenScale: 1.15,
  audioMorphScale: 1.1,
  audioShatterScale: 1.2,
  audioTwistScale: 1.2,
  audioBendScale: 1.1,
  audioWarpScale: 1.25,
  audioLineScale: 1.2,
  audioCameraScale: 1.15,
  audioHueShiftScale: 0,
  // Custom Frequency Bands (default off, 0 scale = no effect)
  audioBandALowHz: 40,
  audioBandAHighHz: 200,
  audioBandAMotionScale: 0,
  audioBandASizeScale: 0,
  audioBandAAlphaScale: 0,
  audioBandBLowHz: 2000,
  audioBandBHighHz: 8000,
  audioBandBMotionScale: 0,
  audioBandBSizeScale: 0,
  audioBandBAlphaScale: 0,
  midiPreferredInputId: '',
  midiVelocityGain: 1,
  midiDecay: 1.6,
  midiBassCC: 74,
  midiTrebleCC: 1,
  midiBandACC: 2,
  midiBandBCC: 3,

  // Synth
  synthWaveform: 'sawtooth',
  synthScale: 'minor-pentatonic',
  synthBaseFrequency: 110,
  synthTempo: 108,
  synthVolume: 0.18,
  synthCutoff: 1200,
  synthPatternDepth: 0.65,
  synthPattern: [0, 2, 4, 5, 3, 1, 4, 6],
};
