import type { ParticleConfig } from '../types';

export const APP_STATE_DEFAULT_GPGPU: Partial<ParticleConfig> = {
  // GPGPU Layer
  gpgpuEnabled: false,
  gpgpuCount: 65536,
  gpgpuGravity: 0.2,
  gpgpuTurbulence: 0.4,
  gpgpuBounce: 0.65,
  gpgpuBounceRadius: 150,
  gpgpuSize: 1.5,
  gpgpuSpeed: 1.0,
  gpgpuColor: '#88aaff',
  gpgpuOpacity: 0.7,
  gpgpuAudioReactive: false,
  gpgpuAudioBlast: 1.5,
  gpgpuTrailEnabled: false,
  gpgpuTrailLength: 8,
  gpgpuTrailFade: 0.75,
  gpgpuTrailVelocityScale: 1.0,
  gpgpuGeomMode: 'point' as const,
  gpgpuGeomVelocityAlign: false,
  gpgpuGeomScale: 1.0,
  gpgpuNBodyEnabled: false,
  gpgpuNBodyStrength: 1.0,
  gpgpuNBodyRepulsion: 5.0,
  gpgpuNBodySoftening: 2.0,
  gpgpuNBodySampleCount: 16,
  gpgpuVelColorEnabled: false,
  gpgpuVelColorHueMin: 200,
  gpgpuVelColorHueMax: 360,
  gpgpuVelColorSaturation: 0.9,
  gpgpuAgeEnabled: false,
  gpgpuAgeMax: 8.0,
  gpgpuAgeFadeIn: 0.1,
  gpgpuAgeFadeOut: 0.2,
  gpgpuCurlEnabled: false,
  gpgpuCurlStrength: 1.0,
  gpgpuCurlScale: 0.008,
  gpgpuBoidsEnabled: false,
  gpgpuBoidsSeparation: 1.0,
  gpgpuBoidsAlignment: 0.5,
  gpgpuBoidsCohesion: 0.3,
  gpgpuBoidsRadius: 30.0,
  gpgpuAttractorEnabled: false,
  gpgpuAttractorType: 'lorenz' as const,
  gpgpuAttractorStrength: 1.0,
  gpgpuAttractorScale: 8.0,
  // Vortex
  gpgpuVortexEnabled: false,
  gpgpuVortexStrength: 1.0,
  gpgpuVortexTilt: 0.0,
  // Wind
  gpgpuWindEnabled: false,
  gpgpuWindStrength: 1.0,
  gpgpuWindX: 1.0,
  gpgpuWindY: 0.0,
  gpgpuWindZ: 0.0,
  gpgpuWindGust: 0.3,
  // Gravity Well
  gpgpuWellEnabled: false,
  gpgpuWellStrength: 1.0,
  gpgpuWellSoftening: 10.0,
  gpgpuWellOrbit: 0.5,
  // Elastic Spring
  gpgpuElasticEnabled: false,
  gpgpuElasticStrength: 0.5,
  // Magnetic
  gpgpuMagneticEnabled: false,
  gpgpuMagneticStrength: 1.0,
  gpgpuMagneticBX: 0.0,
  gpgpuMagneticBY: 1.0,
  gpgpuMagneticBZ: 0.0,
  // SPH Fluid
  gpgpuSphEnabled: false,
  gpgpuSphPressure: 3.0,
  gpgpuSphViscosity: 0.5,
  gpgpuSphRadius: 40.0,
  gpgpuSphRestDensity: 2.0,
  // Vector Field
  gpgpuVFieldEnabled: false,
  gpgpuVFieldType: 'spiral' as const,
  gpgpuVFieldStrength: 1.0,
  gpgpuVFieldScale: 0.005,
  // Spring (to spawn pos)
  gpgpuSpringEnabled: false,
  gpgpuSpringStrength: 1.0,
  // Verlet Integration
  gpgpuVerletEnabled: false,
  // SDF Collider
  gpgpuSdfEnabled: false,
  gpgpuSdfShape: 'sphere' as const,
  gpgpuSdfX: 0.0,
  gpgpuSdfY: 0.0,
  gpgpuSdfZ: 0.0,
  gpgpuSdfSize: 80.0,
  gpgpuSdfBounce: 0.5,
  // Emission Shape
  gpgpuEmitShape: 'sphere' as const,
  // Color over Lifetime
  gpgpuAgeColorEnabled: false,
  gpgpuAgeColorYoung: '#00aaff',
  gpgpuAgeColorOld: '#ff4400',
  // Size over Lifetime
  gpgpuAgeSizeEnabled: false,
  gpgpuAgeSizeStart: 2.0,
  gpgpuAgeSizeEnd: 0.2,
  // Mouse Force
  gpgpuMouseEnabled: false,
  gpgpuMouseStrength: 2.0,
  gpgpuMouseRadius: 150.0,
  gpgpuMouseMode: 'attract' as const,
  // Streak Rendering
  gpgpuStreakEnabled: false,
  gpgpuStreakLength: 15.0,
  gpgpuStreakOpacity: 0.6,
  // Sort-based Transparency
  gpgpuSortEnabled: false,
  // Fluid Advection
  gpgpuFluidEnabled: false,
  gpgpuFluidDiffuse: 0.02,
  gpgpuFluidDecay: 0.01,
  gpgpuFluidStrength: 1.0,
  gpgpuFluidInfluence: 0.8,
  gpgpuFluidScale: 1.5,
  gpgpuFluidExtForce: false,
  // WebGPU Compute Backend
  gpgpuWebGPUEnabled: false,
  gpgpuExecutionPreference: 'auto',
  // Metaballs
  gpgpuMetaballEnabled: false,
  gpgpuMetaballResolution: 28,
  gpgpuMetaballStrength: 1.2,
  gpgpuMetaballIsoLevel: 80,
  gpgpuMetaballColor: '#88aaff',
  gpgpuMetaballStyle: 'classic',
  gpgpuMetaballOpacity: 0.75,
  gpgpuMetaballWireframe: false,
  gpgpuMetaballParticleLimit: 1024,
  gpgpuMetaballMetalness: 0.5,
  gpgpuMetaballRoughness: 0.2,
  gpgpuMetaballSubtract: 12,
  gpgpuMetaballUpdateSkip: 1,
  // Ribbon Trail
  gpgpuRibbonEnabled: false,
  gpgpuRibbonWidth: 4.0,
  gpgpuRibbonTaper: 0.8,
  gpgpuRibbonOpacity: 0.5,
  gpgpuRibbonMaxSegLen: 80.0,
  // Tube Trail
  gpgpuTubeEnabled: false,
  gpgpuTubeRadius: 3.0,
  gpgpuTubeOpacity: 0.6,
  // Smooth Tube
  gpgpuSmoothTubeEnabled: false,
  gpgpuSmoothTubeCount: 32,
  gpgpuSmoothTubeRadius: 2.0,
  gpgpuSmoothTubeHistory: 12,
  gpgpuSmoothTubeColor: '#aaccff',
  gpgpuSmoothTubeOpacity: 0.7,
  // Volumetric Ray Marching
  gpgpuVolumetricEnabled: false,
  gpgpuVolumetricRadius: 12.0,
  gpgpuVolumetricDensity: 2.0,
  gpgpuVolumetricColor: '#aaccff',
  gpgpuVolumetricOpacity: 0.8,
  gpgpuVolumetricSteps: 8,
};
