import type { AudioReactiveCapability } from '../types/audioReactive';

export const AUDIO_REACTIVE_CAPABILITY_REGISTRY: AudioReactiveCapability[] = [
  {
    system: 'particle',
    label: 'Particle Core',
    targets: [
      'particle.bassMotion',
      'particle.trebleMotion',
      'particle.bandAMotion',
      'particle.bandBMotion',
      'particle.bassSize',
      'particle.trebleSize',
      'particle.bandASize',
      'particle.bandBSize',
      'particle.bassAlpha',
      'particle.trebleAlpha',
      'particle.bandAAlpha',
      'particle.bandBAlpha',
      'particle.pulse',
      'particle.morph',
      'particle.shatter',
      'particle.twist',
      'particle.bend',
      'particle.warp',
      'postfx.hueShift',
    ],
    recommendedSources: ['bass', 'treble', 'pulse', 'bandA', 'bandB', 'centroid', 'flux'],
    supportsTrigger: true,
    supportsContinuous: true,
    notes: '現在 live。legacy slider と並走しつつ granular target へ移行できる。',
  },
  {
    system: 'line',
    label: 'Line / Fiber / Glyph',
    targets: [
      'line.opacity',
      'line.width',
      'line.connectDistance',
      'line.shimmer',
      'line.flickerSpeed',
      'line.velocityGlow',
      'line.velocityAlpha',
      'line.burstPulse',
    ],
    recommendedSources: ['treble', 'pulse', 'bandB', 'flux', 'centroid', 'mid'],
    supportsTrigger: true,
    supportsContinuous: true,
    notes: 'line runtime で live。接続距離や幅まで route で駆動できる。',
  },
  {
    system: 'fog',
    label: 'Fog / Volumetric',
    targets: ['fog.density', 'fog.opacity', 'fog.glow', 'fog.drift', 'fog.anisotropy', 'fog.depth'],
    recommendedSources: ['level', 'rms', 'pulse', 'centroid', 'spread', 'lowMid'],
    supportsTrigger: false,
    supportsContinuous: true,
    notes: 'volume fog runtime で live。密度・発光・ドリフト・異方性を route で追加できる。',
  },
  {
    system: 'growth',
    label: 'Growth / Deposition / Erosion',
    targets: ['growth.opacity', 'growth.length', 'growth.branches', 'growth.spread', 'fiber.opacity', 'fiber.length', 'fiber.density', 'fiber.spread'],
    recommendedSources: ['bass', 'pulse', 'beat', 'onset', 'bandA'],
    supportsTrigger: true,
    supportsContinuous: true,
    notes: 'growth field runtime で live。枝数・長さ・広がり・不透明度を補正でき、fiber.* alias で hybrid fiber field も同じ route 語彙へ接続する。',
  },
  {
    system: 'camera',
    label: 'Camera Rig',
    targets: ['camera.shake', 'camera.impulse', 'camera.orbitSpeed', 'camera.fov', 'camera.dolly', 'camera.zoom'],
    recommendedSources: ['bass', 'pulse', 'beat', 'centroid'],
    supportsTrigger: true,
    supportsContinuous: true,
    notes: 'camera rig で live。shake / impulse / orbit / fov / dolly / zoom 語彙を許可。',
  },
  {
    system: 'screen',
    label: 'Screen Overlay FX',
    targets: [
      'screen.scanlineIntensity',
      'screen.noiseIntensity',
      'screen.vignetteIntensity',
      'screen.pulseIntensity',
      'screen.pulseSpeed',
      'screen.interferenceIntensity',
      'screen.persistenceIntensity',
      'screen.splitIntensity',
      'screen.sweepIntensity',
      'overlay.scanline',
      'overlay.noise',
      'overlay.vignette',
      'overlay.pulse',
      'overlay.pulseSpeed',
      'overlay.interference',
      'overlay.persistence',
      'overlay.split',
      'overlay.sweep',
    ],
    recommendedSources: ['pulse', 'treble', 'flux', 'onset', 'centroid'],
    supportsTrigger: true,
    supportsContinuous: true,
    notes: 'screen overlay で live。screen.* と overlay.* の両語彙を受ける。',
  },
  {
    system: 'crystal',
    label: 'Crystal Aggregate',
    targets: [
      'crystal.opacity',
      'crystal.scale',
      'crystal.spread',
      'crystal.wireframe',
      'crystal.glow',
      'crystalAggregate.opacity',
      'crystalAggregate.scale',
      'crystalAggregate.spread',
      'crystalAggregate.wireframe',
      'crystalAggregate.glow',
      'granular.opacity',
      'granular.scale',
      'granular.spread',
    ],
    recommendedSources: ['bass', 'pulse', 'centroid', 'flux', 'bandA'],
    supportsTrigger: true,
    supportsContinuous: true,
    notes: '現在 live。base 語彙に加え crystalAggregate.* alias と granular.* alias を許可。',
  },
  {
    system: 'voxel',
    label: 'Voxel / Lattice',
    targets: [
      'voxel.opacity',
      'voxel.scale',
      'voxel.snap',
      'voxel.jitter',
      'voxel.wireframe',
      'voxelLattice.opacity',
      'voxelLattice.scale',
      'voxelLattice.snap',
      'voxelLattice.jitter',
      'voxelLattice.wireframe',
    ],
    recommendedSources: ['bass', 'pulse', 'centroid', 'flux', 'lowMid'],
    supportsTrigger: true,
    supportsContinuous: true,
    notes: '現在 live。base 語彙に加え voxelLattice.* alias を許可。',
  },
  {
    system: 'reaction',
    label: 'Reaction Diffusion',
    targets: [
      'reaction.opacity',
      'reaction.warp',
      'reaction.feed',
      'reaction.kill',
      'reaction.relief',
      'reactionField.opacity',
      'reactionField.warp',
      'reactionField.feed',
      'reactionField.kill',
      'reactionField.relief',
      'reaction.seedWarp',
    ],
    recommendedSources: ['pulse', 'onset', 'flux', 'centroid', 'bass'],
    supportsTrigger: true,
    supportsContinuous: true,
    notes: '現在 live。reactionField.* と reaction.seedWarp alias を許可。',
  },
  {
    system: 'deposition',
    label: 'Deposition / Crystal Deposition',
    targets: [
      'deposition.opacity',
      'deposition.relief',
      'deposition.erosion',
      'deposition.bands',
      'deposition.scale',
      'deposition.wireframe',
      'depositionField.opacity',
      'depositionField.relief',
      'depositionField.erosion',
      'depositionField.bands',
      'depositionField.scale',
      'depositionField.wireframe',
      'crystalDeposition.opacity',
      'crystalDeposition.relief',
      'crystalDeposition.scale',
      'crystalDeposition.wireframe',
    ],
    recommendedSources: ['bass', 'pulse', 'centroid', 'flux', 'onset', 'lowMid'],
    supportsTrigger: true,
    supportsContinuous: true,
    notes: '現在 live。depositionField.* と crystalDeposition.* alias を許可。',
  },
  {
    system: 'surface',
    label: 'Surface / Membrane / Shell / Brush',
    targets: [
      'surface.displacement',
      'surface.opacity',
      'surface.relief',
      'surface.wireframe',
      'surface.sliceDepth',
      'brush.displacement',
      'brush.opacity',
      'brush.relief',
      'brush.sliceDepth',
      'patch.displacement',
      'patch.opacity',
      'patch.relief',
      'patch.wireframe',
      'patch.sliceDepth',
      'membrane.displacement',
      'membrane.opacity',
      'membrane.relief',
      'membrane.wireframe',
      'membrane.sliceDepth',
      'shell.displacement',
      'shell.opacity',
      'shell.relief',
      'shell.wireframe',
      'shell.sliceDepth',
    ],
    recommendedSources: ['bass', 'treble', 'pulse', 'bandA', 'bandB', 'centroid'],
    supportsTrigger: true,
    supportsContinuous: true,
    notes: '現在 live。共通 surface.* に加え brush / patch / membrane / shell alias を許可。',
  },
  {
    system: 'gpgpu',
    label: 'GPGPU Layer',
    targets: [
      'gpgpu.audioBlast',
      'gpgpu.gravity',
      'gpgpu.turbulence',
      'gpgpu.size',
      'gpgpu.opacity',
      'gpgpu.trailLength',
      'gpgpu.ribbonWidth',
      'gpgpu.volumetricDensity',
    ],
    recommendedSources: ['bass', 'pulse', 'flux', 'centroid', 'lowMid'],
    supportsTrigger: true,
    supportsContinuous: true,
    notes: '現在 live。GPGPU simulation / trail / volumetric の主要ノブを route で補正できる。',
  },
  {
    system: 'sequence',
    label: 'Sequence / Preset Driver',
    targets: [
      'sequence.stepAdvance',
      'sequence.crossfade',
      'sequence.randomizeSeed',
      'sequence.seedMutation',
      'sequence.seedMutation.motion',
      'sequence.seedMutation.structure',
      'sequence.seedMutation.surface',
      'sequence.seedMutation.hybrid',
    ],
    recommendedSources: ['pulse', 'beat', 'onset'],
    supportsTrigger: true,
    supportsContinuous: false,
    notes: '現在 live。randomizeSeed と同義の sequence.seedMutation alias に加え、motion / structure / surface / hybrid の scoped seed-mutation target を含む。',
  },
];

function getAudioReactiveCapability(system: string) {
  return AUDIO_REACTIVE_CAPABILITY_REGISTRY.find((entry) => entry.system === system) ?? null;
}
