import type { ExpressionAtlasBundle } from './expressionAtlasTypes';
import { layerPatch } from './expressionAtlasCore';

export const EXPRESSION_ATLAS_BUNDLES_ANCHORS_GRANULAR: ExpressionAtlasBundle[] = [
  { id: 'viscoelastic-memory-anchor', label: 'Viscoelastic Memory Anchor', summary: 'plane / cylinder で viscoelastic membrane の memory sag と rebound lag を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'viscoelastic_membrane', Source: layerIndex === 2 ? 'plane' : 'cylinder', MaterialStyle: 'glass', TemporalProfile: layerIndex === 2 ? 'rebound' : 'inhale', TemporalStrength: 0.26, TemporalSpeed: 0.82, Count: 9800, RadiusScale: 1.1, BaseSize: 0.94, SheetOpacity: 0.68, SheetFresnel: 0.78, SheetAudioReactive: 0.16, SheetWireframe: false }) },
  { id: 'percolation-ledger-anchor', label: 'Percolation Ledger Anchor', summary: 'text / image で percolation sheet の channel soak と percolate を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'percolation_sheet', Source: layerIndex === 2 ? 'text' : 'image', MaterialStyle: 'halftone', TemporalProfile: layerIndex === 2 ? 'percolate' : 'saturate', TemporalStrength: 0.28, TemporalSpeed: 0.84, Count: 9600, RadiusScale: 1.0, BaseSize: 0.82, TextMapText: 'FLOW', TextMapSize: 292, TextMapPadding: 42, TextMapWeight: 700, DepositionOpacity: 0.84, DepositionRelief: 0.58, DepositionErosion: 0.16, DepositionBands: 8 }) },
  { id: 'talus-slope-anchor', label: 'Talus Slope Anchor', summary: 'plane / sphere で talus heap の slope spread と slump を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'talus_heap', Source: layerIndex === 2 ? 'plane' : 'sphere', MaterialStyle: 'halftone', TemporalProfile: layerIndex === 2 ? 'slump' : 'ossify', TemporalStrength: 0.24, TemporalSpeed: 0.76, Count: 10800, RadiusScale: 1.0, BaseSize: 0.68, CrystalOpacity: 0.76, CrystalScale: 0.78, CrystalDensity: 0.84, CrystalSpread: 0.16 }) },
  { id: 'corrosion-front-anchor', label: 'Corrosion Front Anchor', summary: 'grid / text で corrosion front の etch edge と fissure を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'corrosion_front', Source: layerIndex === 2 ? 'grid' : 'text', MaterialStyle: 'chrome', TemporalProfile: layerIndex === 2 ? 'fissure' : 'percolate', TemporalStrength: 0.26, TemporalSpeed: 0.86, Count: 9200, RadiusScale: 1.0, BaseSize: 0.8, TextMapText: 'ETCH', TextMapSize: 292, TextMapPadding: 42, TextMapWeight: 700, ReactionOpacity: 0.8, ReactionFeed: 0.023, ReactionKill: 0.044, ReactionScale: 1.08, ReactionWarp: 0.24 }) },
  { id: 'creep-lattice-anchor', label: 'Creep Lattice Anchor', summary: 'grid / cube で creep lattice の slow span drag と rebound を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'creep_lattice', Source: layerIndex === 2 ? 'grid' : 'cube', MaterialStyle: 'glass', TemporalProfile: layerIndex === 2 ? 'slump' : 'rebound', TemporalStrength: 0.22, TemporalSpeed: 0.72, Count: 9400, RadiusScale: 1.0, BaseSize: 0.82, VoxelOpacity: 0.8, VoxelScale: 1.12, VoxelDensity: 0.42, VoxelSnap: 0.34, VoxelWireframe: false }) },
  { id: 'ossify-corrode-cycle-anchor', label: 'Ossify Corrode Cycle Anchor', summary: 'talus / corrosion の対比で ossify と fissure の時間差を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: layerIndex === 2 ? 'talus_heap' : 'corrosion_front', Source: layerIndex === 2 ? 'plane' : 'grid', MaterialStyle: layerIndex === 2 ? 'halftone' : 'chrome', TemporalProfile: layerIndex === 2 ? 'ossify' : 'fissure', TemporalStrength: 0.26, TemporalSpeed: 0.8, Count: layerIndex === 2 ? 10800 : 9200, RadiusScale: 1.0, BaseSize: layerIndex === 2 ? 0.68 : 0.8, CrystalOpacity: 0.76, CrystalScale: 0.78, CrystalDensity: 0.84, CrystalSpread: 0.16, ReactionOpacity: 0.8, ReactionFeed: 0.023, ReactionKill: 0.044, ReactionScale: 1.08, ReactionWarp: 0.24 }) },
];
