import type { ExpressionAtlasBundle } from './expressionAtlasTypes';
import { layerPatch } from './expressionAtlasCore';

export const EXPRESSION_ATLAS_BUNDLES_ANCHORS_FLOW: ExpressionAtlasBundle[] = [
  { id: 'advection-flow-ledger-anchor', label: 'Advection Flow Ledger Anchor', summary: 'plane / image で advection flow の lane shear と intermittent を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'advection_flow', Source: layerIndex === 2 ? 'plane' : 'image', MaterialStyle: 'classic', TemporalProfile: layerIndex === 2 ? 'intermittent' : 'hysteresis', TemporalStrength: 0.24, TemporalSpeed: 0.84, Count: 9400, RadiusScale: 1.0, BaseSize: 0.88, BrushOpacity: 0.8, BrushLayers: 5, BrushScale: 1.02, BrushJitter: 0.12, BrushAudioReactive: 0.06 }) },
  { id: 'vortex-transport-column-anchor', label: 'Vortex Transport Column Anchor', summary: 'sphere / video で vortex transport の spiral lift と erupt を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'vortex_transport', Source: layerIndex === 2 ? 'sphere' : 'video', MaterialStyle: 'glass', TemporalProfile: layerIndex === 2 ? 'erupt' : 'intermittent', TemporalStrength: 0.24, TemporalSpeed: 0.88, Count: 7600, RadiusScale: 1.16, BaseSize: 1.18, FogOpacity: 0.3, FogDensity: 0.38, FogDepth: 0.86, FogScale: 1.0, FogDrift: 0.34, FogSlices: 22, FogGlow: 0.2, FogAnisotropy: 0.56, FogAudioReactive: 0.16 }) },
  { id: 'pressure-cells-basin-anchor', label: 'Pressure Cells Basin Anchor', summary: 'grid / plane で pressure cells の basin spacing と hysteresis を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'pressure_cells', Source: layerIndex === 2 ? 'grid' : 'plane', MaterialStyle: 'halftone', TemporalProfile: layerIndex === 2 ? 'hysteresis' : 'recover', TemporalStrength: 0.24, TemporalSpeed: 0.78, Count: 7200, RadiusScale: 1.0, BaseSize: 1.12, FogOpacity: 0.28, FogDensity: 0.44, FogDepth: 0.62, FogScale: 0.84, FogDrift: 0.12, FogSlices: 20, FogGlow: 0.08, FogAnisotropy: 0.18, FogAudioReactive: 0.1 }) },
  { id: 'avalanche-field-slope-anchor', label: 'Avalanche Field Slope Anchor', summary: 'plane / sphere で avalanche field の runout と fatigue を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'avalanche_field', Source: layerIndex === 2 ? 'plane' : 'sphere', MaterialStyle: 'halftone', TemporalProfile: layerIndex === 2 ? 'fatigue' : 'erupt', TemporalStrength: 0.24, TemporalSpeed: 0.8, Count: 11200, RadiusScale: 1.0, BaseSize: 0.66, CrystalOpacity: 0.74, CrystalScale: 0.82, CrystalDensity: 0.92, CrystalSpread: 0.34, CrystalAudioReactive: 0.06 }) },
  { id: 'jammed-pack-cube-anchor', label: 'Jammed Pack Cube Anchor', summary: 'cube / plane で jammed pack の lock と recover を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'jammed_pack', Source: layerIndex === 2 ? 'cube' : 'plane', MaterialStyle: 'classic', TemporalProfile: layerIndex === 2 ? 'recover' : 'fatigue', TemporalStrength: 0.22, TemporalSpeed: 0.72, Count: 9800, RadiusScale: 1.0, BaseSize: 0.78, CrystalOpacity: 0.82, CrystalScale: 1.02, CrystalDensity: 1.0, CrystalSpread: 0.14, CrystalAudioReactive: 0.04 }) },
];
