import type { ExpressionAtlasBundle } from './expressionAtlasTypes';
import { layerPatch } from './expressionAtlasCore';

export const EXPRESSION_ATLAS_BUNDLES_ANCHORS_PHASE: ExpressionAtlasBundle[] = [
  { id: 'melt-front-film-anchor', label: 'Melt Front Film Anchor', summary: 'plane / image で melt front の thermal bleed と collapse を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'melt_front', Source: layerIndex === 2 ? 'plane' : 'image', MaterialStyle: 'classic', TemporalProfile: layerIndex === 2 ? 'collapse' : 'latency', TemporalStrength: 0.24, TemporalSpeed: 0.82, Count: 9000, RadiusScale: 1.0, BaseSize: 0.92, BrushOpacity: 0.82, BrushLayers: 5, BrushScale: 1.08, BrushJitter: 0.18 }) },
  { id: 'freeze-skin-shell-anchor', label: 'Freeze Skin Shell Anchor', summary: 'sphere / plane で freeze skin の frost lock と invert を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'freeze_skin', Source: layerIndex === 2 ? 'sphere' : 'plane', MaterialStyle: 'glass', TemporalProfile: layerIndex === 2 ? 'invert' : 'emerge', TemporalStrength: 0.22, TemporalSpeed: 0.76, Count: 7600, RadiusScale: 1.08, BaseSize: 1.0, HullOpacity: 0.72, HullFresnel: 0.92, HullPointBudget: 1600, HullJitter: 0.05 }) },
  { id: 'condense-field-basin-anchor', label: 'Condense Field Basin Anchor', summary: 'plane / sphere で condense field の droplet core と emerge を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'condense_field', Source: layerIndex === 2 ? 'plane' : 'sphere', MaterialStyle: 'glass', TemporalProfile: layerIndex === 2 ? 'emerge' : 'latency', TemporalStrength: 0.24, TemporalSpeed: 0.8, Count: 7600, RadiusScale: 1.0, BaseSize: 1.06, FogOpacity: 0.3, FogDensity: 0.48, FogDepth: 0.7, FogScale: 0.9, FogDrift: 0.14, FogSlices: 22, FogGlow: 0.12, FogAnisotropy: 0.22 }) },
  { id: 'evaporative-sheet-ledger-anchor', label: 'Evaporative Sheet Ledger Anchor', summary: 'text / plane で evaporative sheet の edge retreat と latency を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'evaporative_sheet', Source: layerIndex === 2 ? 'text' : 'plane', MaterialStyle: 'halftone', TemporalProfile: layerIndex === 2 ? 'latency' : 'collapse', TemporalStrength: 0.24, TemporalSpeed: 0.86, Count: 8600, RadiusScale: 1.0, BaseSize: 0.84, TextMapText: 'DRY', TextMapSize: 276, TextMapPadding: 36, TextMapWeight: 700, BrushOpacity: 0.7, BrushLayers: 4, BrushScale: 0.96, BrushJitter: 0.14 }) },
  { id: 'sublimate-cloud-ring-anchor', label: 'Sublimate Cloud Ring Anchor', summary: 'ring / video で sublimate cloud の hollow core と invert を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'sublimate_cloud', Source: layerIndex === 2 ? 'ring' : 'video', MaterialStyle: 'glass', TemporalProfile: layerIndex === 2 ? 'invert' : 'collapse', TemporalStrength: 0.24, TemporalSpeed: 0.84, Count: 7000, RadiusScale: 1.04, BaseSize: 1.12, FogOpacity: 0.24, FogDensity: 0.34, FogDepth: 0.92, FogScale: 1.12, FogDrift: 0.26, FogSlices: 20, FogGlow: 0.16, FogAnisotropy: 0.48 }) },
];
