import type { ExpressionAtlasBundle } from './expressionAtlasTypes';
import { layerPatch } from './expressionAtlasCore';

export const EXPRESSION_ATLAS_BUNDLES_ANCHORS_ELASTIC: ExpressionAtlasBundle[] = [
  { id: 'reaction-plate-labyrinth-anchor', label: 'Reaction Plate Labyrinth Anchor', summary: 'text / plane を使って reaction diffusion の labyrinth band と phase shift plate を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'reaction_diffusion', Source: layerIndex === 2 ? 'text' : 'plane', MaterialStyle: layerIndex === 2 ? 'glass' : 'classic', TemporalProfile: layerIndex === 2 ? 'phase_shift' : 'resonate', TemporalStrength: 0.28, TemporalSpeed: 0.82, Count: 9800, RadiusScale: 1.02, BaseSize: 0.8, TextMapText: 'LABYRINTH', TextMapSize: 292, TextMapPadding: 42, TextMapWeight: 700, ReactionOpacity: 0.82, ReactionFeed: 0.027, ReactionKill: 0.053, ReactionScale: 1.06, ReactionWarp: 0.18 }) },
  { id: 'biofilm-colony-anchor', label: 'Biofilm Colony Anchor', summary: 'image / text を使って biofilm skin の colony pooling と accrete surface を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: layerIndex === 2 ? 'biofilm_skin' : 'glyph_weave', Source: layerIndex === 2 ? 'image' : 'text', MaterialStyle: layerIndex === 2 ? 'glass' : 'hologram', TemporalProfile: 'accrete', TemporalStrength: layerIndex === 2 ? 0.28 : 0.22, TemporalSpeed: 0.8, Count: layerIndex === 2 ? 9600 : 9000, RadiusScale: layerIndex === 2 ? 1.06 : 1.0, BaseSize: layerIndex === 2 ? 0.86 : 0.82, ReactionOpacity: 0.84, ReactionFeed: 0.034, ReactionKill: 0.057, ReactionScale: 0.98, ReactionWarp: 0.14, TextMapText: 'COLONY', TextMapSize: 288, TextMapPadding: 40, TextMapWeight: 700, GlyphOutlineEnabled: true, GlyphOutlineWidth: 1.42, GlyphOutlineOpacity: 0.5, FiberOpacity: 0.72, FiberLength: 0.9, FiberDensity: 0.68, FiberCurl: 0.16 }) },
  { id: 'elastic-sheet-tension-anchor', label: 'Elastic Sheet Tension Anchor', summary: 'plane / cylinder を使って elastic sheet の rebound と anneal を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'elastic_sheet', Source: layerIndex === 2 ? 'plane' : 'cylinder', MaterialStyle: 'glass', TemporalProfile: layerIndex === 2 ? 'anneal' : 'inhale', TemporalStrength: 0.24, TemporalSpeed: 0.78, Count: layerIndex === 2 ? 9800 : 9200, RadiusScale: 1.1, BaseSize: 0.92, SheetOpacity: 0.66, SheetFresnel: 0.76, SheetAudioReactive: 0.14, SheetWireframe: false }) },
  { id: 'capillary-sheet-ledger-anchor', label: 'Capillary Sheet Ledger Anchor', summary: 'text / image を使って capillary sheet の soak band と saturate を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'capillary_sheet', Source: layerIndex === 2 ? 'text' : 'image', MaterialStyle: 'halftone', TemporalProfile: layerIndex === 2 ? 'saturate' : 'accrete', TemporalStrength: 0.28, TemporalSpeed: 0.82, Count: 9800, RadiusScale: 1.0, BaseSize: 0.8, TextMapText: 'LEDGER', TextMapSize: 288, TextMapPadding: 42, TextMapWeight: 700, DepositionOpacity: 0.84, DepositionRelief: 0.5, DepositionErosion: 0.18, DepositionBands: 7 }) },
  { id: 'sediment-stack-dune-anchor', label: 'Sediment Stack Dune Anchor', summary: 'plane / sphere を使って sediment stack の strata と delaminate を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'sediment_stack', Source: layerIndex === 2 ? 'plane' : 'sphere', MaterialStyle: 'halftone', TemporalProfile: layerIndex === 2 ? 'delaminate' : 'saturate', TemporalStrength: 0.24, TemporalSpeed: 0.76, Count: 10400, RadiusScale: 1.0, BaseSize: 0.68, CrystalOpacity: 0.76, CrystalScale: 0.82, CrystalDensity: 0.82, CrystalSpread: 0.18 }) },
  { id: 'cellular-front-grid-anchor', label: 'Cellular Front Grid Anchor', summary: 'grid / text を使って cellular front の advancing edge と bifurcate を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'cellular_front', Source: layerIndex === 2 ? 'grid' : 'text', MaterialStyle: 'classic', TemporalProfile: layerIndex === 2 ? 'bifurcate' : 'phase_shift', TemporalStrength: 0.26, TemporalSpeed: 0.88, Count: 9000, RadiusScale: 1.0, BaseSize: 0.82, TextMapText: 'FRONT', TextMapSize: 292, TextMapPadding: 42, TextMapWeight: 700, ReactionOpacity: 0.82, ReactionFeed: 0.03, ReactionKill: 0.046, ReactionScale: 1.04, ReactionWarp: 0.16 }) },
  { id: 'elastic-lattice-span-anchor', label: 'Elastic Lattice Span Anchor', summary: 'grid / cube を使って elastic lattice の span tension と anneal を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: 'elastic_lattice', Source: layerIndex === 2 ? 'grid' : 'cube', MaterialStyle: 'glass', TemporalProfile: layerIndex === 2 ? 'anneal' : 'oscillate', TemporalStrength: 0.22, TemporalSpeed: 0.74, Count: 9400, RadiusScale: 1.0, BaseSize: 0.8, VoxelOpacity: 0.78, VoxelScale: 1.06, VoxelDensity: 0.46, VoxelSnap: 0.46, VoxelWireframe: false }) },
  { id: 'recur-codex-anchor', label: 'Recur Codex Anchor', summary: 'text source を固定し、growth grammar と glyph 系の recur 循環を確認するアンカー束です。', patch: (layerIndex) => layerPatch(layerIndex, { Type: layerIndex === 2 ? 'growth_grammar' : 'glyph_weave', Source: 'text', MaterialStyle: layerIndex === 2 ? 'hologram' : 'classic', TemporalProfile: 'recur', TemporalStrength: 0.28, TemporalSpeed: 0.84, Count: layerIndex === 2 ? 9000 : 9800, RadiusScale: 1.04, BaseSize: 0.8, TextMapText: layerIndex === 2 ? 'RECUR' : 'VARELSER', TextMapSize: 296, TextMapPadding: 40, TextMapWeight: 700, GrowthOpacity: 0.8, GrowthBranches: 8, GrowthLength: 1.0, GrowthSpread: 0.46, GlyphOutlineEnabled: true, GlyphOutlineWidth: 1.46, GlyphOutlineOpacity: 0.54, FiberOpacity: 0.78, FiberLength: 0.94, FiberDensity: 0.74, FiberCurl: 0.18 }) },
];
