import type { HybridExpressionRecipe } from './hybridExpressionTypes';

export const HYBRID_EXPRESSION_BASE_EXTENDED_RECIPES: HybridExpressionRecipe[] = [
{
    id: 'thread-smoke',
    name: 'Thread + Smoke',
    summary: 'Charged or aurora threads suspended inside volumetric mirage or prism smoke.',
    layer2Modes: ['aurora_threads', 'plasma_thread', 'signal_braid'],
    layer3Modes: ['mirage_smoke', 'prism_smoke', 'charge_veil'],
    emphasis: ['thread glow', 'smoke density', 'phase drift'],
  },
{
    id: 'lattice-script',
    name: 'Lattice + Script',
    summary: 'Frosted lattice or residue skin carrying dusty sigil traces and text erosion.',
    layer2Modes: ['frost_lattice', 'residue_skin', 'calcified_skin'],
    layer3Modes: ['sigil_dust', 'drift_glyph_dust', 'ink_bleed'],
    emphasis: ['cell scale', 'script breakup', 'contrast'],
  },
{
    id: 'halo-dust',
    name: 'Halo + Dust',
    summary: 'Halo shells seeded with drifting dust, spores, and sigil particulate.',
    layer2Modes: ['spore_halo', 'aura_shell', 'residue_skin'],
    layer3Modes: ['sigil_dust', 'pollen_storm', 'bloom_spores'],
    emphasis: ['halo radius', 'dust density', 'falloff'],
  },
{
    id: 'thread-prism',
    name: 'Thread + Prism',
    summary: 'Spectral threads or braids suspended inside prismatic smoke or ion rain.',
    layer2Modes: ['prism_threads', 'aurora_threads', 'signal_braid'],
    layer3Modes: ['prism_smoke', 'ion_rain', 'static_smoke'],
    emphasis: ['thread glow', 'spectral spread', 'density'],
  },
{
    id: 'shell-smoke',
    name: 'Shell + Smoke',
    summary: 'Inscribed or resinous shells emerging from mirage, static, or velvet smoke.',
    layer2Modes: ['shell_script', 'resin_shell', 'eclipse_halo'],
    layer3Modes: ['mirage_smoke', 'velvet_ash', 'static_smoke'],
    emphasis: ['shell opacity', 'smoke density', 'fresnel'],
  },
{
    id: 'pollen-script',
    name: 'Pollen + Script',
    summary: 'Pollen lattices and halo shells carrying dusty sigils and dissolving text.',
    layer2Modes: ['pollen_lattice', 'membrane_pollen', 'spore_halo'],
    layer3Modes: ['sigil_dust', 'drift_glyph_dust', 'shell_script'],
    emphasis: ['pollen density', 'script breakup', 'cell scale'],
  },
{
    id: 'ash-lattice',
    name: 'Ash + Lattice',
    summary: 'Ash, soot, or velvet particulate draped through lattices and calcified grids.',
    layer2Modes: ['velvet_ash', 'soot_veil', 'ashfall'],
    layer3Modes: ['frost_lattice', 'pollen_lattice', 'calcified_skin'],
    emphasis: ['ash density', 'lattice visibility', 'falloff'],
  },
{
    id: 'halo-thread',
    name: 'Halo + Thread',
    summary: 'Eclipsed halos energized by glowing braids and prismatic thread networks.',
    layer2Modes: ['eclipse_halo', 'spore_halo', 'aura_shell'],
    layer3Modes: ['prism_threads', 'aurora_threads', 'signal_braid'],
    emphasis: ['halo radius', 'thread density', 'phase'],
  },
{
    id: 'resin-glyph',
    name: 'Resin + Glyph',
    summary: 'Resinous shells and smoke carrying sticky glyph sediment and script residue.',
    layer2Modes: ['resin_shell', 'shell_script', 'velvet_ash'],
    layer3Modes: ['sigil_dust', 'drift_glyph_dust', 'ink_bleed'],
    emphasis: ['resin gloss', 'glyph residue', 'opacity'],
  },
{
    id: 'fracture-lattice',
    name: 'Fracture + Lattice',
    summary: 'Blooming fracture clusters collide with surging or frost-bound lattice scaffolds.',
    layer2Modes: ['fracture_bloom', 'orbit_fracture', 'crystal_aggregate'],
    layer3Modes: ['lattice_surge', 'frost_lattice', 'pollen_lattice'],
    emphasis: ['bloom radius', 'cell snap', 'surge wave'],
  },
{
    id: 'pollen-fracture',
    name: 'Pollen + Fracture',
    summary: 'Pollen-loaded lattices shedding into fracture pollen and storm-driven shard bloom.',
    layer2Modes: ['pollen_lattice', 'membrane_pollen', 'spore_halo'],
    layer3Modes: ['fracture_pollen', 'pollen_storm', 'fracture_bloom'],
    emphasis: ['dust packing', 'storm spread', 'fragment lift'],
  },
{
    id: 'contour-script',
    name: 'Contour + Script',
    summary: 'Contour plates and standing surfaces carrying shell manuscripts, sigils, and inked residue.',
    layer2Modes: ['contour_echo', 'echo_rings', 'standing_interference'],
    layer3Modes: ['shell_script', 'sigil_dust', 'ink_bleed'],
    emphasis: ['contour cadence', 'etch density', 'plate contrast'],
  },
{
    id: 'ink-glyph',
    name: 'Ink + Glyph',
    summary: 'Bleeding ink sheets mixed with drifting glyph dust and sigil-coded palimpsest residue.',
    layer2Modes: ['ink_bleed', 'drift_glyph_dust', 'sigil_dust'],
    layer3Modes: ['shell_script', 'surface_patch', 'contour_echo'],
    emphasis: ['bleed perimeter', 'glyph breakup', 'echo plate'],
  },
{
    id: 'outline-script',
    name: 'Outline + Script',
    summary: 'Contour plates and glyph weaves carrying manuscript shells, sigils, and outlined codex traces.',
    layer2Modes: ['contour_echo', 'glyph_weave', 'echo_rings'],
    layer3Modes: ['shell_script', 'sigil_dust', 'ink_bleed'],
    emphasis: ['outline width', 'gate cadence', 'trace density'],
  },
{
    id: 'codex-network',
    name: 'Codex Network',
    summary: 'Woven line networks and codex outlines stitched to drifting glyph residue and shell inscriptions.',
    layer2Modes: ['glyph_weave', 'mesh_weave', 'spectral_mesh'],
    layer3Modes: ['shell_script', 'drift_glyph_dust', 'sigil_dust'],
    emphasis: ['network tension', 'outline fragmentation', 'residue drift'],
  },
{
    id: 'ribbon-biofilm',
    name: 'Ribbon + Biofilm',
    summary: 'Ribbon veils and smear sheets laid over living biofilm membranes and growth plates.',
    layer2Modes: ['ribbon_veil', 'liquid_smear', 'brush_surface'],
    layer3Modes: ['biofilm_skin', 'growth_field', 'reaction_diffusion'],
    emphasis: ['veil taper', 'colony pooling', 'sheet overlap'],
  },
{
    id: 'branch-smear',
    name: 'Branch + Smear',
    summary: 'Arborized branch structures dragging liquid smears and brush sheets across the field.',
    layer2Modes: ['branch_propagation', 'growth_field', 'fiber_field'],
    layer3Modes: ['liquid_smear', 'brush_surface', 'ink_bleed'],
    emphasis: ['armature depth', 'smear drag', 'tip glow'],
  },
{
    id: 'halo-membrane',
    name: 'Halo + Membrane',
    summary: 'Compressed halo disks paired with porous membrane shells and pollen-sealed surfaces.',
    layer2Modes: ['halo_bloom', 'membrane_pollen', 'spore_halo'],
    layer3Modes: ['contour_echo', 'drift_glyph_dust', 'bloom_spores'],
    emphasis: ['rim bloom', 'pore breakup', 'center dimming'],
  },
{
    id: 'spore-reliquary',
    name: 'Spore + Reliquary',
    summary: 'Spore halos, eclipse rims, and pollen shells layered into reliquary-like containment fields.',
    layer2Modes: ['spore_halo', 'halo_bloom', 'eclipse_halo'],
    layer3Modes: ['membrane_pollen', 'pollen_storm', 'shell_script'],
    emphasis: ['spore grain', 'halo compression', 'shell inscription'],
  },
{
    id: 'aura-reliquary',
    name: 'Aura Reliquary',
    summary: 'Aura shells and eclipse disks wrapped around resin-coated shells and porous reliquary membranes.',
    layer2Modes: ['aura_shell', 'eclipse_halo', 'halo_bloom'],
    layer3Modes: ['resin_shell', 'membrane_pollen', 'shell_script'],
    emphasis: ['aura inflation', 'umbra ring', 'lacquer sheen'],
  },
{
    id: 'amber-umbra',
    name: 'Amber Umbra',
    summary: 'Resin-coated shells paired with eclipse halos and residue skins to form sealed amber umbra bodies.',
    layer2Modes: ['resin_shell', 'aura_shell', 'residue_skin'],
    layer3Modes: ['eclipse_halo', 'spore_halo', 'shell_script'],
    emphasis: ['amber pooling', 'disk compression', 'sealed shell rim'],
  },
{
    id: 'dust-ledger',
    name: 'Dust + Ledger',
    summary: 'Rising dust columns and ash curtains pressed against contour plates, scripts, and dry codex surfaces.',
    layer2Modes: ['dust_plume', 'ashfall', 'velvet_ash'],
    layer3Modes: ['contour_echo', 'shell_script', 'ink_bleed'],
    emphasis: ['column lift', 'fall streaks', 'plate dryness'],
  },
{
    id: 'mirage-static',
    name: 'Mirage + Static',
    summary: 'Heat-mirage smoke colliding with static slabs, charge veils, and holographic thread artifacts.',
    layer2Modes: ['mirage_smoke', 'static_smoke', 'charge_veil'],
    layer3Modes: ['prism_threads', 'spectral_mesh', 'ion_rain'],
    emphasis: ['refraction shimmer', 'scan flicker', 'signal glow'],
  },
{
    id: 'velvet-manuscript',
    name: 'Velvet + Manuscript',
    summary: 'Velvet ash pressed into ink-bleed receiving sheets so the fog acts like a soft soot deposit rather than neutral haze.',
    layer2Modes: ['velvet_ash', 'soot_veil', 'ashfall'],
    layer3Modes: ['ink_bleed', 'contour_echo', 'deposition_field'],
    emphasis: ['velvet core', 'soot staining', 'capillary reception'],
  },
{
    id: 'rune-ledger',
    name: 'Rune + Ledger',
    summary: 'Rune smoke and soot veils paired with drift-glyph residue and ink surfaces to create coded ledgers rather than generic smoke sheets.',
    layer2Modes: ['rune_smoke', 'soot_veil', 'static_smoke'],
    layer3Modes: ['drift_glyph_dust', 'sigil_dust', 'ink_bleed'],
    emphasis: ['rune gating', 'ledger bands', 'glyph retention'],
  },
{
    id: 'static-signal-lace',
    name: 'Static Signal Lace',
    summary: 'Quantized static lace and signal braids paired with spectral meshes and glyph-coded traces.',
    layer2Modes: ['static_lace', 'signal_braid', 'mesh_weave'],
    layer3Modes: ['spectral_mesh', 'glyph_weave', 'shell_script'],
    emphasis: ['lace quantization', 'braid cadence', 'spectral shimmer'],
  },
{
    id: 'cinder-codex-web',
    name: 'Cinder Codex Web',
    summary: 'Charred web meshes and ember lace pressed against codex shells, residue, and drifting script traces.',
    layer2Modes: ['cinder_web', 'ember_lace', 'static_lace'],
    layer3Modes: ['shell_script', 'drift_glyph_dust', 'ink_bleed'],
    emphasis: ['char seams', 'residue hold', 'web looseness'],
  }
];
