import type { HybridTemporalVariant } from './hybridTemporalVariantTypes';

export const HYBRID_TEMPORAL_VARIANTS_CYCLES: HybridTemporalVariant[] = [
  {
    id: 'accumulation-mantle',
    label: 'Accumulation Mantle',
    summary: '堆積と粒状体が層を厚くする時間変化。',
    requiredHybridId: 'physical-band-crossfade',
    layer2Temporal: 'accumulate',
    layer3Temporal: 'accumulate',
  },
  {
    id: 'exfoliate-reliquary',
    label: 'Exfoliate Reliquary',
    summary: '膜や殻が少しずつ剥離して欠片化する時間変化。',
    requiredHybridId: 'physical-band-crossfade',
    layer2Temporal: 'exfoliate',
    layer3Temporal: 'shed',
  },
  {
    id: 'phase-transition-veil',
    label: 'Phase Transition Veil',
    summary: '流体と霧の境界が相転移のように揺れ続ける時間変化。',
    requiredHybridId: 'physical-band-crossfade',
    layer2Temporal: 'phase_shift',
    layer3Temporal: 'melt',
  },
  {
    id: 'breathing-canopy',
    label: 'Breathing Canopy',
    summary: 'cloth membrane と growth grammar が呼吸的に膨張・収縮する時間変化。',
    requiredHybridId: 'growth-rewrite-codex',
    layer2Temporal: 'inhale',
    layer3Temporal: 'growth',
  },
  {
    id: 'rewrite-codex-cycle',
    label: 'Rewrite Codex Cycle',
    summary: 'text 面が再記述を繰り返しながら growth grammar と同期する時間変化。',
    requiredHybridId: 'growth-rewrite-codex',
    layer2Temporal: 'rewrite',
    layer3Temporal: 'rewrite',
  },
  { id: 'saturate-ledger-cycle', label: 'Saturate Ledger Cycle', summary: 'capillary surfaces and receiving sheets saturate until the ledger band fills.', requiredHybridId: 'elastic-capillary-ledger', layer2Temporal: 'anneal', layer3Temporal: 'saturate' },
  { id: 'delaminate-dune-cycle', label: 'Delaminate Dune Cycle', summary: 'sediment stacks compress and then peel into layered slips.', requiredHybridId: 'sediment-front-delta', layer2Temporal: 'delaminate', layer3Temporal: 'bifurcate' },
  { id: 'anneal-span-cycle', label: 'Anneal Span Cycle', summary: 'elastic spans cool, tighten, and return to a calmer scaffold.', requiredHybridId: 'lattice-membrane-span', layer2Temporal: 'anneal', layer3Temporal: 'anneal' },
  { id: 'bifurcate-front-cycle', label: 'Bifurcate Front Cycle', summary: 'cellular fronts fork and widen while sediment layers resist the split.', requiredHybridId: 'sediment-front-delta', layer2Temporal: 'saturate', layer3Temporal: 'bifurcate' },
  { id: 'recur-codex-cycle', label: 'Recur Codex Cycle', summary: 'growth grammar, glyphs, and capillary sheets loop through a recursive rewrite cycle.', requiredHybridId: 'recur-growth-codex', layer2Temporal: 'recur', layer3Temporal: 'recur' },
  { id: 'memory-percolation-cycle', label: 'Memory Percolation Cycle', summary: 'viscoelastic membrane が戻りながら percolation channels がさらに染み込む循環です。', requiredHybridId: 'memory-percolation-ledger', layer2Temporal: 'rebound', layer3Temporal: 'percolate' },
  { id: 'talus-corrosion-cycle', label: 'Talus Corrosion Cycle', summary: 'talus slope が崩れ、corrosion front が縁から裂ける循環です。', requiredHybridId: 'talus-corrosion-front', layer2Temporal: 'slump', layer3Temporal: 'fissure' },
  { id: 'creep-memory-cycle', label: 'Creep Memory Cycle', summary: 'span memory と slow creep が交互に押し引きする循環です。', requiredHybridId: 'creep-memory-span', layer2Temporal: 'rebound', layer3Temporal: 'slump' },
  { id: 'percolation-corrode-cycle', label: 'Percolation Corrode Cycle', summary: '受け皿面が浸透しつつ、別層では腐食が文字縁から進む循環です。', requiredHybridId: 'percolation-corrode-codex', layer2Temporal: 'percolate', layer3Temporal: 'fissure' },
  { id: 'talus-ossify-cycle', label: 'Talus Ossify Cycle', summary: '崩れた talus が硬化し、その横で creep lattice が遅れて戻る循環です。', requiredHybridId: 'talus-ossify-span', layer2Temporal: 'ossify', layer3Temporal: 'rebound' },
  { id: 'advection-pressure-cycle', label: 'Advection Pressure Cycle', summary: 'flow lanes break intermittently while pressure basins recover with lag.', requiredHybridId: 'advection-pressure-ledger', layer2Temporal: 'intermittent', layer3Temporal: 'hysteresis' },
  { id: 'avalanche-jam-cycle', label: 'Avalanche Jam Cycle', summary: 'avalanche runout fatigues while packed debris slowly recovers its locked body.', requiredHybridId: 'avalanche-jam-stack', layer2Temporal: 'fatigue', layer3Temporal: 'recover' },
  { id: 'melt-condense-latency', label: 'Melt Condense Latency', summary: 'melting fronts retreat while condensation emerges after a short latent delay.', requiredHybridId: 'melt-condense-cycle', layer2Temporal: 'collapse', layer3Temporal: 'emerge' },
  { id: 'freeze-sublimate-inversion', label: 'Freeze Sublimate Inversion', summary: 'frozen shells lock while surrounding vapor inverts into a sublimating hollow cloud.', requiredHybridId: 'freeze-sublimate-shell', layer2Temporal: 'invert', layer3Temporal: 'invert' },
]
