import type { HybridTemporalVariant } from './hybridTemporalVariantTypes';

export const HYBRID_TEMPORAL_VARIANTS_BASE_SPECIALIST = [
{
    id: 'thread-prism-resonate',
    label: 'Prismatic Thread Resonance',
    summary: 'Prismatic smoke and threads pulse in a tight resonant braid.',
    requiredHybridId: 'thread-prism',
    layer2Temporal: 'resonate',
    layer3Temporal: 'oscillate',
  },
{
    id: 'shell-smoke-condense',
    label: 'Shell Smoke Condensation',
    summary: 'Smoke condenses into a shell that thickens and briefly stabilizes.',
    requiredHybridId: 'shell-smoke',
    layer2Temporal: 'condense',
    layer3Temporal: 'evaporate',
  },
{
    id: 'pollen-script-unravel',
    label: 'Pollen Script Unraveling',
    summary: 'Script dust unravels while pollen lattices continue to pulse outward.',
    requiredHybridId: 'pollen-script',
    layer2Temporal: 'shed',
    layer3Temporal: 'unravel',
  },
{
    id: 'ash-lattice-ignite',
    label: 'Ash Lattice Ignition',
    summary: 'Ash catches and brightens while the lattice briefly surges and locks.',
    requiredHybridId: 'ash-lattice',
    layer2Temporal: 'ignite',
    layer3Temporal: 'condense',
  },
{
    id: 'halo-thread-bloom',
    label: 'Halo Thread Bloom',
    summary: 'Halo shells bloom as prismatic threads oscillate across their surface.',
    requiredHybridId: 'halo-thread',
    layer2Temporal: 'growth',
    layer3Temporal: 'resonate',
  },
{
    id: 'resin-glyph-accretion',
    label: 'Resin Glyph Accretion',
    summary: 'Resin shells accrete while glyph residue repeatedly rebuilds itself.',
    requiredHybridId: 'resin-glyph',
    layer2Temporal: 'accrete',
    layer3Temporal: 'condense',
  },
{
    id: 'fracture-lattice-surge',
    label: 'Fracture Lattice Surge',
    summary: 'Lattice corridors charge and surge while fracture blooms pulse outward in bursts.',
    requiredHybridId: 'fracture-lattice',
    layer2Temporal: 'rupture',
    layer3Temporal: 'oscillate',
  },
{
    id: 'pollen-fracture-shed',
    label: 'Pollen Fracture Shedding',
    summary: 'Pollen lattices shed outward while fracture pollen and storm shards drift into bloom.',
    requiredHybridId: 'pollen-fracture',
    layer2Temporal: 'shed',
    layer3Temporal: 'growth',
  },
{
    id: 'contour-script-resonance',
    label: 'Contour Script Resonance',
    summary: 'Contour plates resonate while shell script and sigil residue repeatedly re-inscribe themselves.',
    requiredHybridId: 'contour-script',
    layer2Temporal: 'resonate',
    layer3Temporal: 'unravel',
  },
{
    id: 'ink-glyph-accretion',
    label: 'Ink Glyph Accretion',
    summary: 'Ink spreads and pools while glyph residue accretes into a palimpsest plate.',
    requiredHybridId: 'ink-glyph',
    layer2Temporal: 'accrete',
    layer3Temporal: 'condense',
  },
{
    id: 'outline-script-trace',
    label: 'Outline Script Trace',
    summary: 'Outlined codex plates resonate while shell scripts slowly unravel into dust.',
    requiredHybridId: 'outline-script',
    layer2Temporal: 'resonate',
    layer3Temporal: 'unravel',
  },
{
    id: 'codex-network-fade',
    label: 'Codex Network Fade',
    summary: 'Glyph networks hold tension while codex residue fades and sheds into broken traces.',
    requiredHybridId: 'codex-network',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'shed',
  },
{
    id: 'ribbon-biofilm-creep',
    label: 'Biofilm Veil Creep',
    summary: 'Ribbon veils drift while biofilm colonies slowly accrete and pool beneath them.',
    requiredHybridId: 'ribbon-biofilm',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'accrete',
  },
{
    id: 'branch-smear-propagate',
    label: 'Smear Arbor Propagate',
    summary: 'Branch structures continue propagating while the overlaid smear stretches and softens.',
    requiredHybridId: 'branch-smear',
    layer2Temporal: 'growth',
    layer3Temporal: 'melt',
  },
{
    id: 'halo-membrane-breath',
    label: 'Halo Membrane Breathing',
    summary: 'Compressed halo rims pulse while porous membranes slowly accrete and seal again.',
    requiredHybridId: 'halo-membrane',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'accrete',
  },
{
    id: 'spore-reliquary-shed',
    label: 'Spore Reliquary Shedding',
    summary: 'Spore halos shed particulate rings while the enclosing pollen shell loosens and re-inscribes.',
    requiredHybridId: 'spore-reliquary',
    layer2Temporal: 'shed',
    layer3Temporal: 'growth',
  },
{
    id: 'aura-reliquary-breathe',
    label: 'Aura Reliquary Breathing',
    summary: 'Aura shells slowly breathe while the resin-coated reliquary core stays sealed and luminous.',
    requiredHybridId: 'aura-reliquary',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'steady',
  },
{
    id: 'amber-umbra-shed',
    label: 'Amber Umbra Shedding',
    summary: 'Amber shells hold their lacquer while the eclipsed halo sheds a dark particulate ring.',
    requiredHybridId: 'amber-umbra',
    layer2Temporal: 'steady',
    layer3Temporal: 'shed',
  },
{
    id: 'dust-ledger-settle',
    label: 'Dust Ledger Settling',
    summary: 'Dust columns keep rising while the receiving ledger surface slowly accretes and darkens.',
    requiredHybridId: 'dust-ledger',
    layer2Temporal: 'growth',
    layer3Temporal: 'accrete',
  },
{
    id: 'mirage-static-flicker',
    label: 'Mirage Static Flicker',
    summary: 'Mirage smoke evaporates through a static slab that keeps oscillating with electronic flicker.',
    requiredHybridId: 'mirage-static',
    layer2Temporal: 'evaporate',
    layer3Temporal: 'oscillate',
  },
{
    id: 'velvet-manuscript-sink',
    label: 'Velvet Manuscript Sink',
    summary: 'Velvet ash keeps shedding while the receiving manuscript sheet continues to accrete and darken.',
    requiredHybridId: 'velvet-manuscript',
    layer2Temporal: 'shed',
    layer3Temporal: 'accrete',
  },
{
    id: 'rune-ledger-oscillation',
    label: 'Rune Ledger Oscillation',
    summary: 'Rune smoke oscillates while the ledger surface keeps holding its inscribed residue in place.',
    requiredHybridId: 'rune-ledger',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'steady',
  },
{
    id: 'static-signal-oscillation',
    label: 'Static Signal Oscillation',
    summary: 'Static lace keeps oscillating while the spectral braid layer continues to resonate and shimmer.',
    requiredHybridId: 'static-signal-lace',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'resonate',
  },
{
    id: 'cinder-codex-shed',
    label: 'Cinder Codex Shedding',
    summary: 'Cinder webs keep shedding embers while the codex surface holds its residue and inscriptions.',
    requiredHybridId: 'cinder-codex-web',
    layer2Temporal: 'shed',
    layer3Temporal: 'steady',
  }
];
