import { HYBRID_EXPRESSION_BASE_CORE_RECIPES } from './hybridExpressionBaseCore';
import { HYBRID_EXPRESSION_BASE_EXTENDED_RECIPES } from './hybridExpressionBaseExtended';
import { HYBRID_EXPRESSION_BASE_SOURCE_ANCHOR_RECIPES } from './hybridExpressionBaseSourceAnchors';

export const HYBRID_EXPRESSION_BASE_RECIPES = [
  ...HYBRID_EXPRESSION_BASE_CORE_RECIPES,
  ...HYBRID_EXPRESSION_BASE_EXTENDED_RECIPES,
  ...HYBRID_EXPRESSION_BASE_SOURCE_ANCHOR_RECIPES,
];
