import type { HybridExpressionRecipe } from './hybridExpressionTypes';

export const HYBRID_EXPRESSION_BASE_CORE_RECIPES: HybridExpressionRecipe[] = [
{
    id: 'membrane-crystal',
    name: 'Membrane + Crystal',
    summary: 'A skin or shell carrying mineral growth and reflective aggregation.',
    layer2Modes: ['sheet', 'surface_shell', 'surface_patch'],
    layer3Modes: ['crystal_aggregate', 'crystal_deposition', 'voxel_lattice'],
    emphasis: ['shell opacity', 'crystal scale', 'spread'],
  },
{
    id: 'fog-glyph',
    name: 'Fog + Glyph',
    summary: 'Volumetric haze carrying text silhouettes or inscription traces.',
    layer2Modes: ['volume_fog', 'dust_plume'],
    layer3Modes: ['brush_surface', 'erosion_trail', 'reaction_diffusion', 'sheet'],
    emphasis: ['fog depth', 'glyph outline', 'glow'],
  },
{
    id: 'deposition-growth',
    name: 'Deposition + Growth',
    summary: 'Sediment, relief, or accretion combined with branching propagation.',
    layer2Modes: ['deposition_field', 'crystal_deposition'],
    layer3Modes: ['growth_field', 'fiber_field', 'erosion_trail'],
    emphasis: ['relief', 'branch length', 'density'],
  },
{
    id: 'shell-pulse',
    name: 'Shell + Pulse',
    summary: 'An enclosing body modulated by breathing or beacon-like temporal motion.',
    layer2Modes: ['surface_shell', 'aura_shell', 'halo_bloom'],
    layer3Modes: ['pulse_breathing', 'beacon', 'sheet'],
    emphasis: ['fresnel', 'pulse depth', 'phase'],
  },
{
    id: 'fiber-drift',
    name: 'Fiber + Drift',
    summary: 'Strands, ribbons, or line webs drifting against a secondary current.',
    layer2Modes: ['fiber_field', 'braid_stream', 'ribbon_veil', 'mesh_weave'],
    layer3Modes: ['crosscurrent', 'helio', 'interference_wave', 'filament'],
    emphasis: ['strand length', 'trail', 'phase offset'],
  },
{
    id: 'plasma-skin',
    name: 'Plasma + Skin',
    summary: 'Charged thread fields running across a skin-like lattice enclosure.',
    layer2Modes: ['plasma_thread', 'mesh_weave'],
    layer3Modes: ['skin_lattice', 'surface_shell', 'aura_shell'],
    emphasis: ['thread glow', 'cell scale', 'surface tension'],
  },
{
    id: 'ash-echo',
    name: 'Ash + Echo',
    summary: 'Falling particulate haze framed by reverberating contour rings.',
    layer2Modes: ['ashfall', 'dust_plume'],
    layer3Modes: ['echo_rings', 'contour_echo', 'reaction_diffusion'],
    emphasis: ['fall speed', 'ring spacing', 'opacity decay'],
  },
{
    id: 'mist-inscription',
    name: 'Mist Ribbon + Inscription',
    summary: 'Mist-laden ribbons drifting across text, glyph, or patch surfaces.',
    layer2Modes: ['mist_ribbon', 'ribbon_veil'],
    layer3Modes: ['ink_bleed', 'brush_surface', 'surface_patch'],
    emphasis: ['ribbon width', 'drift', 'bleed softness'],
  },
{
    id: 'liquid-rupture',
    name: 'Liquid + Rupture',
    summary: 'Smear-like surfaces meeting fracture, erosion, or collapse motion.',
    layer2Modes: ['liquid_smear', 'brush_surface', 'ink_bleed'],
    layer3Modes: ['collapse_fracture', 'erosion_trail', 'shard_debris'],
    emphasis: ['smear opacity', 'fracture burst', 'erosion drift'],
  },
{
    id: 'plasma-fog',
    name: 'Plasma + Fog',
    summary: 'Electrified threads or veils carrying through spectral fog volumes.',
    layer2Modes: ['plasma_thread', 'charge_veil'],
    layer3Modes: ['volume_fog', 'prism_smoke', 'soot_veil'],
    emphasis: ['charge glow', 'fog depth', 'spectral drift'],
  },
{
    id: 'ash-glyph',
    name: 'Ash + Glyph',
    summary: 'Charred dust and ash tracing or erasing inscription-like surfaces.',
    layer2Modes: ['ashfall', 'drift_glyph_dust', 'soot_veil'],
    layer3Modes: ['ink_bleed', 'drift_glyph_dust', 'surface_patch'],
    emphasis: ['dust mask', 'glyph breakup', 'falloff'],
  },
{
    id: 'lattice-rupture',
    name: 'Lattice + Rupture',
    summary: 'Membrane or voxel structures pushed toward fracture and collapse.',
    layer2Modes: ['skin_lattice', 'membrane_pollen', 'voxel_lattice'],
    layer3Modes: ['collapse_fracture', 'orbit_fracture', 'shard_debris'],
    emphasis: ['cell scale', 'rupture force', 'fragment spread'],
  },
{
    id: 'veil-lattice',
    name: 'Veil + Lattice',
    summary: 'Charged or drifting veils crossing skeletal mesh or shell lattice structures.',
    layer2Modes: ['charge_veil', 'ribbon_veil', 'mist_ribbon'],
    layer3Modes: ['spectral_mesh', 'calcified_skin', 'skin_lattice'],
    emphasis: ['veil drift', 'lattice density', 'contrast'],
  },
{
    id: 'smoke-script',
    name: 'Smoke + Script',
    summary: 'Glyph-like smoke and dust carrying inscription traces through the volume.',
    layer2Modes: ['rune_smoke', 'prism_smoke', 'soot_veil'],
    layer3Modes: ['drift_glyph_dust', 'ink_bleed', 'surface_patch'],
    emphasis: ['glyph breakup', 'smoke density', 'falloff'],
  },
{
    id: 'pollen-shell',
    name: 'Pollen + Shell',
    summary: 'Halo shells and membranes carrying spores, pollen, and calcified blooms.',
    layer2Modes: ['membrane_pollen', 'spore_halo'],
    layer3Modes: ['calcified_skin', 'aura_shell', 'surface_shell'],
    emphasis: ['halo radius', 'shell opacity', 'spore spread'],
  },
{
    id: 'veil-script',
    name: 'Veil + Script',
    summary: 'Charged, smoky, or ribbon veils carrying inscription-like traces.',
    layer2Modes: ['charge_veil', 'ribbon_veil', 'rune_smoke', 'prism_smoke'],
    layer3Modes: ['drift_glyph_dust', 'ink_bleed', 'surface_patch'],
    emphasis: ['veil drift', 'script breakup', 'edge glow'],
  },
{
    id: 'halo-spore',
    name: 'Halo + Spore',
    summary: 'Halo shells seeded with spores, pollen, and suspended bloom debris.',
    layer2Modes: ['spore_halo', 'halo_bloom', 'aura_shell'],
    layer3Modes: ['bloom_spores', 'pollen_storm', 'membrane_pollen'],
    emphasis: ['halo radius', 'spore density', 'bloom spread'],
  },
{
    id: 'smoke-lattice',
    name: 'Smoke + Lattice',
    summary: 'Prismatic or runic smoke moving through a visible lattice or mesh scaffold.',
    layer2Modes: ['prism_smoke', 'rune_smoke', 'soot_veil'],
    layer3Modes: ['spectral_mesh', 'calcified_skin', 'skin_lattice', 'voxel_lattice'],
    emphasis: ['smoke density', 'lattice visibility', 'shedding'],
  }
];
