import type { HybridExpressionRecipe } from './hybridExpressionTypes';

export const HYBRID_EXPRESSION_REVIEW_RECIPES: HybridExpressionRecipe[] = [
  {
    id: 'review-text-inscription-split',
    name: 'Review Text Inscription Split',
    summary: 'Text source を固定し、shell script と ink bleed / rune smoke の差を確認する review 用レシピ。',
    layer2Modes: ['shell_script', 'rune_smoke'],
    layer3Modes: ['ink_bleed', 'drift_glyph_dust', 'glyph_weave'],
    emphasis: ['etch gate', 'bleed reception', 'rune retention'],
  },
  {
    id: 'review-grid-architectonic-split',
    name: 'Review Grid Architectonic Split',
    summary: 'Grid source を固定し、calcified shell と static fog / lace の差を確認する review 用レシピ。',
    layer2Modes: ['calcified_skin', 'static_smoke'],
    layer3Modes: ['static_lace', 'stipple_field', 'mesh_weave'],
    emphasis: ['quantize hold', 'static slab', 'grid tension'],
  },
  {
    id: 'review-ring-orbit-split',
    name: 'Review Ring Orbit Split',
    summary: 'Ring source を固定し、eclipse halo と spectral mesh / dust plume の差を確認する review 用レシピ。',
    layer2Modes: ['eclipse_halo', 'dust_plume'],
    layer3Modes: ['spectral_mesh', 'signal_braid', 'mirage_smoke'],
    emphasis: ['disk compression', 'orbit shimmer', 'plume orbit'],
  },
  {
    id: 'review-plane-ledger-split',
    name: 'Review Plane Ledger Split',
    summary: 'Plane source を固定し、soot veil と ink bleed / velvet ash の差を確認する review 用レシピ。',
    layer2Modes: ['soot_veil', 'velvet_ash'],
    layer3Modes: ['ink_bleed', 'deposition_field', 'contour_echo'],
    emphasis: ['soot ledger', 'velvet body', 'ink reception'],
  },

  {
    id: 'review-text-local-residual-split',
    name: 'Review Text Local Residual Split',
    summary: 'Text source を固定し、shell script と drift glyph dust / glyph weave の残留衝突だけを局所確認する review 用レシピ。',
    layer2Modes: ['shell_script'],
    layer3Modes: ['drift_glyph_dust', 'glyph_weave'],
    emphasis: ['etch gate', 'dust dropout', 'text adherence'],
  },
  {
    id: 'review-grid-local-residual-split',
    name: 'Review Grid Local Residual Split',
    summary: 'Grid source を固定し、calcified skin と static lace / stipple field の残留衝突だけを局所確認する review 用レシピ。',
    layer2Modes: ['calcified_skin'],
    layer3Modes: ['static_lace', 'stipple_field'],
    emphasis: ['calcify bands', 'grid tension', 'quantized hold'],
  },
  {
    id: 'review-text-glyph-density-split',
    name: 'Review Text Glyph Density Split',
    summary: 'Text source を固定し、glyph weave / contour echo / shell script の 2D 系差を見本密度込みで確認する review 用レシピ。',
    layer2Modes: ['glyph_weave', 'shell_script'],
    layer3Modes: ['contour_echo', 'drift_glyph_dust'],
    emphasis: ['glyph gating', 'contour plate', 'text adherence'],
  },
  {
    id: 'review-grid-stipple-density-split',
    name: 'Review Grid Stipple Density Split',
    summary: 'Grid source を固定し、stipple field / static lace / calcified skin の 2D 系差を見本密度込みで確認する review 用レシピ。',
    layer2Modes: ['stipple_field', 'calcified_skin'],
    layer3Modes: ['static_lace', 'deposition_field'],
    emphasis: ['stipple relief', 'grid quantize', 'calcify band'],
  },
  {
    id: 'review-text-plate-weave-split',
    name: 'Review Text Plate Weave Split',
    summary: 'Text source を固定し、contour echo / glyph weave / shell script の inscription 差を確認する review 用レシピ。',
    layer2Modes: ['contour_echo', 'shell_script'],
    layer3Modes: ['glyph_weave', 'drift_glyph_dust'],
    emphasis: ['plate flattening', 'outline gate', 'inscription hold'],
  },
  {
    id: 'review-grid-relief-line-split',
    name: 'Review Grid Relief Line Split',
    summary: 'Grid source を固定し、tremor lattice / static lace / stipple field の relief と line 差を確認する review 用レシピ。',
    layer2Modes: ['tremor_lattice', 'stipple_field'],
    layer3Modes: ['static_lace', 'mesh_weave'],
    emphasis: ['grid shear', 'line cadence', 'relief hold'],
  },
  {
    id: 'review-grid-relief-shell-split',
    name: 'Review Grid Relief Shell Split',
    summary: 'Grid source を固定し、contour echo / calcified skin の plate と shell 差を確認する review 用レシピ。',
    layer2Modes: ['contour_echo', 'calcified_skin'],
    layer3Modes: ['static_smoke', 'stipple_field'],
    emphasis: ['plate contour', 'shell rigidity', 'grid quantize'],
  },
];
