import type { HybridTemporalVariant } from './hybridTemporalVariantTypes';

export const HYBRID_TEMPORAL_VARIANTS_REVIEW: HybridTemporalVariant[] = [
  {
    id: 'review-text-inscription-split-trace',
    label: 'Review Text Inscription Trace',
    summary: 'Text-adhered shell and deposition continue tracing while rune smoke oscillates behind them.',
    requiredHybridId: 'review-text-inscription-split',
    layer2Temporal: 'unravel',
    layer3Temporal: 'accrete',
  },
  {
    id: 'review-grid-architectonic-split-hold',
    label: 'Review Grid Architectonic Hold',
    summary: 'Grid-bound shell and static lace hold their structure while fog keeps a restrained oscillation.',
    requiredHybridId: 'review-grid-architectonic-split',
    layer2Temporal: 'steady',
    layer3Temporal: 'oscillate',
  },
  {
    id: 'review-ring-orbit-split-breathe',
    label: 'Review Ring Orbit Breathe',
    summary: 'Ring-bound halo and spectral lines breathe around a compressed orbit core.',
    requiredHybridId: 'review-ring-orbit-split',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'resonate',
  },
  {
    id: 'review-plane-ledger-split-settle',
    label: 'Review Plane Ledger Settle',
    summary: 'Plane-bound soot and ink continue settling into a darker, flatter receiving surface.',
    requiredHybridId: 'review-plane-ledger-split',
    layer2Temporal: 'shed',
    layer3Temporal: 'accrete',
  },

  {
    id: 'review-text-local-residual-split-trace',
    label: 'Review Text Local Residual Trace',
    summary: 'Text-adhered shell and drifting glyph dust keep separating while their inscription anchor remains fixed.',
    requiredHybridId: 'review-text-local-residual-split',
    layer2Temporal: 'unravel',
    layer3Temporal: 'accrete',
  },
  {
    id: 'review-grid-local-residual-split-hold',
    label: 'Review Grid Local Residual Hold',
    summary: 'Grid-bound calcified shell and static lace keep their local tension without collapsing into one pattern.',
    requiredHybridId: 'review-grid-local-residual-split',
    layer2Temporal: 'steady',
    layer3Temporal: 'oscillate',
  },
  {
    id: 'review-text-glyph-density-trace',
    label: 'Review Text Glyph Density Trace',
    summary: 'Text-bound glyph weave and contour plates keep tracing different inscriptions rather than collapsing into one script field.',
    requiredHybridId: 'review-text-glyph-density-split',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'resonate',
  },
  {
    id: 'review-grid-stipple-density-hold',
    label: 'Review Grid Stipple Density Hold',
    summary: 'Grid-bound stipple and static lace hold their relief and line tension without flattening into one architectonic texture.',
    requiredHybridId: 'review-grid-stipple-density-split',
    layer2Temporal: 'accrete',
    layer3Temporal: 'oscillate',
  },
  {
    id: 'review-text-plate-weave-trace',
    label: 'Plate Weave Trace',
    summary: 'Text inscription surfaces trace between plate echoes and woven glyphs.',
    requiredHybridId: 'review-text-plate-weave-split',
    layer2Temporal: 'resonate',
    layer3Temporal: 'oscillate',
  },
  {
    id: 'review-grid-relief-line-hold',
    label: 'Relief Line Hold',
    summary: 'Grid-bound relief and lace hold their separation under steady oscillation.',
    requiredHybridId: 'review-grid-relief-line-split',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'resonate',
  },
  {
    id: 'review-grid-relief-shell-hold',
    label: 'Relief Shell Hold',
    summary: 'Grid plates and calcified shells hold apart while static residue stays constrained.',
    requiredHybridId: 'review-grid-relief-shell-split',
    layer2Temporal: 'resonate',
    layer3Temporal: 'steady',
  },
]
