import type { HybridTemporalVariant } from './hybridTemporalVariantTypes';

export const HYBRID_TEMPORAL_VARIANTS_BASE_CORE = [
{
    id: 'membrane-crystal-crystallize',
    label: 'Crystal Bloom',
    summary: 'Shell surfaces slowly crystallize while aggregate structures lock in.',
    requiredHybridId: 'membrane-crystal',
    layer2Temporal: 'growth',
    layer3Temporal: 'crystallize',
  },
{
    id: 'fog-glyph-decay',
    label: 'Inscription Fade',
    summary: 'Fog drifts outward as inscription traces decay and dissolve.',
    requiredHybridId: 'fog-glyph',
    layer2Temporal: 'decay',
    layer3Temporal: 'melt',
  },
{
    id: 'deposition-growth-accretion',
    label: 'Accretion Lift',
    summary: 'Sediment thickens while branching structures continue to emerge.',
    requiredHybridId: 'deposition-growth',
    layer2Temporal: 'growth',
    layer3Temporal: 'growth',
  },
{
    id: 'shell-pulse-beacon',
    label: 'Breathing Reliquary',
    summary: 'An aura shell breathes against a pulse-driven beacon rhythm.',
    requiredHybridId: 'shell-pulse',
    layer2Temporal: 'melt',
    layer3Temporal: 'rupture',
  },
{
    id: 'plasma-skin-charge',
    label: 'Charged Carapace',
    summary: 'Thread networks pulse while the lattice skin gradually stabilizes.',
    requiredHybridId: 'plasma-skin',
    layer2Temporal: 'rupture',
    layer3Temporal: 'growth',
  },
{
    id: 'ash-echo-falloff',
    label: 'Falloff Reverberation',
    summary: 'Ashfall decays while echo rings continue to pulse outward.',
    requiredHybridId: 'ash-echo',
    layer2Temporal: 'decay',
    layer3Temporal: 'oscillate',
  },
{
    id: 'mist-inscription-drift',
    label: 'Inscribed Drift Veil',
    summary: 'Mist ribbons melt and carry inscription-like patches through drift.',
    requiredHybridId: 'mist-inscription',
    layer2Temporal: 'melt',
    layer3Temporal: 'decay',
  },
{
    id: 'liquid-rupture-burst',
    label: 'Fracture Spill',
    summary: 'Smear surfaces soften while rupture events spike and shed debris.',
    requiredHybridId: 'liquid-rupture',
    layer2Temporal: 'melt',
    layer3Temporal: 'rupture',
  },
{
    id: 'plasma-fog-surge',
    label: 'Ion Veil Surge',
    summary: 'Charged veils pulse while fog volumes bloom and recede.',
    requiredHybridId: 'plasma-fog',
    layer2Temporal: 'rupture',
    layer3Temporal: 'melt',
  },
{
    id: 'ash-glyph-fade',
    label: 'Cinder Script Fade',
    summary: 'Ash decays while glyph dust slowly erases itself into the field.',
    requiredHybridId: 'ash-glyph',
    layer2Temporal: 'decay',
    layer3Temporal: 'decay',
  },
{
    id: 'lattice-rupture-shed',
    label: 'Carapace Shedding',
    summary: 'Lattice membranes grow brittle and shed fragments outward.',
    requiredHybridId: 'lattice-rupture',
    layer2Temporal: 'growth',
    layer3Temporal: 'rupture',
  },
{
    id: 'veil-lattice-oscillation',
    label: 'Lattice Veil Oscillation',
    summary: 'Charged veils oscillate across a visible structural lattice.',
    requiredHybridId: 'veil-lattice',
    layer2Temporal: 'melt',
    layer3Temporal: 'growth',
  },
{
    id: 'smoke-script-erasure',
    label: 'Script Smoke Erasure',
    summary: 'Inscribed smoke writes and then erases itself into dust.',
    requiredHybridId: 'smoke-script',
    layer2Temporal: 'decay',
    layer3Temporal: 'decay',
  },
{
    id: 'pollen-shell-bloom',
    label: 'Pollen Shell Bloom',
    summary: 'Halo spores bloom outward while the shell stabilizes beneath them.',
    requiredHybridId: 'pollen-shell',
    layer2Temporal: 'growth',
    layer3Temporal: 'crystallize',
  },
{
    id: 'veil-script-evaporation',
    label: 'Script Veil Evaporation',
    summary: 'Veils oscillate and then evaporate while script traces dissolve into dust.',
    requiredHybridId: 'veil-script',
    layer2Temporal: 'evaporate',
    layer3Temporal: 'decay',
  },
{
    id: 'halo-spore-accretion',
    label: 'Spore Halo Accretion',
    summary: 'Halo shells accrete outward as spore structures crystallize and settle.',
    requiredHybridId: 'halo-spore',
    layer2Temporal: 'accrete',
    layer3Temporal: 'growth',
  },
{
    id: 'smoke-lattice-shedding',
    label: 'Lattice Smoke Shedding',
    summary: 'Smoke scaffolds oscillate through a lattice that gradually sheds material.',
    requiredHybridId: 'smoke-lattice',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'shed',
  },
{
    id: 'thread-smoke-drift',
    label: 'Aurora Smoke Drift',
    summary: 'Aurora threads breathing through mirage smoke and charged haze.',
    requiredHybridId: 'thread-smoke',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'evaporate',
  },
{
    id: 'lattice-script-shear',
    label: 'Lattice Script Shear',
    summary: 'Crusted lattices shedding and rebuilding script-like dust inscriptions.',
    requiredHybridId: 'lattice-script',
    layer2Temporal: 'shed',
    layer3Temporal: 'accrete',
  },
{
    id: 'halo-dust-reverie',
    label: 'Halo Dust Reverie',
    summary: 'Halo shells blooming with dust and pollen that later drift away.',
    requiredHybridId: 'halo-dust',
    layer2Temporal: 'growth',
    layer3Temporal: 'evaporate',
  }
];
