import type { HybridTemporalVariant } from './hybridTemporalVariantTypes';

export const HYBRID_TEMPORAL_VARIANTS_BASE_EXPANSION = [
{
    id: 'thread-smoke-reverie',
    label: 'Thread Smoke Reverie',
    summary: 'Aurora or plasma threads oscillate through smoke that slowly evaporates.',
    requiredHybridId: 'thread-smoke',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'evaporate',
  },
{
    id: 'lattice-script-accretion',
    label: 'Script Accretion Skin',
    summary: 'Lattice surfaces accrete while dust scripts repeatedly rebuild themselves.',
    requiredHybridId: 'lattice-script',
    layer2Temporal: 'accrete',
    layer3Temporal: 'accrete',
  },
{
    id: 'halo-dust-shed',
    label: 'Halo Dust Shedding',
    summary: 'Halo shells bloom and then shed dust into a drifting outer ring.',
    requiredHybridId: 'halo-dust',
    layer2Temporal: 'shed',
    layer3Temporal: 'evaporate',
  },
{
    id: 'thread-smoke-surge',
    label: 'Ion Thread Surge',
    summary: 'Charged threads pulse hard against smoke volumes that thicken and recede.',
    requiredHybridId: 'thread-smoke',
    layer2Temporal: 'rupture',
    layer3Temporal: 'oscillate',
  },
{
    id: 'lattice-script-frost',
    label: 'Frost Script Crystallize',
    summary: 'Frost lattices crystallize while script dust settles into brittle traces.',
    requiredHybridId: 'lattice-script',
    layer2Temporal: 'crystallize',
    layer3Temporal: 'shed',
  },
{
    id: 'halo-dust-bloom',
    label: 'Halo Dust Bloom',
    summary: 'Shell halos accrete outward as dust blooms and slowly fades.',
    requiredHybridId: 'halo-dust',
    layer2Temporal: 'growth',
    layer3Temporal: 'decay',
  },
{
    id: 'plasma-fog-oscillate',
    label: 'Prismatic Storm Breathing',
    summary: 'Charged veils oscillate while prism smoke thickens and thins in layered breaths.',
    requiredHybridId: 'plasma-fog',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'evaporate',
  },
{
    id: 'ash-glyph-shed',
    label: 'Ash Script Shedding',
    summary: 'Ash haze sheds and falls away while scripted dust breaks into fragmented traces.',
    requiredHybridId: 'ash-glyph',
    layer2Temporal: 'shed',
    layer3Temporal: 'decay',
  },
{
    id: 'veil-lattice-accrete',
    label: 'Veil Lattice Accretion',
    summary: 'Veils keep drifting while the lattice underneath slowly accretes and hardens.',
    requiredHybridId: 'veil-lattice',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'accrete',
  },
{
    id: 'smoke-script-evaporate',
    label: 'Runic Smoke Evaporation',
    summary: 'Runic smoke evaporates upward while inscriptions blur and erase into residue.',
    requiredHybridId: 'smoke-script',
    layer2Temporal: 'evaporate',
    layer3Temporal: 'decay',
  },
{
    id: 'pollen-shell-shed',
    label: 'Pollen Shell Shedding',
    summary: 'Halo shells shed outward while pollen blooms detach and drift into the perimeter.',
    requiredHybridId: 'pollen-shell',
    layer2Temporal: 'shed',
    layer3Temporal: 'growth',
  },
{
    id: 'thread-smoke-accrete',
    label: 'Thread Smoke Accretion',
    summary: 'Aurora threads continue to braid while smoke layers accrete into a denser envelope.',
    requiredHybridId: 'thread-smoke',
    layer2Temporal: 'oscillate',
    layer3Temporal: 'accrete',
  },
{
    id: 'halo-dust-evaporate',
    label: 'Halo Dust Evaporation',
    summary: 'Halo shells remain while dust blooms thin and evaporate into a dim outer field.',
    requiredHybridId: 'halo-dust',
    layer2Temporal: 'growth',
    layer3Temporal: 'evaporate',
  }
];
