import type { Layer2Type } from '../types';
import type { MotionArchitecture } from './motionArchitectureTypes';

export const OVERRIDES: Partial<Record<Layer2Type, Partial<Omit<MotionArchitecture, 'id' | 'family'>>>> = {
  resonance_flux: {
    driver: 'oscillation',
    temporalBehavior: 'oscillatory',
    editingProfile: 'shape',
    depictionHint: 'resonant standing flux',
    recommendedSources: ['grid', 'plane', 'text'],
    editingFocus: ['resonance', 'phase', 'interference'],
  },
  tidal_lock: {
    driver: 'orbit',
    temporalBehavior: 'steady',
    editingProfile: 'weave',
    depictionHint: 'locked tidal orbit band',
    recommendedSources: ['ring', 'torus', 'spiral'],
    editingFocus: ['orbit lock', 'phase lag', 'radius'],
  },
  fracture_bloom: {
    driver: 'transform',
    temporalBehavior: 'pulsed',
    editingProfile: 'explore',
    depictionHint: 'fracture burst bloom',
    recommendedSources: ['cube', 'text', 'sphere'],
    editingFocus: ['burst', 'spread', 'fragment drift'],
  },
  ember_drift: {
    driver: 'field',
    temporalBehavior: 'decay',
    editingProfile: 'atmosphere',
    depictionHint: 'ember-laden drift',
    recommendedSources: ['sphere', 'plane', 'text'],
    editingFocus: ['lift', 'falloff', 'glow'],
  },
  lattice_surge: {
    driver: 'structural',
    temporalBehavior: 'pulsed',
    editingProfile: 'shape',
    depictionHint: 'surging lattice scaffold',
    recommendedSources: ['grid', 'cube', 'text'],
    editingFocus: ['cell pulse', 'snap', 'phase'],
  },
  glyph_weave: {
    driver: 'transform',
    temporalBehavior: 'oscillatory',
    editingProfile: 'weave',
    depictionHint: 'woven glyph signal',
    recommendedSources: ['text', 'image', 'plane'],
    editingFocus: ['script density', 'weave offset', 'drift'],
  },
  ion_rain: {
    driver: 'volumetric',
    temporalBehavior: 'decay',
    editingProfile: 'atmosphere',
    depictionHint: 'charged rainfall fog',
    recommendedSources: ['sphere', 'cube'],
    editingFocus: ['fall speed', 'density', 'glow'],
  },
  velvet_ash: {
    driver: 'volumetric',
    temporalBehavior: 'decay',
    editingProfile: 'atmosphere',
    depictionHint: 'soft ash veil',
    recommendedSources: ['sphere', 'text'],
    editingFocus: ['softness', 'falloff', 'density'],
  },
  shell_script: {
    driver: 'structural',
    temporalBehavior: 'steady',
    editingProfile: 'shape',
    depictionHint: 'inscribed shell',
    recommendedSources: ['text', 'sphere', 'cube'],
    editingFocus: ['shell opacity', 'script contrast', 'fresnel'],
  },
  prism_threads: {
    driver: 'structural',
    temporalBehavior: 'oscillatory',
    editingProfile: 'weave',
    depictionHint: 'spectral thread weave',
    recommendedSources: ['cylinder', 'spiral', 'text'],
    editingFocus: ['thread density', 'length', 'glow'],
  },
  pollen_lattice: {
    driver: 'growth',
    temporalBehavior: 'emergent',
    editingProfile: 'grow',
    depictionHint: 'spore lattice scaffold',
    recommendedSources: ['cube', 'sphere'],
    editingFocus: ['cell scale', 'seed density', 'spread'],
  },
  eclipse_halo: {
    driver: 'structural',
    temporalBehavior: 'pulsed',
    editingProfile: 'shape',
    depictionHint: 'shadowed halo shell',
    recommendedSources: ['sphere', 'ring'],
    editingFocus: ['halo radius', 'falloff', 'occlusion'],
  },
  static_smoke: {
    driver: 'volumetric',
    temporalBehavior: 'oscillatory',
    editingProfile: 'atmosphere',
    depictionHint: 'electrostatic smoke',
    recommendedSources: ['cube', 'text'],
    editingFocus: ['noise scale', 'flicker', 'density'],
  },
  resin_shell: {
    driver: 'deposition',
    temporalBehavior: 'emergent',
    editingProfile: 'accumulate',
    depictionHint: 'resin-coated shell',
    recommendedSources: ['sphere', 'text'],
    editingFocus: ['gloss', 'thickness', 'drip'],
  },

  viscoelastic_membrane: {
    driver: 'structural',
    temporalBehavior: 'oscillatory',
    editingProfile: 'shape',
    depictionHint: 'viscoelastic rebound membrane',
    recommendedSources: ['plane', 'cylinder', 'text'],
    editingFocus: ['memory sag', 'rebound snap', 'wind damping'],
  },
  percolation_sheet: {
    driver: 'deposition',
    temporalBehavior: 'emergent',
    editingProfile: 'accumulate',
    depictionHint: 'percolating receiving sheet',
    recommendedSources: ['text', 'image', 'plane'],
    editingFocus: ['wick paths', 'band soak', 'channel retention'],
  },
  talus_heap: {
    driver: 'deposition',
    temporalBehavior: 'decay',
    editingProfile: 'accumulate',
    depictionHint: 'talus heap body',
    recommendedSources: ['plane', 'sphere', 'grid'],
    editingFocus: ['slope angle', 'pile slip', 'fragment density'],
  },
  corrosion_front: {
    driver: 'growth',
    temporalBehavior: 'decay',
    editingProfile: 'grow',
    depictionHint: 'corroding reaction front',
    recommendedSources: ['grid', 'text', 'plane'],
    editingFocus: ['etch edge', 'pit spread', 'front crawl'],
  },
  creep_lattice: {
    driver: 'structural',
    temporalBehavior: 'oscillatory',
    editingProfile: 'shape',
    depictionHint: 'slow creeping lattice scaffold',
    recommendedSources: ['grid', 'cube', 'cylinder'],
    editingFocus: ['beam creep', 'span sag', 'snap drag'],
  },
  melt_front: {
    driver: 'transform', temporalBehavior: 'decay', editingProfile: 'shape', depictionHint: 'melting brush front', recommendedSources: ['plane', 'image', 'text'], editingFocus: ['front softness', 'drip shear', 'thermal bleed'],
  },
  freeze_skin: {
    driver: 'structural', temporalBehavior: 'emergent', editingProfile: 'shape', depictionHint: 'frozen shell skin', recommendedSources: ['sphere', 'plane', 'cube'], editingFocus: ['ice crust', 'frost ring', 'shell lock'],
  },
  condense_field: {
    driver: 'volumetric', temporalBehavior: 'emergent', editingProfile: 'atmosphere', depictionHint: 'condensing fog body', recommendedSources: ['plane', 'sphere', 'video'], editingFocus: ['droplet core', 'fog thickening', 'sink bands'],
  },
  evaporative_sheet: {
    driver: 'transform', temporalBehavior: 'decay', editingProfile: 'shape', depictionHint: 'evaporating surface sheet', recommendedSources: ['plane', 'text', 'image'], editingFocus: ['edge thinning', 'plate retreat', 'salt fringe'],
  },
  sublimate_cloud: {
    driver: 'volumetric', temporalBehavior: 'decay', editingProfile: 'atmosphere', depictionHint: 'sublimating vapor cloud', recommendedSources: ['sphere', 'ring', 'video'], editingFocus: ['lifted loss', 'crystal haze', 'hollow core'],
  },
};
