import type { Layer2Type } from '../types';
import type { MotionArchitecture } from './motionArchitectureTypes';

export const OVERRIDES: Partial<Record<Layer2Type, Partial<Omit<MotionArchitecture, 'id' | 'family'>>>> = {
  orbit_swarm: {
    driver: 'orbit',
    temporalBehavior: 'oscillatory',
    editingProfile: 'weave',
    depictionHint: 'multi-orbit swarm',
    recommendedSources: ['ring', 'sphere', 'torus'],
    editingFocus: ['radius', 'phase offset', 'swarm spread'],
  },
  braid_stream: {
    driver: 'orbit',
    temporalBehavior: 'steady',
    editingProfile: 'weave',
    depictionHint: 'braided particle stream',
    recommendedSources: ['spiral', 'ring', 'cylinder'],
    editingFocus: ['strand spacing', 'curl', 'phase'],
  },
  pulse_breathing: {
    driver: 'oscillation',
    temporalBehavior: 'pulsed',
    editingProfile: 'shape',
    depictionHint: 'breathing pulse envelope',
    recommendedSources: ['sphere', 'ring', 'text'],
    editingFocus: ['breath depth', 'frequency', 'phase'],
  },
  collapse_fracture: {
    driver: 'transform',
    temporalBehavior: 'decay',
    editingProfile: 'explore',
    depictionHint: 'collapse and fracture field',
    recommendedSources: ['cube', 'text', 'plane'],
    editingFocus: ['collapse center', 'shatter spread', 'decay'],
  },
  crawl_seep: {
    driver: 'field',
    temporalBehavior: 'steady',
    editingProfile: 'explore',
    depictionHint: 'creeping seep current',
    recommendedSources: ['plane', 'image', 'text'],
    editingFocus: ['surface drift', 'density', 'viscosity'],
  },
  interference_wave: {
    driver: 'oscillation',
    temporalBehavior: 'oscillatory',
    editingProfile: 'shape',
    depictionHint: 'wave interference scaffold',
    recommendedSources: ['plane', 'grid', 'text'],
    editingFocus: ['frequency offset', 'symmetry', 'density'],
  },
  flock_drift: {
    driver: 'field',
    temporalBehavior: 'steady',
    editingProfile: 'weave',
    depictionHint: 'flocking drift swarm',
    recommendedSources: ['sphere', 'ring', 'plane'],
    editingFocus: ['cohesion', 'spread', 'drift'],
  },
  vortex_sheet: {
    driver: 'orbit',
    temporalBehavior: 'oscillatory',
    editingProfile: 'shape',
    depictionHint: 'sheeted vortex orbit',
    recommendedSources: ['disc', 'ring', 'plane'],
    editingFocus: ['swirl radius', 'sheet depth', 'phase'],
  },
  cloth_membrane: {
    driver: 'structural',
    temporalBehavior: 'oscillatory',
    editingProfile: 'shape',
    depictionHint: 'cloth membrane',
    recommendedSources: ['plane', 'text', 'cylinder'],
    editingFocus: ['drape', 'fold', 'wind ripple'],
  },
  viscous_flow: {
    driver: 'field',
    temporalBehavior: 'steady',
    editingProfile: 'shape',
    depictionHint: 'viscous sheet flow',
    recommendedSources: ['plane', 'image', 'video'],
    editingFocus: ['drag', 'pooling', 'bleed'],
  },
  granular_fall: {
    driver: 'deposition',
    temporalBehavior: 'decay',
    editingProfile: 'accumulate',
    depictionHint: 'granular fall body',
    recommendedSources: ['sphere', 'plane', 'video'],
    editingFocus: ['grain density', 'fall bias', 'pile spread'],
  },
  fracture_grammar: {
    driver: 'growth',
    temporalBehavior: 'decay',
    editingProfile: 'grow',
    depictionHint: 'fracture grammar scaffold',
    recommendedSources: ['plane', 'text', 'grid'],
    editingFocus: ['branch angle', 'crack gating', 'shatter spread'],
  },
  growth_grammar: {
    driver: 'growth',
    temporalBehavior: 'emergent',
    editingProfile: 'grow',
    depictionHint: 'growth grammar scaffold',
    recommendedSources: ['sphere', 'plane', 'text'],
    editingFocus: ['branch grammar', 'arbor depth', 'tip rate'],
  },
  branch_propagation: {
    driver: 'growth',
    temporalBehavior: 'emergent',
    editingProfile: 'grow',
    depictionHint: 'branch propagation network',
    recommendedSources: ['sphere', 'text', 'plane'],
    editingFocus: ['branch spread', 'segment growth', 'density'],
  },
  seep_fracture: {
    driver: 'deposition',
    temporalBehavior: 'decay',
    editingProfile: 'accumulate',
    depictionHint: 'fractured seep trace',
    recommendedSources: ['plane', 'image', 'text'],
    editingFocus: ['fracture width', 'erosion', 'drift'],
  },
  standing_interference: {
    driver: 'oscillation',
    temporalBehavior: 'oscillatory',
    editingProfile: 'shape',
    depictionHint: 'standing interference lattice',
    recommendedSources: ['plane', 'grid', 'text'],
    editingFocus: ['node spacing', 'frequency', 'stability'],
  },
  ember_swarm: {
    driver: 'transform',
    temporalBehavior: 'decay',
    editingProfile: 'explore',
    depictionHint: 'ember-like spark swarm',
    recommendedSources: ['sphere', 'cone', 'text'],
    editingFocus: ['spark size', 'falloff', 'glow'],
  },
  biofilm_skin: {
    driver: 'growth',
    temporalBehavior: 'emergent',
    editingProfile: 'grow',
    depictionHint: 'biofilm reaction skin',
    recommendedSources: ['plane', 'text', 'image'],
    editingFocus: ['feed', 'kill', 'skin thickness'],
  },
  static_lace: {
    driver: 'structural',
    temporalBehavior: 'steady',
    editingProfile: 'weave',
    depictionHint: 'lace-like line scaffold',
    recommendedSources: ['plane', 'grid', 'text'],
    editingFocus: ['strand density', 'curl', 'lace spacing'],
  },
  vapor_canopy: {
    driver: 'volumetric',
    temporalBehavior: 'steady',
    editingProfile: 'atmosphere',
    depictionHint: 'hanging vapor canopy',
    recommendedSources: ['sphere', 'plane', 'cube'],
    editingFocus: ['density', 'canopy depth', 'drift'],
  },
  fracture_pollen: {
    driver: 'transform',
    temporalBehavior: 'decay',
    editingProfile: 'explore',
    depictionHint: 'fracture-born pollen debris',
    recommendedSources: ['cube', 'sphere', 'text'],
    editingFocus: ['fragment scale', 'dispersion', 'shimmer'],
  },
  tremor_lattice: {
    driver: 'oscillation',
    temporalBehavior: 'oscillatory',
    editingProfile: 'shape',
    depictionHint: 'tremoring lattice displacement',
    recommendedSources: ['grid', 'plane', 'text'],
    editingFocus: ['tremor speed', 'node spacing', 'amplitude'],
  },
  bloom_torrent: {
    driver: 'growth',
    temporalBehavior: 'emergent',
    editingProfile: 'grow',
    depictionHint: 'blooming torrent surge',
    recommendedSources: ['sphere', 'cone', 'plane'],
    editingFocus: ['surge radius', 'expansion', 'density'],
  },
  orbit_fracture: {
    driver: 'orbit',
    temporalBehavior: 'decay',
    editingProfile: 'explore',
    depictionHint: 'orbiting fracture field',
    recommendedSources: ['ring', 'cube', 'text'],
    editingFocus: ['orbit radius', 'fracture spread', 'spin'],
  },
  foam_drift: {
    driver: 'field',
    temporalBehavior: 'steady',
    editingProfile: 'atmosphere',
    depictionHint: 'foam-like drifting surface',
    recommendedSources: ['plane', 'disc', 'sphere'],
    editingFocus: ['bubble spread', 'drift', 'softness'],
  },
  signal_braid: {
    driver: 'oscillation',
    temporalBehavior: 'oscillatory',
    editingProfile: 'weave',
    depictionHint: 'signalling braided current',
    recommendedSources: ['text', 'spiral', 'ring'],
    editingFocus: ['braid spacing', 'phase offset', 'signal strength'],
  },
  soot_veil: {
    driver: 'volumetric',
    temporalBehavior: 'decay',
    editingProfile: 'atmosphere',
    depictionHint: 'soot-black hanging veil',
    recommendedSources: ['plane', 'text', 'cube'],
    editingFocus: ['smoke density', 'falloff', 'veil thickness'],
  },
  nerve_web: {
    driver: 'structural',
    temporalBehavior: 'steady',
    editingProfile: 'weave',
    depictionHint: 'neural web filament scaffold',
    recommendedSources: ['image', 'text', 'sphere'],
    editingFocus: ['branch density', 'junctions', 'curl'],
  },
  bloom_spores: {
    driver: 'growth',
    temporalBehavior: 'emergent',
    editingProfile: 'grow',
    depictionHint: 'spore bloom aggregate',
    recommendedSources: ['sphere', 'cone', 'text'],
    editingFocus: ['spore size', 'dispersion', 'bloom rate'],
  },
  mirror_skin: {
    driver: 'transform',
    temporalBehavior: 'steady',
    editingProfile: 'shape',
    depictionHint: 'reflective mirrored skin shell',
    recommendedSources: ['sphere', 'cube', 'text'],
    editingFocus: ['shell smoothness', 'reflective edge', 'symmetry'],
  },
  pollen_storm: {
    driver: 'field',
    temporalBehavior: 'decay',
    editingProfile: 'explore',
    depictionHint: 'storm of bright pollen fragments',
    recommendedSources: ['sphere', 'plane', 'text'],
    editingFocus: ['particle spread', 'flutter', 'glow'],
  },
  charge_veil: {
    driver: 'volumetric',
    temporalBehavior: 'oscillatory',
    editingProfile: 'atmosphere',
    depictionHint: 'electrified drifting veil',
    recommendedSources: ['text', 'plane', 'cube'],
    editingFocus: ['charge glow', 'veil depth', 'drift'],
  },
  cinder_web: {
    driver: 'structural',
    temporalBehavior: 'decay',
    editingProfile: 'weave',
    depictionHint: 'charred web of glowing cinders',
    recommendedSources: ['image', 'text', 'sphere'],
    editingFocus: ['web density', 'ember nodes', 'curl'],
  },
  membrane_pollen: {
    driver: 'growth',
    temporalBehavior: 'emergent',
    editingProfile: 'grow',
    depictionHint: 'pollen bloom trapped in membrane skin',
    recommendedSources: ['sphere', 'text', 'plane'],
    editingFocus: ['shell softness', 'pollen density', 'spread'],
  },
  drift_glyph_dust: {
    driver: 'field',
    temporalBehavior: 'decay',
    editingProfile: 'explore',
    depictionHint: 'dust traces drifting off glyph-like surfaces',
    recommendedSources: ['text', 'image', 'plane'],
    editingFocus: ['glyph breakup', 'drift rate', 'dust mask'],
  },
  prism_smoke: {
    driver: 'volumetric',
    temporalBehavior: 'oscillatory',
    editingProfile: 'atmosphere',
    depictionHint: 'prismatic smoke volume with spectral lift',
    recommendedSources: ['cube', 'sphere', 'text'],
    editingFocus: ['spectrum glow', 'density', 'slice depth'],
  },
  spectral_mesh: {
    driver: 'structural',
    temporalBehavior: 'oscillatory',
    editingProfile: 'weave',
    depictionHint: 'spectral woven mesh',
    recommendedSources: ['text', 'plane', 'ring'],
    editingFocus: ['mesh density', 'phase', 'glow'],
  },
  ember_lace: {
    driver: 'structural',
    temporalBehavior: 'decay',
    editingProfile: 'weave',
    depictionHint: 'ember-like glowing lace',
    recommendedSources: ['ring', 'plane', 'text'],
    editingFocus: ['strand heat', 'spacing', 'drift'],
  },
  spore_halo: {
    driver: 'structural',
    temporalBehavior: 'pulsed',
    editingProfile: 'shape',
    depictionHint: 'halo shell carrying spores',
    recommendedSources: ['sphere', 'ring'],
    editingFocus: ['halo radius', 'spore glow', 'shell opacity'],
  },
  calcified_skin: {
    driver: 'structural',
    temporalBehavior: 'steady',
    editingProfile: 'shape',
    depictionHint: 'calcified shell skin',
    recommendedSources: ['sphere', 'cube', 'text'],
    editingFocus: ['shell thickness', 'rigidity', 'surface grain'],
  },
  rune_smoke: {
    driver: 'volumetric',
    temporalBehavior: 'oscillatory',
    editingProfile: 'atmosphere',
    depictionHint: 'inscribed smoke plume',
    recommendedSources: ['text', 'plane', 'ring'],
    editingFocus: ['smoke density', 'glyph breakup', 'drift'],
  },

};
