import type { Layer2Type } from '../types';
import type { MotionArchitecture } from './motionArchitectureTypes';

export const OVERRIDES: Partial<Record<Layer2Type, Partial<Omit<MotionArchitecture, 'id' | 'family'>>>> = {
  sheet: {
    driver: 'structural',
    temporalBehavior: 'steady',
    editingProfile: 'shape',
    depictionHint: 'membrane surface',
    recommendedSources: ['plane', 'grid', 'text'],
    editingFocus: ['opacity', 'fresnel', 'surface tension'],
  },
  surface_shell: {
    driver: 'structural',
    temporalBehavior: 'steady',
    editingProfile: 'shape',
    depictionHint: 'shell enclosure',
    recommendedSources: ['sphere', 'cube'],
    editingFocus: ['shell thickness', 'point budget', 'jitter'],
  },
  surface_patch: {
    driver: 'structural',
    temporalBehavior: 'steady',
    editingProfile: 'shape',
    depictionHint: 'patch surface',
    recommendedSources: ['plane', 'text', 'image'],
    editingFocus: ['resolution', 'relax', 'opacity'],
  },
  brush_surface: {
    driver: 'transform',
    temporalBehavior: 'steady',
    editingProfile: 'shape',
    depictionHint: 'brush veil',
    recommendedSources: ['plane', 'text', 'image'],
    editingFocus: ['layers', 'stroke jitter', 'scale'],
  },
  fiber_field: {
    driver: 'structural',
    temporalBehavior: 'oscillatory',
    editingProfile: 'weave',
    depictionHint: 'fiber strands',
    recommendedSources: ['cylinder', 'sphere'],
    editingFocus: ['strand length', 'density', 'curl'],
  },
  growth_field: {
    driver: 'growth',
    temporalBehavior: 'emergent',
    editingProfile: 'grow',
    depictionHint: 'branch growth',
    recommendedSources: ['sphere', 'plane'],
    editingFocus: ['branches', 'length', 'spread'],
  },
  deposition_field: {
    driver: 'deposition',
    temporalBehavior: 'emergent',
    editingProfile: 'accumulate',
    depictionHint: 'sediment field',
    recommendedSources: ['plane', 'image'],
    editingFocus: ['relief', 'bands', 'erosion'],
  },
  crystal_aggregate: {
    driver: 'growth',
    temporalBehavior: 'emergent',
    editingProfile: 'grow',
    depictionHint: 'crystal cluster',
    recommendedSources: ['sphere', 'cube'],
    editingFocus: ['cluster scale', 'density', 'spread'],
  },
  erosion_trail: {
    driver: 'deposition',
    temporalBehavior: 'decay',
    editingProfile: 'accumulate',
    depictionHint: 'erosion trails',
    recommendedSources: ['plane', 'text'],
    editingFocus: ['trail length', 'density', 'drift'],
  },
  voxel_lattice: {
    driver: 'structural',
    temporalBehavior: 'steady',
    editingProfile: 'shape',
    depictionHint: 'voxel scaffold',
    recommendedSources: ['cube', 'plane'],
    editingFocus: ['snap', 'density', 'cell scale'],
  },
  crystal_deposition: {
    driver: 'deposition',
    temporalBehavior: 'emergent',
    editingProfile: 'accumulate',
    depictionHint: 'mineral accretion',
    recommendedSources: ['plane', 'image'],
    editingFocus: ['crystal scale', 'density', 'relief'],
  },
  reaction_diffusion: {
    driver: 'growth',
    temporalBehavior: 'oscillatory',
    editingProfile: 'grow',
    depictionHint: 'reaction skin',
    recommendedSources: ['plane', 'text'],
    editingFocus: ['feed', 'kill', 'warp'],
  },
  volume_fog: {
    driver: 'volumetric',
    temporalBehavior: 'steady',
    editingProfile: 'atmosphere',
    depictionHint: 'fog volume',
    recommendedSources: ['sphere', 'cube'],
    editingFocus: ['density', 'depth', 'slices'],
  },

};
