import type { OperatorRecipe } from './operatorMatrixTypes';

export const BASE_OPERATOR_RECIPE_LIBRARY_RAW: OperatorRecipe[] = [

  {
    id: 'operator-fluid-capillary-ledger',
    label: 'Fluid Capillary Ledger',
    summary: 'fluid × sheet × capillary × ledger × text。インク受け皿の大量網羅起点。',
    mode: 'capillary_sheet', source: 'text', dedicatedAxis: 'text-inscription', material: 'ink', geometry: 'plate', dynamics: 'capillary', inscription: 'ledger', temporal: 'percolate', materialStyle: 'halftone', count: 9800, baseSize: 0.82, reviewTags: ['fluid', 'plate', 'ledger'],
  },
  {
    id: 'operator-fluid-advection-plane',
    label: 'Fluid Advection Plane',
    summary: 'fluid × sheet × advection × plain × plane。流動面の基準。',
    mode: 'advection_flow', source: 'plane', dedicatedAxis: 'plane-ledger', material: 'vapor', geometry: 'sheet', dynamics: 'advection', inscription: 'plain', temporal: 'intermittent', materialStyle: 'classic', count: 9400, baseSize: 0.88, reviewTags: ['fluid', 'sheet', 'advection'],
  },
  {
    id: 'operator-vapor-vortex-rune',
    label: 'Vapor Vortex Rune',
    summary: 'vapor × fog × vortex × rune × ring。渦輸送と記述霧の束。',
    mode: 'vortex_transport', source: 'ring', dedicatedAxis: 'ring-orbit', material: 'vapor', geometry: 'fog', dynamics: 'vortex', inscription: 'rune', temporal: 'erupt', materialStyle: 'glass', count: 7600, baseSize: 1.14, radiusScale: 1.12, reviewTags: ['fog', 'vortex', 'rune'],
  },
  {
    id: 'operator-vapor-pressure-grid',
    label: 'Vapor Pressure Grid',
    summary: 'vapor × fog × pressure × plain × grid。セル圧の構造霧。',
    mode: 'pressure_cells', source: 'grid', dedicatedAxis: 'grid-architectonic', material: 'vapor', geometry: 'fog', dynamics: 'pressure', inscription: 'plain', temporal: 'hysteresis', materialStyle: 'glass', count: 7200, baseSize: 1.08, reviewTags: ['fog', 'grid', 'pressure'],
  },
  {
    id: 'operator-granular-avalanche',
    label: 'Granular Avalanche Slope',
    summary: 'granular × aggregate × avalanche × plain × plane。斜面崩積の基準。',
    mode: 'avalanche_field', source: 'plane', dedicatedAxis: 'plane-ledger', material: 'ash', geometry: 'aggregate', dynamics: 'avalanche', inscription: 'plain', temporal: 'fatigue', materialStyle: 'halftone', count: 11200, baseSize: 0.66, reviewTags: ['granular', 'aggregate', 'slope'],
  },
  {
    id: 'operator-granular-jam-cube',
    label: 'Granular Jammed Cube',
    summary: 'granular × aggregate × jam × ledger × cube。詰まりと空隙の束。',
    mode: 'jammed_pack', source: 'cube', dedicatedAxis: 'grid-architectonic', material: 'dust', geometry: 'aggregate', dynamics: 'jam', inscription: 'ledger', temporal: 'recover', materialStyle: 'classic', count: 9800, baseSize: 0.78, reviewTags: ['granular', 'pack', 'jam'],
  },
  {
    id: 'operator-membrane-viscoelastic-glyph',
    label: 'Viscoelastic Glyph Membrane',
    summary: 'membrane × sheet × viscoelastic × glyph × text。記号膜の起点。',
    mode: 'viscoelastic_membrane', source: 'text', dedicatedAxis: 'text-inscription', material: 'glass', geometry: 'sheet', dynamics: 'viscoelastic', inscription: 'glyph', temporal: 'rebound', materialStyle: 'glass', count: 9800, baseSize: 0.94, radiusScale: 1.1, reviewTags: ['membrane', 'glyph', 'memory'],
  },
  {
    id: 'operator-shell-freeze-contour',
    label: 'Freeze Contour Shell',
    summary: 'shell × freeze × contour × sphere。相変化 shell の基準。',
    mode: 'freeze_skin', source: 'sphere', dedicatedAxis: 'phase-transition', material: 'glass', geometry: 'shell', dynamics: 'freeze', inscription: 'contour', temporal: 'invert', materialStyle: 'glass', count: 7600, baseSize: 1.0, radiusScale: 1.08, reviewTags: ['shell', 'freeze', 'contour'],
  },
  {
    id: 'operator-phase-melt-palimpsest',
    label: 'Melt Palimpsest Front',
    summary: 'phase × sheet × melt × palimpsest × plane。溶融前線と上書きの束。',
    mode: 'melt_front', source: 'plane', dedicatedAxis: 'phase-transition', material: 'resin', geometry: 'sheet', dynamics: 'melt', inscription: 'palimpsest', temporal: 'collapse', materialStyle: 'classic', count: 9000, baseSize: 0.92, reviewTags: ['phase', 'melt', 'palimpsest'],
  },
  {
    id: 'operator-phase-condense-ledger',
    label: 'Condense Ledger Basin',
    summary: 'phase × fog × pressure × ledger × plane。凝縮盆地の束。',
    mode: 'condense_field', source: 'plane', dedicatedAxis: 'phase-transition', material: 'glass', geometry: 'fog', dynamics: 'pressure', inscription: 'ledger', temporal: 'emerge', materialStyle: 'glass', count: 7600, baseSize: 1.06, reviewTags: ['phase', 'condense', 'ledger'],
  },
  {
    id: 'operator-phase-sublimate-ring',
    label: 'Sublimate Ring Cloud',
    summary: 'phase × fog × sublimate × contour × ring。昇華雲の基準。',
    mode: 'sublimate_cloud', source: 'ring', dedicatedAxis: 'phase-transition', material: 'vapor', geometry: 'fog', dynamics: 'sublimate', inscription: 'contour', temporal: 'invert', materialStyle: 'glass', count: 7000, baseSize: 1.12, radiusScale: 1.04, reviewTags: ['phase', 'sublimate', 'ring'],
  },
  {
    id: 'operator-shell-resin-palimpsest',
    label: 'Resin Palimpsest Shell',
    summary: 'shell × resin × palimpsest × image。樹脂被膜の束。',
    mode: 'resin_shell', source: 'image', dedicatedAxis: 'phase-transition', material: 'resin', geometry: 'shell', dynamics: 'melt', inscription: 'palimpsest', temporal: 'recur', materialStyle: 'classic', count: 8200, baseSize: 0.96, radiusScale: 1.08, reviewTags: ['shell', 'resin', 'trace'],
  },
  {
    id: 'operator-shell-calcified-ledger',
    label: 'Calcified Ledger Shell',
    summary: 'shell × calcify × ledger × grid。鉱化 shell の束。',
    mode: 'calcified_skin', source: 'grid', dedicatedAxis: 'grid-architectonic', material: 'metal', geometry: 'shell', dynamics: 'static', inscription: 'ledger', temporal: 'ossify', materialStyle: 'chrome', count: 8200, baseSize: 0.9, radiusScale: 1.06, reviewTags: ['shell', 'calcify', 'grid'],
  },
  {
    id: 'operator-deposition-ink-plane',
    label: 'Ink Ledger Plane',
    summary: 'ink × plate × capillary × ledger × plane。受け皿系の基準。',
    mode: 'ink_bleed', source: 'plane', dedicatedAxis: 'plane-ledger', material: 'ink', geometry: 'plate', dynamics: 'capillary', inscription: 'ledger', temporal: 'rewrite', materialStyle: 'halftone', count: 10400, baseSize: 0.8, reviewTags: ['deposition', 'ink', 'plane'],
  },
  {
    id: 'operator-deposition-percolation-image',
    label: 'Percolation Image Plate',
    summary: 'ink × plate × percolation × palimpsest × image。浸透像の束。',
    mode: 'percolation_sheet', source: 'image', dedicatedAxis: 'plane-ledger', material: 'ink', geometry: 'plate', dynamics: 'capillary', inscription: 'palimpsest', temporal: 'percolate', materialStyle: 'halftone', count: 9600, baseSize: 0.82, reviewTags: ['deposition', 'percolation', 'image'],
  },
  {
    id: 'operator-lattice-creep-grid',
    label: 'Creep Grid Lattice',
    summary: 'lattice × creep × plain × grid。緩慢変形格子の束。',
    mode: 'creep_lattice', source: 'grid', dedicatedAxis: 'grid-architectonic', material: 'metal', geometry: 'lattice', dynamics: 'creep', inscription: 'plain', temporal: 'rebound', materialStyle: 'glass', count: 9400, baseSize: 0.82, reviewTags: ['lattice', 'creep', 'grid'],
  },
  {
    id: 'operator-lattice-elastic-glyph',
    label: 'Elastic Glyph Lattice',
    summary: 'lattice × elastic × glyph × cylinder。符号格子の束。',
    mode: 'elastic_lattice', source: 'cylinder', dedicatedAxis: 'grid-architectonic', material: 'glass', geometry: 'lattice', dynamics: 'viscoelastic', inscription: 'glyph', temporal: 'anneal', materialStyle: 'glass', count: 9200, baseSize: 0.82, reviewTags: ['lattice', 'elastic', 'glyph'],
  },
  {
    id: 'operator-growth-grammar-text',
    label: 'Growth Grammar Text',
    summary: 'growth × front × grammar × glyph × text。再帰成長の束。',
    mode: 'growth_grammar', source: 'text', dedicatedAxis: 'text-inscription', material: 'bio', geometry: 'front', dynamics: 'growth', inscription: 'glyph', temporal: 'recur', materialStyle: 'classic', count: 8400, baseSize: 0.78, reviewTags: ['growth', 'grammar', 'text'],
  },
  {
    id: 'operator-fracture-grammar-grid',
    label: 'Fracture Grammar Grid',
    summary: 'front × grammar × contour × grid。破断文法の束。',
    mode: 'fracture_grammar', source: 'grid', dedicatedAxis: 'grid-architectonic', material: 'metal', geometry: 'front', dynamics: 'grammar', inscription: 'contour', temporal: 'rewrite', materialStyle: 'classic', count: 8600, baseSize: 0.76, reviewTags: ['fracture', 'grammar', 'grid'],
  },
  {
    id: 'operator-corrosion-rune-grid',
    label: 'Corrosion Rune Grid',
    summary: 'front × corrode × rune × grid。腐食前線の束。',
    mode: 'corrosion_front', source: 'grid', dedicatedAxis: 'erosion-wear', material: 'metal', geometry: 'front', dynamics: 'corrode', inscription: 'rune', temporal: 'fissure', materialStyle: 'chrome', count: 9200, baseSize: 0.8, reviewTags: ['corrosion', 'rune', 'grid'],
  },
  {
    id: 'operator-erosion-ledger-text',
    label: 'Erosion Ledger Text',
    summary: 'erosion × line/front × erode × ledger × text。侵食線と帳面痕の束。',
    mode: 'erosion_trail', source: 'text', dedicatedAxis: 'erosion-wear', material: 'dust', geometry: 'front', dynamics: 'erode', inscription: 'ledger', temporal: 'fatigue', materialStyle: 'halftone', count: 9800, baseSize: 0.76, reviewTags: ['erosion', 'text', 'ledger'],
  },
  {
    id: 'operator-dissolution-seep-image',
    label: 'Dissolution Seep Image',
    summary: 'dissolution × plate × dissolve × palimpsest × image。溶解と滲み崩れの束。',
    mode: 'seep_fracture', source: 'image', dedicatedAxis: 'erosion-wear', material: 'vapor', geometry: 'plate', dynamics: 'dissolve', inscription: 'palimpsest', temporal: 'collapse', materialStyle: 'glass', count: 9000, baseSize: 0.82, reviewTags: ['dissolution', 'image', 'seep'],
  },
  {
    id: 'operator-wear-residue-plane',
    label: 'Wear Residue Plane',
    summary: 'wear × shell/plate × abrade × ledger × plane。摩耗被膜と残渣面の束。',
    mode: 'residue_skin', source: 'plane', dedicatedAxis: 'erosion-wear', material: 'metal', geometry: 'shell', dynamics: 'abrade', inscription: 'ledger', temporal: 'hysteresis', materialStyle: 'chrome', count: 8400, baseSize: 0.9, radiusScale: 1.04, reviewTags: ['wear', 'plane', 'residue'],
  },
  {
    id: 'operator-pitted-calcify-grid',
    label: 'Pitted Calcify Grid',
    summary: 'wear/corrosion × shell × pit × contour × grid。孔食と鉱化の束。',
    mode: 'calcified_skin', source: 'grid', dedicatedAxis: 'grid-architectonic', material: 'metal', geometry: 'shell', dynamics: 'pit', inscription: 'contour', temporal: 'ossify', materialStyle: 'chrome', count: 8600, baseSize: 0.88, radiusScale: 1.06, reviewTags: ['pit', 'calcify', 'grid'],
  },
  {
    id: 'operator-biofilm-palimpsest-plane',
    label: 'Biofilm Palimpsest Plane',
    summary: 'bio × front × growth × palimpsest × plane。膜状生命 front の束。',
    mode: 'biofilm_skin', source: 'plane', dedicatedAxis: 'plane-ledger', material: 'bio', geometry: 'front', dynamics: 'growth', inscription: 'palimpsest', temporal: 'regrow', materialStyle: 'classic', count: 8800, baseSize: 0.84, reviewTags: ['bio', 'front', 'palimpsest'],
  },
  {
    id: 'operator-fog-ash-ledger',
    label: 'Ash Ledger Veil',
    summary: 'ash × fog × static × ledger × plane。灰帳面の束。',
    mode: 'soot_veil', source: 'plane', dedicatedAxis: 'plane-ledger', material: 'ash', geometry: 'fog', dynamics: 'static', inscription: 'ledger', temporal: 'shed', materialStyle: 'halftone', count: 8200, baseSize: 0.98, reviewTags: ['ash', 'fog', 'ledger'],
  },
  {
    id: 'operator-fog-velvet-plane',
    label: 'Velvet Ash Plane',
    summary: 'ash × fog × pressure × plain × plane。ベルベット灰の束。',
    mode: 'velvet_ash', source: 'plane', dedicatedAxis: 'plane-ledger', material: 'ash', geometry: 'fog', dynamics: 'pressure', inscription: 'plain', temporal: 'shed', materialStyle: 'halftone', count: 8200, baseSize: 0.98, reviewTags: ['ash', 'fog', 'matte'],
  },
  {
    id: 'operator-static-grid-smoke',
    label: 'Static Grid Smoke',
    summary: 'vapor × fog × static × glyph × grid。電子的な格子霧。',
    mode: 'static_smoke', source: 'grid', dedicatedAxis: 'grid-architectonic', material: 'vapor', geometry: 'fog', dynamics: 'static', inscription: 'glyph', temporal: 'oscillate', materialStyle: 'glass', count: 7600, baseSize: 1.02, reviewTags: ['static', 'fog', 'grid'],
  },
  {
    id: 'operator-mesh-prism-cylinder',
    label: 'Prism Thread Cylinder',
    summary: 'mesh × prism × glyph × cylinder。糸系大量網羅の束。',
    mode: 'prism_threads', source: 'cylinder', dedicatedAxis: 'ring-orbit', material: 'glass', geometry: 'mesh', dynamics: 'advection', inscription: 'glyph', temporal: 'resonate', materialStyle: 'chrome', count: 9800, baseSize: 0.78, reviewTags: ['mesh', 'prism', 'cylinder'],
  },
  {
    id: 'operator-halo-eclipse-ring',
    label: 'Eclipse Rune Halo',
    summary: 'shell × halo × rune × ring。halo 群の束。',
    mode: 'eclipse_halo', source: 'ring', dedicatedAxis: 'ring-orbit', material: 'glass', geometry: 'shell', dynamics: 'pressure', inscription: 'rune', temporal: 'oscillate', materialStyle: 'glass', count: 8200, baseSize: 0.92, radiusScale: 1.12, reviewTags: ['halo', 'ring', 'rune'],
  },
  {
    id: 'operator-glyph-weave-text',
    label: 'Glyph Weave Text',
    summary: 'mesh × glyph × text。字形編みの基準束。',
    mode: 'glyph_weave', source: 'text', dedicatedAxis: 'text-inscription', material: 'ink', geometry: 'mesh', dynamics: 'grammar', inscription: 'glyph', temporal: 'unravel', materialStyle: 'classic', count: 9200, baseSize: 0.8, reviewTags: ['mesh', 'glyph', 'text'],
  },
  {
    id: 'operator-stipple-grid-ledger',
    label: 'Stipple Grid Ledger',
    summary: 'plate × stipple × ledger × grid。点描格子の基準束。',
    mode: 'stipple_field', source: 'grid', dedicatedAxis: 'grid-architectonic', material: 'ink', geometry: 'plate', dynamics: 'static', inscription: 'ledger', temporal: 'accrete', materialStyle: 'halftone', count: 10200, baseSize: 0.78, reviewTags: ['stipple', 'grid', 'ledger'],
  },
];
