import type { ProductPackBundle } from './productPackLibraryTypes';

export const TOUCHDESIGNER_PRODUCT_PACK_BUNDLES: ProductPackBundle[] = [
{
    id: 'product-pack-touch-feedback-topology',
    label: 'Touch Feedback Topology',
    family: 'touchdesigner',
    summary: 'TOP feedback / contour rewrite / split-fringe chain をまとめた TouchDesigner 系の基準束です。',
    emphasis: ['feedback TOP', 'contour rewrite', 'orthographic smear'],
    postStackId: 'post-stack-touch-smear',
    solverFamilies: ['operator-graph', 'signal-image-field', 'simulation-zone'],
    specialistFamilies: ['touch-feedback-topology'],
    signature: {
      viewMode: 'orthographic',
      layer2Type: 'ribbon_veil',
      layer2Source: 'video',
      layer3Type: 'contour_echo',
      layer3Source: 'plane',
      postFxStackProfile: 'touch-feedback',
    },
    patch: {
      renderQuality: 'balanced',
      cameraControlMode: 'manual',
      viewMode: 'orthographic',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'ribbon_veil',
      layer2Source: 'video',
      layer2Count: 7600,
      layer2MaterialStyle: 'glass',
      layer2SheetOpacity: 0.64,
      layer2SheetFresnel: 0.82,
      layer2TemporalProfile: 'recur',
      layer2TemporalStrength: 0.24,
      layer2GhostTrailEnabled: true,
      layer2GlyphOutlineEnabled: false,
      layer2SdfEnabled: false,
      layer3Enabled: true,
      layer3Type: 'contour_echo',
      layer3Source: 'plane',
      layer3Count: 4200,
      layer3MaterialStyle: 'chrome',
      layer3TemporalProfile: 'rewrite',
      layer3TemporalStrength: 0.22,
      layer3GlyphOutlineEnabled: false,
      layer3SdfEnabled: false,
      gpgpuEnabled: false,
      audioEnabled: false,
      screenPersistenceIntensity: 0.12,
      screenPersistenceLayers: 3,
      screenSplitIntensity: 0.08,
      screenSplitOffset: 2.4,
      screenInterferenceIntensity: 0.08,
    },
  },
{
    id: 'product-pack-touch-pop-force-cloud',
    label: 'Touch POP Force Cloud',
    family: 'touchdesigner',
    summary: 'POP force / vector field / WebGPU instancing をまとめた GPU 粒子クラウド束です。',
    emphasis: ['POP forces', 'WebGPU instancing', 'spiral field'],
    postStackId: 'post-stack-touch-smear',
    solverFamilies: ['operator-graph', 'system-emitter', 'gpu-vfx-graph'],
    specialistFamilies: ['touch-pop-force-cloud'],
    signature: {
      gpgpuEnabled: true,
      gpgpuWebGPUEnabled: true,
      gpgpuGeomMode: 'cube',
      gpgpuVFieldEnabled: true,
      gpgpuVFieldType: 'spiral',
      postFxStackProfile: 'touch-feedback',
    },
    patch: {
      renderQuality: 'balanced',
      layer1Enabled: false,
      layer2Enabled: false,
      layer3Enabled: true,
      layer3Type: 'surface_shell',
      layer3Source: 'sphere',
      layer3Count: 2800,
      layer3MaterialStyle: 'glass',
      layer3HullOpacity: 0.12,
      layer3HullPointBudget: 840,
      layer3HullFresnel: 0.86,
      gpgpuEnabled: true,
      gpgpuWebGPUEnabled: true,
      gpgpuCount: 14336,
      gpgpuEmitShape: 'sphere',
      gpgpuGeomMode: 'cube',
      gpgpuGeomScale: 0.72,
      gpgpuOpacity: 0.72,
      gpgpuCurlEnabled: true,
      gpgpuCurlStrength: 1.24,
      gpgpuCurlScale: 0.008,
      gpgpuVFieldEnabled: true,
      gpgpuVFieldType: 'spiral',
      gpgpuVFieldStrength: 0.94,
      gpgpuVFieldScale: 0.0055,
      gpgpuTrailEnabled: true,
      gpgpuTrailLength: 8,
      gpgpuTrailFade: 0.68,
      gpgpuRibbonEnabled: false,
      gpgpuSmoothTubeEnabled: false,
      gpgpuMetaballEnabled: false,
      gpgpuVolumetricEnabled: false,
      gpgpuSortEnabled: true,
      gpgpuVelColorEnabled: true,
      audioEnabled: false,
      screenPersistenceIntensity: 0.06,
    },
  },
{
    id: 'product-pack-touch-curve-relief-feedback',
    label: 'Touch Curve Relief Feedback',
    family: 'touchdesigner',
    summary: 'curve / surface relief / feedback smear を束ねた SOP-TOP 的な基準束です。',
    emphasis: ['curve lines', 'surface relief', 'feedback split'],
    postStackId: 'post-stack-touch-smear',
    solverFamilies: ['operator-graph', 'signal-image-field', 'simulation-zone'],
    specialistFamilies: ['touch-curve-relief-feedback'],
    signature: {
      layer2Type: 'prism_threads',
      layer3Type: 'surface_patch',
      layer3Source: 'image',
      postFxStackProfile: 'touch-feedback',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'orthographic',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'prism_threads',
      layer2Source: 'spiral',
      layer2Count: 9600,
      layer2MaterialStyle: 'classic',
      layer2FlowAmplitude: 58,
      layer2Trail: 0.26,
      layer2TemporalProfile: 'oscillate',
      layer2TemporalStrength: 0.16,
      layer2LineVelocityGlow: 0.42,
      layer2LineVelocityAlpha: 0.24,
      layer2LineBurstPulse: 0.32,
      layer2LineShimmer: 0.22,
      layer2LineFlickerSpeed: 1.9,
      layer3Enabled: true,
      layer3Type: 'surface_patch',
      layer3Source: 'image',
      layer3Count: 3400,
      layer3MaterialStyle: 'glass',
      layer3PatchOpacity: 0.68,
      layer3PatchResolution: 64,
      layer3PatchRelax: 0.26,
      layer3PatchFresnel: 0.58,
      layer3PatchWireframe: true,
      gpgpuEnabled: false,
      audioEnabled: false,
      screenPersistenceIntensity: 0.08,
      screenSplitIntensity: 0.07,
      screenSplitOffset: 2.2,
    },
  },
{
    id: 'product-pack-touch-top-cop-signal-field',
    label: 'Touch TOP COP Signal Field',
    family: 'touchdesigner',
    summary: 'TOP / COP 的な image-feedback と signal rewriting をまとめた signal-field 系 pack です。',
    emphasis: ['signal field', 'image feedback', 'channel rewrite'],
    postStackId: 'post-stack-touch-smear',
    solverFamilies: ['operator-graph', 'signal-image-field'],
    specialistFamilies: ['touch-top-cop-signal-field'],
    signature: {
      layer2Type: 'interference_wave',
      layer3Type: 'contour_echo',
      postFxStackProfile: 'touch-feedback',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'orthographic',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'interference_wave',
      layer2Source: 'video',
      layer2Count: 9800,
      layer2MaterialStyle: 'hologram',
      layer2TemporalProfile: 'oscillate',
      layer2TemporalStrength: 0.24,
      layer2GhostTrailEnabled: true,
      layer3Enabled: true,
      layer3Type: 'contour_echo',
      layer3Source: 'image',
      layer3Count: 5200,
      layer3MaterialStyle: 'halftone',
      layer3TemporalProfile: 'rewrite',
      layer3TemporalStrength: 0.18,
      screenPersistenceIntensity: 0.14,
      screenSplitIntensity: 0.12,
      screenSplitOffset: 2.8,
      screenInterferenceIntensity: 0.1,
      audioEnabled: true,
      audioSourceMode: 'internal-synth',
      gpgpuEnabled: false,
    },
  }
];
