import type { ProductPackBundle } from './productPackLibraryTypes';

export const UNITY_VFX_PRODUCT_PACK_BUNDLES: ProductPackBundle[] = [
{
    id: 'product-pack-unity-vfx-gpu-sheet',
    label: 'Unity VFX GPU Sheet',
    family: 'unityvfx',
    summary: 'GPU Event 的な薄膜 ribbon / tube / audio-reactive drive をまとめた Unity VFX Graph 系 pack です。',
    emphasis: ['gpu event', 'sheet ribbons', 'audio drive'],
    postStackId: 'post-stack-particular-glow',
    solverFamilies: ['system-emitter', 'gpu-vfx-graph'],
    specialistFamilies: ['unity-vfx-gpu-sheet'],
    signature: {
      gpgpuEnabled: true,
      gpgpuWebGPUEnabled: true,
      gpgpuRibbonEnabled: true,
      gpgpuSmoothTubeEnabled: true,
      postFxStackProfile: 'particular-glow',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'orthographic',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'ribbon_veil',
      layer2Source: 'plane',
      layer2Count: 6400,
      layer2MaterialStyle: 'glass',
      layer2TemporalProfile: 'recur',
      layer2TemporalStrength: 0.18,
      layer2SheetOpacity: 0.52,
      layer2SheetFresnel: 0.7,
      layer3Enabled: false,
      audioEnabled: true,
      audioSourceMode: 'internal-synth',
      gpgpuEnabled: true,
      gpgpuWebGPUEnabled: true,
      gpgpuCount: 16384,
      gpgpuEmitShape: 'disc',
      gpgpuGeomMode: 'icosa',
      gpgpuRibbonEnabled: true,
      gpgpuRibbonWidth: 3.8,
      gpgpuRibbonOpacity: 0.34,
      gpgpuSmoothTubeEnabled: true,
      gpgpuSmoothTubeRadius: 0.16,
      gpgpuSmoothTubeOpacity: 0.2,
      gpgpuAudioReactive: true,
      gpgpuAudioBlast: 0.28,
      gpgpuCurlEnabled: true,
      gpgpuCurlStrength: 0.92,
      gpgpuVFieldEnabled: true,
      gpgpuVFieldType: 'spiral',
      gpgpuVFieldStrength: 0.62,
      gpgpuTrailEnabled: true,
      gpgpuTrailLength: 8,
      gpgpuTrailFade: 0.7,
      gpgpuSortEnabled: true,
    },
  }
];
