import type { ProductPackBundle } from './productPackLibraryTypes';

export const GEOMETRY_NODES_PRODUCT_PACK_BUNDLES: ProductPackBundle[] = [
{
    id: 'product-pack-geometrynodes-simulation-lattice',
    label: 'Geometry Nodes Simulation Lattice',
    family: 'geometrynodes',
    summary: 'voxel lattice と standing interference を束ね、Simulation Zone 的な構造+振動帯域を寄せた Geometry Nodes 系 pack です。',
    emphasis: ['simulation zone', 'lattice', 'oscillation'],
    postStackId: 'post-stack-manual-neutral',
    solverFamilies: ['simulation-zone'],
    specialistFamilies: ['geometrynodes-simulation-lattice'],
    signature: {
      layer2Type: 'voxel_lattice',
      layer3Type: 'standing_interference',
      postFxStackProfile: 'manual',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'orthographic',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'voxel_lattice',
      layer2Source: 'grid',
      layer2Count: 8200,
      layer2MaterialStyle: 'chrome',
      layer2TemporalProfile: 'recur',
      layer2TemporalStrength: 0.2,
      layer2VoxelOpacity: 0.58,
      layer2VoxelScale: 1.06,
      layer2VoxelDensity: 0.46,
      layer2VoxelSnap: 0.86,
      layer3Enabled: true,
      layer3Type: 'standing_interference',
      layer3Source: 'plane',
      layer3Count: 6800,
      layer3MaterialStyle: 'halftone',
      layer3TemporalProfile: 'oscillate',
      layer3TemporalStrength: 0.24,
      layer3PatchOpacity: 0.54,
      gpgpuEnabled: false,
      audioEnabled: false,
    },
  },
{
    id: 'product-pack-geometrynodes-reaction-growth-plate',
    label: 'Geometry Nodes Reaction Growth Plate',
    family: 'geometrynodes',
    summary: 'reaction diffusion と growth field を束ね、反応面と増殖面を往復する Geometry Nodes 系 pack です。',
    emphasis: ['reaction plate', 'growth field', 'surface recursion'],
    postStackId: 'post-stack-dream-smear',
    solverFamilies: ['simulation-zone', 'task-graph'],
    specialistFamilies: ['geometrynodes-reaction-growth-plate'],
    signature: {
      layer2Type: 'reaction_diffusion',
      layer3Type: 'growth_field',
      postFxStackProfile: 'dream-smear',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'orthographic',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'reaction_diffusion',
      layer2Source: 'plane',
      layer2Count: 11200,
      layer2MaterialStyle: 'hologram',
      layer2TemporalProfile: 'rewrite',
      layer2TemporalStrength: 0.24,
      layer2ReactionOpacity: 0.78,
      layer2ReactionFeed: 0.026,
      layer2ReactionKill: 0.056,
      layer2ReactionScale: 1.08,
      layer2ReactionWarp: 0.2,
      layer3Enabled: true,
      layer3Type: 'growth_field',
      layer3Source: 'plane',
      layer3Count: 7600,
      layer3MaterialStyle: 'classic',
      layer3TemporalProfile: 'growth',
      layer3TemporalStrength: 0.24,
      layer3GrowthOpacity: 0.76,
      layer3GrowthBranches: 6,
      layer3GrowthLength: 0.9,
      layer3GrowthSpread: 0.38,
      gpgpuEnabled: false,
      audioEnabled: false,
      depthFogEnabled: false,
    },
  }
];
