import type { ProductPackBundle } from './productPackLibraryTypes';

export const TRAPCODE_PRODUCT_PACK_BUNDLES: ProductPackBundle[] = [
{
    id: 'product-pack-trapcode-particular-noir',
    label: 'Trapcode Particular Noir',
    family: 'trapcode',
    summary: 'cone emitter / age color / streak / glow をまとめた Particular 系の基準束です。',
    emphasis: ['cone emitter', 'age color', 'glow trails'],
    postStackId: 'post-stack-particular-glow',
    solverFamilies: ['system-emitter'],
    specialistFamilies: ['trapcode-particular-noir'],
    signature: {
      gpgpuEnabled: true,
      gpgpuEmitShape: 'cone',
      gpgpuStreakEnabled: true,
      gpgpuAgeEnabled: true,
      postFxStackProfile: 'particular-glow',
    },
    patch: {
      renderQuality: 'balanced',
      layer1Enabled: false,
      layer2Enabled: false,
      layer3Enabled: false,
      ambientEnabled: false,
      audioEnabled: true,
      audioSourceMode: 'internal-synth',
      gpgpuEnabled: true,
      gpgpuWebGPUEnabled: false,
      gpgpuCount: 18432,
      gpgpuEmitShape: 'cone',
      gpgpuOpacity: 0.82,
      gpgpuSize: 1.28,
      gpgpuAudioReactive: true,
      gpgpuAudioBlast: 0.38,
      gpgpuWindEnabled: true,
      gpgpuWindStrength: 0.34,
      gpgpuWindX: 0.0,
      gpgpuWindY: 0.22,
      gpgpuWindZ: 0.12,
      gpgpuTrailEnabled: true,
      gpgpuTrailLength: 10,
      gpgpuTrailFade: 0.72,
      gpgpuStreakEnabled: true,
      gpgpuStreakLength: 24,
      gpgpuStreakOpacity: 0.38,
      gpgpuAgeEnabled: true,
      gpgpuAgeMax: 8.2,
      gpgpuAgeColorEnabled: true,
      gpgpuAgeSizeEnabled: true,
      gpgpuVelColorEnabled: true,
      gpgpuRibbonEnabled: false,
      gpgpuSmoothTubeEnabled: false,
      screenPulseIntensity: 0.08,
    },
  },
{
    id: 'product-pack-trapcode-particular-audio-sparks',
    label: 'Trapcode Particular Audio Sparks',
    family: 'trapcode',
    summary: 'burst / ring emitter / audio blast / spark ribbon を強めた動的モーショングラフィックス束です。',
    emphasis: ['audio blast', 'ring emitter', 'spark ribbons'],
    postStackId: 'post-stack-particular-glow',
    solverFamilies: ['system-emitter', 'signal-image-field'],
    specialistFamilies: ['trapcode-particular-audio-sparks'],
    signature: {
      gpgpuEnabled: true,
      gpgpuEmitShape: 'ring',
      gpgpuRibbonEnabled: true,
      gpgpuAudioReactive: true,
      postFxStackProfile: 'particular-glow',
    },
    patch: {
      renderQuality: 'balanced',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'halo_bloom',
      layer2Source: 'text',
      layer2TextMapText: 'SYNC',
      layer2Count: 6400,
      layer2MaterialStyle: 'glass',
      layer2TemporalProfile: 'resonate',
      layer2TemporalStrength: 0.28,
      layer2GlyphOutlineEnabled: true,
      layer2GlyphOutlineWidth: 1.28,
      layer2GlyphOutlineOpacity: 0.46,
      layer3Enabled: false,
      audioEnabled: true,
      audioSourceMode: 'internal-synth',
      gpgpuEnabled: true,
      gpgpuCount: 12288,
      gpgpuEmitShape: 'ring',
      gpgpuRibbonEnabled: true,
      gpgpuRibbonWidth: 4.2,
      gpgpuRibbonTaper: 0.84,
      gpgpuRibbonOpacity: 0.42,
      gpgpuAudioReactive: true,
      gpgpuAudioBlast: 0.42,
      gpgpuCurlEnabled: true,
      gpgpuCurlStrength: 1.04,
      gpgpuCurlScale: 0.01,
      gpgpuVortexEnabled: true,
      gpgpuVortexStrength: 0.92,
      gpgpuVortexTilt: 0.36,
      gpgpuAgeEnabled: true,
      gpgpuAgeColorEnabled: true,
      screenPulseIntensity: 0.12,
      screenBurstDrive: 0.14,
    },
  },
{
    id: 'product-pack-trapcode-form-lattice',
    label: 'Trapcode Form Lattice',
    family: 'trapcode',
    summary: 'grid particle lattice / connection sheet / fiber overlay を束ねた Form 系の構造束です。',
    emphasis: ['grid lattice', 'connection mesh', 'fiber overlay'],
    postStackId: 'post-stack-particular-glow',
    solverFamilies: ['system-emitter', 'simulation-zone'],
    specialistFamilies: ['trapcode-form-lattice'],
    signature: {
      viewMode: 'orthographic',
      layer2Type: 'voxel_lattice',
      layer2Source: 'grid',
      layer3Type: 'signal_braid',
      postFxStackProfile: 'particular-glow',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'orthographic',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'voxel_lattice',
      layer2Source: 'grid',
      layer2Count: 9800,
      layer2MaterialStyle: 'halftone',
      layer2TemporalProfile: 'oscillate',
      layer2TemporalStrength: 0.18,
      layer2VoxelOpacity: 0.82,
      layer2VoxelScale: 1.06,
      layer2VoxelDensity: 0.48,
      layer2VoxelSnap: 0.42,
      layer2ConnectionEnabled: true,
      layer2ConnectionDistance: 26,
      layer2ConnectionOpacity: 0.16,
      layer3Enabled: true,
      layer3Type: 'signal_braid',
      layer3Source: 'grid',
      layer3Count: 4200,
      layer3MaterialStyle: 'classic',
      layer3FiberOpacity: 0.74,
      layer3FiberLength: 0.88,
      layer3FiberDensity: 0.7,
      layer3FiberCurl: 0.12,
      gpgpuEnabled: false,
      audioEnabled: false,
      screenScanlineIntensity: 0.14,
      screenInterferenceIntensity: 0.06,
    },
  },
{
    id: 'product-pack-trapcode-form-sdf-swarm',
    label: 'Trapcode Form SDF Swarm',
    family: 'trapcode',
    summary: 'instanced object swarm / SDF collision / ribbon trails を束ねた Form 拡張束です。',
    emphasis: ['instanced swarm', 'SDF collision', 'ribbon trails'],
    postStackId: 'post-stack-particular-glow',
    solverFamilies: ['system-emitter', 'gpu-vfx-graph'],
    specialistFamilies: ['trapcode-form-sdf-swarm'],
    signature: {
      gpgpuEnabled: true,
      gpgpuGeomMode: 'icosa',
      gpgpuSdfEnabled: true,
      gpgpuRibbonEnabled: true,
      postFxStackProfile: 'particular-glow',
    },
    patch: {
      renderQuality: 'balanced',
      layer1Enabled: false,
      layer2Enabled: false,
      layer3Enabled: false,
      audioEnabled: false,
      gpgpuEnabled: true,
      gpgpuWebGPUEnabled: true,
      gpgpuCount: 16384,
      gpgpuEmitShape: 'ring',
      gpgpuGeomMode: 'icosa',
      gpgpuGeomScale: 0.84,
      gpgpuOpacity: 0.74,
      gpgpuCurlEnabled: true,
      gpgpuCurlStrength: 1.08,
      gpgpuCurlScale: 0.009,
      gpgpuVortexEnabled: true,
      gpgpuVortexStrength: 0.86,
      gpgpuVortexTilt: 0.3,
      gpgpuSdfEnabled: true,
      gpgpuSdfShape: 'torus',
      gpgpuSdfSize: 18,
      gpgpuSdfBounce: 0.74,
      gpgpuTrailEnabled: true,
      gpgpuTrailLength: 9,
      gpgpuTrailFade: 0.7,
      gpgpuRibbonEnabled: true,
      gpgpuRibbonWidth: 3.6,
      gpgpuRibbonTaper: 0.82,
      gpgpuRibbonOpacity: 0.34,
      gpgpuSortEnabled: true,
      gpgpuVelColorEnabled: true,
      screenPersistenceIntensity: 0.04,
    },
  }
];
