import type { ProductPackBundle } from './productPackLibraryTypes';

export const HOUDINI_PRODUCT_PACK_BUNDLES: ProductPackBundle[] = [
{
    id: 'product-pack-houdini-pyro-vortex-column',
    label: 'Houdini Pyro Vortex Column',
    family: 'houdini',
    summary: 'vortex transport / condense field / sparse pyro 的なボリューム帯域を束ねた Houdini 系の volumetric pack です。',
    emphasis: ['pyro volume', 'vortex transport', 'condense field'],
    postStackId: 'post-stack-dream-smear',
    solverFamilies: ['volumetric-solver'],
    specialistFamilies: ['houdini-pyro-vortex-column'],
    signature: {
      layer2Type: 'vortex_transport',
      layer3Type: 'condense_field',
      postFxStackProfile: 'dream-smear',
    },
    patch: {
      renderQuality: 'cinematic',
      cameraControlMode: 'auto',
      viewMode: 'perspective',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'vortex_transport',
      layer2Source: 'ring',
      layer2Count: 8200,
      layer2MaterialStyle: 'glass',
      layer2TemporalProfile: 'erupt',
      layer2TemporalStrength: 0.24,
      layer2FogOpacity: 0.3,
      layer2FogDensity: 0.42,
      layer2FogDepth: 0.9,
      layer2FogScale: 1.08,
      layer2FogDrift: 0.28,
      layer2FogSlices: 24,
      layer2FogGlow: 0.18,
      layer2FogAnisotropy: 0.52,
      layer3Enabled: true,
      layer3Type: 'condense_field',
      layer3Source: 'plane',
      layer3Count: 6200,
      layer3MaterialStyle: 'glass',
      layer3TemporalProfile: 'emerge',
      layer3TemporalStrength: 0.22,
      layer3FogOpacity: 0.26,
      layer3FogDensity: 0.5,
      layer3FogDepth: 0.7,
      layer3FogScale: 0.92,
      layer3FogDrift: 0.12,
      layer3FogSlices: 22,
      layer3FogGlow: 0.1,
      layer3FogAnisotropy: 0.24,
      depthFogEnabled: true,
      gpgpuEnabled: false,
      audioEnabled: false,
      screenPersistenceIntensity: 0.08,
      screenInterferenceIntensity: 0.06,
    },
  },
{
    id: 'product-pack-houdini-vellum-granular-drape',
    label: 'Houdini Vellum Granular Drape',
    family: 'houdini',
    summary: 'cloth membrane と granular fall を重ね、布・粒・堆積の帯域をまとめた Houdini 系の PBD pack です。',
    emphasis: ['vellum cloth', 'granular fall', 'deposition'],
    postStackId: 'post-stack-manual-neutral',
    solverFamilies: ['pbd-solver'],
    specialistFamilies: ['houdini-vellum-granular-drape'],
    signature: {
      layer2Type: 'cloth_membrane',
      layer3Type: 'granular_fall',
      postFxStackProfile: 'manual',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'perspective',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'cloth_membrane',
      layer2Source: 'plane',
      layer2Count: 7600,
      layer2MaterialStyle: 'glass',
      layer2TemporalProfile: 'inhale',
      layer2TemporalStrength: 0.22,
      layer2SheetOpacity: 0.46,
      layer2SheetFresnel: 0.74,
      layer3Enabled: true,
      layer3Type: 'granular_fall',
      layer3Source: 'sphere',
      layer3Count: 9800,
      layer3MaterialStyle: 'halftone',
      layer3TemporalProfile: 'accumulate',
      layer3TemporalStrength: 0.24,
      layer3CrystalOpacity: 0.72,
      layer3CrystalScale: 0.88,
      layer3CrystalDensity: 0.84,
      layer3CrystalSpread: 0.24,
      gpgpuEnabled: false,
      audioEnabled: false,
      depthFogEnabled: true,
    },
  },
{
    id: 'product-pack-houdini-growth-arbor',
    label: 'Houdini Growth Arbor',
    family: 'houdini',
    summary: 'growth grammar / branch propagation / biofilm skin を束ね、成長ソルバ系の帯域を寄せた Houdini 系 pack です。',
    emphasis: ['growth grammar', 'branch propagation', 'solver growth'],
    postStackId: 'post-stack-dream-smear',
    solverFamilies: ['task-graph'],
    specialistFamilies: ['houdini-growth-arbor'],
    signature: {
      layer2Type: 'growth_grammar',
      layer3Type: 'branch_propagation',
      postFxStackProfile: 'dream-smear',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'orthographic',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'growth_grammar',
      layer2Source: 'sphere',
      layer2Count: 9000,
      layer2MaterialStyle: 'hologram',
      layer2TemporalProfile: 'rewrite',
      layer2TemporalStrength: 0.28,
      layer2GrowthOpacity: 0.8,
      layer2GrowthBranches: 8,
      layer2GrowthLength: 1.02,
      layer2GrowthSpread: 0.48,
      layer3Enabled: true,
      layer3Type: 'branch_propagation',
      layer3Source: 'text',
      layer3TextMapText: 'ARBOR',
      layer3Count: 7200,
      layer3MaterialStyle: 'classic',
      layer3TemporalProfile: 'growth',
      layer3TemporalStrength: 0.24,
      layer3FiberOpacity: 0.78,
      layer3FiberLength: 0.86,
      layer3FiberDensity: 144,
      layer3FiberCurl: 0.18,
      gpgpuEnabled: false,
      audioEnabled: false,
    },
  },
{
    id: 'product-pack-houdini-mpm-slurry-stack',
    label: 'Houdini MPM Slurry Stack',
    family: 'houdini',
    summary: '泥・堆積・粘性流を寄せた MPM / material behavior 系 pack です。',
    emphasis: ['slurry stack', 'viscous flow', 'sediment body'],
    postStackId: 'post-stack-dream-smear',
    solverFamilies: ['mpm-material'],
    specialistFamilies: ['houdini-mpm-slurry-stack'],
    signature: {
      layer2Type: 'viscous_flow',
      layer3Type: 'sediment_stack',
      postFxStackProfile: 'dream-smear',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'orthographic',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'viscous_flow',
      layer2Source: 'image',
      layer2Count: 9200,
      layer2MaterialStyle: 'halftone',
      layer2TemporalProfile: 'rewrite',
      layer2TemporalStrength: 0.22,
      layer2SheetOpacity: 0.72,
      layer2SheetFresnel: 0.36,
      layer3Enabled: true,
      layer3Type: 'sediment_stack',
      layer3Source: 'plane',
      layer3Count: 7800,
      layer3MaterialStyle: 'chrome',
      layer3TemporalProfile: 'growth',
      layer3TemporalStrength: 0.18,
      gpgpuEnabled: false,
      audioEnabled: false,
      depthFogEnabled: true,
      depthFogNear: 420,
      depthFogFar: 2200,
    },
  },
{
    id: 'product-pack-houdini-destruction-fracture-debris',
    label: 'Houdini Destruction Fracture Debris',
    family: 'houdini',
    summary: 'fracture grammar / collapse / shard debris を束ねた destruction 系 pack です。',
    emphasis: ['fracture grammar', 'collapse field', 'shard debris'],
    postStackId: 'post-stack-retro-feedback',
    solverFamilies: ['destruction-fracture'],
    specialistFamilies: ['houdini-destruction-fracture-debris'],
    signature: {
      layer2Type: 'fracture_grammar',
      layer3Type: 'shard_debris',
      postFxStackProfile: 'retro-feedback',
    },
    patch: {
      renderQuality: 'balanced',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'fracture_grammar',
      layer2Source: 'text',
      layer2Count: 11000,
      layer2MaterialStyle: 'classic',
      layer2TemporalProfile: 'rewrite',
      layer2TemporalStrength: 0.22,
      layer2ConnectionEnabled: true,
      layer2SparkEnabled: true,
      layer2SparkCount: 260,
      layer3Enabled: true,
      layer3Type: 'shard_debris',
      layer3Source: 'cube',
      layer3Count: 6400,
      layer3MaterialStyle: 'chrome',
      layer3TemporalProfile: 'decay',
      layer3TemporalStrength: 0.28,
      layer3SparkEnabled: true,
      layer3SparkCount: 240,
      gpgpuEnabled: false,
      audioEnabled: false,
      screenInterferenceIntensity: 0.06,
    },
  },
{
    id: 'product-pack-houdini-shell-metaball-volume',
    label: 'Houdini Shell Metaball Volume',
    family: 'houdini',
    summary: 'shell-volume source / metaball surface / volumetric density をまとめた render-gap 補強 pack です。',
    emphasis: ['shell volume', 'metaball iso-surface', 'density volume'],
    postStackId: 'post-stack-dream-smear',
    solverFamilies: ['volumetric-solver', 'mpm-material'],
    specialistFamilies: ['houdini-shell-metaball-volume'],
    signature: {
      gpgpuEnabled: true,
      gpgpuEmitShape: 'shell',
      gpgpuMetaballEnabled: true,
      gpgpuVolumetricEnabled: true,
      postFxStackProfile: 'dream-smear',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'perspective',
      layer1Enabled: false,
      layer2Enabled: false,
      layer3Enabled: true,
      layer3Type: 'surface_shell',
      layer3Source: 'sphere',
      layer3Count: 3600,
      layer3MaterialStyle: 'glass',
      layer3GeomMode3D: 'cube',
      layer3SdfEnabled: true,
      layer3HullOpacity: 0.18,
      layer3HullPointBudget: 960,
      layer3HullFresnel: 0.82,
      gpgpuEnabled: true,
      gpgpuWebGPUEnabled: true,
      gpgpuCount: 14336,
      gpgpuEmitShape: 'shell',
      gpgpuGeomMode: 'icosa',
      gpgpuGeomScale: 0.88,
      gpgpuOpacity: 0.58,
      gpgpuMetaballEnabled: true,
      gpgpuMetaballResolution: 24,
      gpgpuMetaballIsoLevel: 84,
      gpgpuVolumetricEnabled: true,
      gpgpuVolumetricSteps: 10,
      gpgpuVolumetricDensity: 2.2,
      gpgpuSmoothTubeEnabled: true,
      gpgpuTubeRadius: 0.05,
      gpgpuTrailEnabled: true,
      gpgpuTrailLength: 8,
      gpgpuVortexEnabled: true,
      gpgpuVortexStrength: 0.48,
      gpgpuAgeColorEnabled: true,
      audioEnabled: false,
      postVignetteEnabled: true,
      postVignetteOffset: 0.28,
      postVignetteDarkness: 0.72,
      screenVignetteIntensity: 0.08,
    },
  }
];
