import type { ProductPackBundle } from './productPackLibraryTypes';

export const HYBRID_PRODUCT_PACK_BUNDLES: ProductPackBundle[] = [
{
    id: 'product-pack-hybrid-audio-operator-stack',
    label: 'Hybrid Audio Operator Stack',
    family: 'hybrid',
    summary: 'text / halo / ribbon / audio reactive motion を束ねた横断的な operator 束です。',
    emphasis: ['audio reactive', 'text halo', 'operator hybrid'],
    postStackId: 'post-stack-dream-smear',
    solverFamilies: ['operator-graph', 'signal-image-field', 'task-graph'],
    specialistFamilies: ['hybrid-audio-operator-stack'],
    signature: {
      audioEnabled: true,
      layer2Type: 'halo_bloom',
      gpgpuRibbonEnabled: true,
      gpgpuAudioReactive: true,
      postFxStackProfile: 'dream-smear',
    },
    patch: {
      renderQuality: 'balanced',
      audioEnabled: true,
      audioSourceMode: 'internal-synth',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'halo_bloom',
      layer2Source: 'text',
      layer2TextMapText: 'SYNC',
      layer2Count: 6400,
      layer2MaterialStyle: 'glass',
      layer2TemporalProfile: 'resonate',
      layer2TemporalStrength: 0.28,
      layer2GlyphOutlineEnabled: true,
      layer2GlyphOutlineWidth: 1.28,
      layer2GlyphOutlineOpacity: 0.46,
      layer3Enabled: true,
      layer3Type: 'surface_shell',
      layer3Source: 'text',
      layer3TextMapText: 'SYNC',
      layer3Count: 2200,
      layer3MaterialStyle: 'chrome',
      layer3HullOpacity: 0.18,
      layer3HullPointBudget: 1200,
      layer3HullFresnel: 0.8,
      gpgpuEnabled: true,
      gpgpuCount: 12288,
      gpgpuEmitShape: 'ring',
      gpgpuRibbonEnabled: true,
      gpgpuRibbonWidth: 4.2,
      gpgpuRibbonTaper: 0.84,
      gpgpuRibbonOpacity: 0.42,
      gpgpuAudioReactive: true,
      gpgpuAudioBlast: 0.42,
      gpgpuCurlEnabled: true,
      gpgpuCurlStrength: 1.04,
      gpgpuCurlScale: 0.01,
      gpgpuVortexEnabled: true,
      gpgpuVortexStrength: 0.92,
      gpgpuVortexTilt: 0.36,
      gpgpuAgeEnabled: true,
      gpgpuAgeColorEnabled: true,
      screenPulseIntensity: 0.12,
      screenBurstDrive: 0.14,
    },
  },
{
    id: 'product-pack-hybrid-pdg-variant-sweep',
    label: 'Hybrid PDG Variant Sweep',
    family: 'hybrid',
    summary: 'growth grammar / crystal deposition / sequence drive を束ねた variant sweep 系 pack です。',
    emphasis: ['variant sweep', 'grammar growth', 'recipe branching'],
    postStackId: 'post-stack-manual-neutral',
    solverFamilies: ['task-graph', 'simulation-zone'],
    specialistFamilies: ['hybrid-pdg-variant-sweep'],
    signature: {
      layer2Type: 'growth_grammar',
      layer3Type: 'crystal_deposition',
      postFxStackProfile: 'manual',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'orthographic',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'growth_grammar',
      layer2Source: 'text',
      layer2Count: 8600,
      layer2MaterialStyle: 'classic',
      layer2TemporalProfile: 'growth',
      layer2TemporalStrength: 0.28,
      layer2ConnectionEnabled: true,
      layer3Enabled: true,
      layer3Type: 'crystal_deposition',
      layer3Source: 'image',
      layer3Count: 6000,
      layer3MaterialStyle: 'chrome',
      layer3TemporalProfile: 'growth',
      layer3TemporalStrength: 0.22,
      layer3CrystalDepositionOpacity: 0.62,
      layer3CrystalDepositionCrystalScale: 1.18,
      layer3CrystalDepositionDensity: 0.54,
      layer3CrystalDepositionRelief: 0.48,
      gpgpuEnabled: false,
      audioEnabled: false,
    },
  },
{
    id: 'product-pack-hybrid-contact-sdf-scatter',
    label: 'Hybrid Contact SDF Scatter',
    family: 'hybrid',
    summary: 'random scatter / shell source / contact FX / SDF shading をまとめた missing-target 補強 pack です。',
    emphasis: ['scatter field', 'contact glow', 'SDF shaded shell'],
    postStackId: 'post-stack-manual-neutral',
    solverFamilies: ['operator-graph', 'signal-image-field'],
    specialistFamilies: ['hybrid-contact-sdf-scatter'],
    signature: {
      layer2Source: 'random',
      gpgpuEmitShape: 'shell',
      interLayerContactFxEnabled: true,
      sdfShapeEnabled: true,
      postFxStackProfile: 'manual',
    },
    patch: {
      renderQuality: 'balanced',
      viewMode: 'orthographic',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'signal_braid',
      layer2Source: 'random',
      layer2Count: 9200,
      layer2MaterialStyle: 'halftone',
      layer2GeomMode3D: 'cube',
      layer2AuxEnabled: true,
      layer2SparkEnabled: true,
      layer2SdfEnabled: true,
      layer2TemporalProfile: 'oscillate',
      layer2TemporalStrength: 0.16,
      layer2ConnectionEnabled: true,
      layer3Enabled: true,
      layer3Type: 'surface_shell',
      layer3Source: 'sphere',
      layer3Count: 4800,
      layer3MaterialStyle: 'chrome',
      layer3GeomMode3D: 'icosa',
      layer3SdfEnabled: true,
      layer3GhostTrailEnabled: true,
      layer3HullOpacity: 0.14,
      layer3HullPointBudget: 720,
      interLayerCollisionEnabled: true,
      interLayerCollisionStrength: 0.42,
      interLayerContactFxEnabled: true,
      interLayerContactGlowBoost: 0.54,
      interLayerContactSizeBoost: 0.42,
      interLayerContactLineBoost: 0.32,
      interLayerContactScreenBoost: 0.24,
      sdfShapeEnabled: true,
      sdfShape: 'ring',
      postVignetteEnabled: true,
      postVignetteOffset: 0.26,
      postVignetteDarkness: 0.78,
      screenVignetteIntensity: 0.14,
      gpgpuEnabled: true,
      gpgpuEmitShape: 'shell',
      gpgpuCount: 4096,
      gpgpuOpacity: 0.26,
      audioEnabled: false,
    },
  }
];
