import type { ProductPackBundle } from './productPackLibraryTypes';

export const NIAGARA_PRODUCT_PACK_BUNDLES: ProductPackBundle[] = [
{
    id: 'product-pack-niagara-stateless-orbit-mesh',
    label: 'Niagara Stateless Orbit Mesh',
    family: 'niagara',
    summary: 'WebGPU instancing / ring orbit / stateless emitter 的な mesh-swarm を束ねた Niagara 系 pack です。',
    emphasis: ['stateless emitters', 'mesh swarm', 'orbit field'],
    postStackId: 'post-stack-touch-smear',
    solverFamilies: ['system-emitter', 'gpu-vfx-graph'],
    specialistFamilies: ['niagara-stateless-orbit-mesh'],
    signature: {
      gpgpuEnabled: true,
      gpgpuWebGPUEnabled: true,
      gpgpuWellEnabled: true,
      gpgpuNBodyEnabled: true,
      postFxStackProfile: 'touch-feedback',
    },
    patch: {
      renderQuality: 'balanced',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'orbit_swarm',
      layer2Source: 'ring',
      layer2Count: 12000,
      layer2MaterialStyle: 'classic',
      layer2TemporalProfile: 'oscillate',
      layer2TemporalStrength: 0.18,
      layer2Trail: 0.2,
      layer3Enabled: false,
      gpgpuEnabled: true,
      gpgpuWebGPUEnabled: true,
      gpgpuCount: 16384,
      gpgpuEmitShape: 'ring',
      gpgpuGeomMode: 'cube',
      gpgpuGeomScale: 0.64,
      gpgpuOpacity: 0.76,
      gpgpuWellEnabled: true,
      gpgpuWellStrength: 0.82,
      gpgpuVortexEnabled: true,
      gpgpuVortexStrength: 0.94,
      gpgpuVortexTilt: 0.32,
      gpgpuNBodyEnabled: true,
      gpgpuNBodyStrength: 0.46,
      gpgpuTrailEnabled: true,
      gpgpuTrailLength: 7,
      gpgpuTrailFade: 0.68,
      gpgpuSortEnabled: true,
      gpgpuVelColorEnabled: true,
      audioEnabled: false,
      screenPersistenceIntensity: 0.05,
    },
  },
{
    id: 'product-pack-niagara-collision-burst-field',
    label: 'Niagara Collision Burst Field',
    family: 'niagara',
    summary: 'SDF collision / mouse impulse / burst trails を束ねた Niagara 系の collision-event pack です。',
    emphasis: ['collision events', 'sdf field', 'burst trails'],
    postStackId: 'post-stack-particular-glow',
    solverFamilies: ['system-emitter', 'destruction-fracture'],
    specialistFamilies: ['niagara-collision-burst-field'],
    signature: {
      gpgpuEnabled: true,
      gpgpuSdfEnabled: true,
      gpgpuMouseEnabled: true,
      postFxStackProfile: 'particular-glow',
    },
    patch: {
      renderQuality: 'balanced',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'collapse_fracture',
      layer2Source: 'text',
      layer2TextMapText: 'SEV',
      layer2Count: 9600,
      layer2MaterialStyle: 'chrome',
      layer2TemporalProfile: 'collapse',
      layer2TemporalStrength: 0.24,
      layer2Trail: 0.24,
      layer3Enabled: false,
      gpgpuEnabled: true,
      gpgpuCount: 14336,
      gpgpuEmitShape: 'cone',
      gpgpuOpacity: 0.8,
      gpgpuSdfEnabled: true,
      gpgpuSdfShape: 'torus',
      gpgpuMouseEnabled: true,
      gpgpuMouseMode: 'repel',
      gpgpuTrailEnabled: true,
      gpgpuTrailLength: 9,
      gpgpuTrailFade: 0.7,
      gpgpuStreakEnabled: true,
      gpgpuStreakLength: 18,
      gpgpuStreakOpacity: 0.3,
      gpgpuAgeEnabled: true,
      gpgpuAgeColorEnabled: true,
      gpgpuAgeSizeEnabled: true,
      gpgpuVelColorEnabled: true,
      audioEnabled: false,
      screenImpactFlashIntensity: 0.1,
      screenBurstDrive: 0.12,
    },
  },
{
    id: 'product-pack-niagara-chaos-magnetic-tubes',
    label: 'Niagara Chaos Magnetic Tubes',
    family: 'niagara',
    summary: 'chaos attractor / boids swarm / magnetic drift / tube trails を束ねた motion-gap 補強 pack です。',
    emphasis: ['chaos attractor', 'boids swarm', 'magnetic tubes'],
    postStackId: 'post-stack-particular-glow',
    solverFamilies: ['system-emitter', 'gpu-vfx-graph'],
    specialistFamilies: ['niagara-chaos-magnetic-tubes'],
    signature: {
      gpgpuEnabled: true,
      gpgpuTubeEnabled: true,
      gpgpuBoidsEnabled: true,
      gpgpuMagneticEnabled: true,
      gpgpuAttractorEnabled: true,
      gpgpuElasticEnabled: true,
      postFxStackProfile: 'particular-glow',
    },
    patch: {
      renderQuality: 'balanced',
      layer1Enabled: false,
      layer2Enabled: true,
      layer2Type: 'plasma_thread',
      layer2Source: 'random',
      layer2Count: 6800,
      layer2MaterialStyle: 'glass',
      layer2GeomMode3D: 'icosa',
      layer2TemporalProfile: 'oscillate',
      layer2TemporalStrength: 0.2,
      layer2AuxEnabled: true,
      layer2SdfEnabled: true,
      layer3Enabled: false,
      gpgpuEnabled: true,
      gpgpuWebGPUEnabled: true,
      gpgpuCount: 16384,
      gpgpuEmitShape: 'ring',
      gpgpuGeomMode: 'cube',
      gpgpuGeomScale: 0.76,
      gpgpuOpacity: 0.74,
      gpgpuTubeEnabled: true,
      gpgpuTubeRadius: 0.07,
      gpgpuTubeOpacity: 0.74,
      gpgpuTrailEnabled: true,
      gpgpuTrailLength: 12,
      gpgpuTrailFade: 0.72,
      gpgpuSortEnabled: true,
      gpgpuBoidsEnabled: true,
      gpgpuBoidsRadius: 1.06,
      gpgpuBoidsAlignment: 0.72,
      gpgpuBoidsCohesion: 0.5,
      gpgpuBoidsSeparation: 1.2,
      gpgpuAttractorEnabled: true,
      gpgpuAttractorType: 'lorenz',
      gpgpuAttractorStrength: 0.74,
      gpgpuMagneticEnabled: true,
      gpgpuMagneticStrength: 0.62,
      gpgpuElasticEnabled: true,
      gpgpuElasticStrength: 0.46,
      gpgpuSpringEnabled: true,
      gpgpuSpringStrength: 0.3,
      gpgpuAgeColorEnabled: true,
      gpgpuVelColorEnabled: true,
      audioEnabled: false,
      screenVignetteIntensity: 0.1,
    },
  }
];
