import type { ProductPackBundle } from './productPackLibraryTypes';

export const UNIVERSE_PRODUCT_PACK_BUNDLES: ProductPackBundle[] = [
{
    id: 'product-pack-universe-retro-feedback',
    label: 'Universe Retro Feedback',
    family: 'universe',
    summary: 'retro scanline / split fringe / static smoke を束ねた Universe 系の映像処理束です。',
    emphasis: ['retro scanline', 'fringe split', 'static smoke'],
    postStackId: 'post-stack-retro-feedback',
    solverFamilies: ['signal-image-field', 'simulation-zone'],
    specialistFamilies: ['universe-retro-feedback'],
    signature: {
      layer2Type: 'echo_rings',
      layer3Type: 'static_smoke',
      screenScanlineIntensity: 0.42,
      postFxStackProfile: 'retro-feedback',
    },
    patch: {
      renderQuality: 'balanced',
      layer1Count: 7200,
      baseSize: 0.9,
      layer2Enabled: true,
      layer2Type: 'echo_rings',
      layer2Source: 'ring',
      layer2Count: 8600,
      layer2MaterialStyle: 'halftone',
      layer2TemporalProfile: 'intermittent',
      layer2TemporalStrength: 0.22,
      layer3Enabled: true,
      layer3Type: 'static_smoke',
      layer3Source: 'video',
      layer3Count: 3600,
      layer3MaterialStyle: 'chrome',
      gpgpuEnabled: false,
      audioEnabled: false,
      screenScanlineIntensity: 0.42,
      screenScanlineDensity: 720,
      screenNoiseIntensity: 0.16,
      screenInterferenceIntensity: 0.18,
      screenPersistenceIntensity: 0.08,
      screenPersistenceLayers: 2,
      screenSplitIntensity: 0.12,
      screenSplitOffset: 3.0,
      screenSweepIntensity: 0.18,
    },
  },
{
    id: 'product-pack-universe-broadcast-ghost',
    label: 'Universe Broadcast Ghost',
    family: 'universe',
    summary: 'broadcast ring / ghost persistence / scanline damage を強めた Universe 映像束です。',
    emphasis: ['broadcast rings', 'ghost persistence', 'screen damage'],
    postStackId: 'post-stack-retro-feedback',
    solverFamilies: ['signal-image-field', 'simulation-zone'],
    specialistFamilies: ['universe-broadcast-ghost'],
    signature: {
      layer2Type: 'ripple_ring',
      layer2Source: 'disc',
      screenSplitIntensity: 0.16,
      postFxStackProfile: 'retro-feedback',
    },
    patch: {
      renderQuality: 'balanced',
      layer1Enabled: true,
      layer1Count: 6400,
      layer2Enabled: true,
      layer2Type: 'ripple_ring',
      layer2Source: 'disc',
      layer2Count: 22000,
      layer2FlowAmplitude: 74,
      layer2FlowFrequency: 4.2,
      layer3Enabled: true,
      layer3Type: 'static_smoke',
      layer3Source: 'video',
      layer3Count: 2800,
      layer3MaterialStyle: 'chrome',
      gpgpuEnabled: false,
      audioEnabled: false,
      screenScanlineIntensity: 0.38,
      screenScanlineDensity: 640,
      screenNoiseIntensity: 0.18,
      screenInterferenceIntensity: 0.18,
      screenSweepIntensity: 0.2,
      screenPersistenceIntensity: 0.1,
      screenPersistenceLayers: 3,
      screenSplitIntensity: 0.16,
      screenSplitOffset: 3.2,
    },
  }
];
