import type { RenderModeDefinition } from './renderModeRegistryShared';
import {
  anyLayer,
  anyLayerMode,
  layerUsesProceduralSystem,
} from './renderModeRegistryShared';
import {
  doesLayerRenderConnectionLines,
  doesLayerRenderConnectionStyle,
  doesLayerRenderGhostTrail,
  doesLayerRenderGlyphOutline,
  doesLayerRenderInstancedSolids,
  doesLayerRenderParticleCore,
  doesLayerRenderTextInstancedSolids,
  doesLayerUseMediaParticleLayout,
} from './sceneRenderRoutingRuntime';

export const RENDER_MODE_LAYER_MODES: RenderModeDefinition[] = [
  {
      id: 'layer-points',
      label: 'Layer Points / Sprites',
      category: 'particles',
      support: 'stable',
      description: 'CPU particle layers rendered as billboards, rings, sparks, and soft sprites.',
      activeWhen: (config) => Boolean(config.layer1Enabled || config.ambientEnabled || doesLayerRenderParticleCore(config, 2) || doesLayerRenderParticleCore(config, 3)),
    },
  {
      id: 'layer-image-layout',
      label: 'Image-driven Particle Layout',
      category: 'particles',
      support: 'experimental',
      description: 'Particle emitters distributed from image luminance maps.',
      activeWhen: (config) => anyLayer(config, (layerIndex) => doesLayerUseMediaParticleLayout(config, layerIndex, 'image')),
    },
  {
      id: 'layer-video-layout',
      label: 'Video-driven Particle Layout',
      category: 'particles',
      support: 'experimental',
      description: 'Particle emitters resampled from uploaded video frames.',
      activeWhen: (config) => anyLayer(config, (layerIndex) => doesLayerUseMediaParticleLayout(config, layerIndex, 'video')),
    },
  {
      id: 'layer-text-layout',
      label: 'Text / Glyph Particle Layout',
      category: 'particles',
      support: 'experimental',
      description: 'Particle emitters distributed from dynamically rasterized text and glyph shapes.',
      activeWhen: (config) => anyLayer(config, (layerIndex) => doesLayerUseMediaParticleLayout(config, layerIndex, 'text')),
    },
  {
      id: 'layer-lines',
      label: 'Layer Connection Lines',
      category: 'lines',
      support: 'stable',
      description: 'Inter-particle connection graph for Layer 2 / 3.',
      activeWhen: (config) => anyLayer(config, (layerIndex) => doesLayerRenderConnectionLines(config, layerIndex)),
    },
  {
      id: 'layer-brush-lines',
      label: 'Brush Connection Strips',
      category: 'lines',
      support: 'experimental',
      description: 'Camera-facing soft strips for painterly plexus strokes.',
      activeWhen: (config) => anyLayer(config, (layerIndex) => doesLayerRenderConnectionStyle(config, layerIndex, 'brush')),
    },
  {
      id: 'layer-filament-lines',
      label: 'Filament Connection Strips',
      category: 'lines',
      support: 'experimental',
      description: 'Thin glowing strand-like line ribbons for fibrous webs.',
      activeWhen: (config) => anyLayer(config, (layerIndex) => doesLayerRenderConnectionStyle(config, layerIndex, 'filament')),
    },
  {
      id: 'layer-sheet-membrane',
      label: 'Sheet / Membrane Surface',
      category: 'surfaces',
      support: 'experimental',
      description: 'CPU-updated membrane mesh woven from layer particle motion.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'membrane'),
    },
  {
      id: 'layer-surface-shell',
      label: 'Surface Shell',
      category: 'surfaces',
      support: 'experimental',
      description: 'Convex shell surface reconstructed from layer particle positions.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'surface-shell'),
    },
  {
      id: 'layer-surface-patch',
      label: 'Surface Patch',
      category: 'surfaces',
      support: 'experimental',
      description: 'Patch surface reconstructed from sampled layer positions.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'surface-patch'),
    },
  {
      id: 'layer-brush-surface',
      label: 'Brush Surface Wash',
      category: 'surfaces',
      support: 'experimental',
      description: 'Painterly layered brush-sheet surface.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'brush-surface'),
    },
  {
      id: 'layer-fiber-field',
      label: 'Fiber Field',
      category: 'lines',
      support: 'experimental',
      description: 'Sampled strand field grown from layer particle motion.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'fiber-field'),
    },
  {
      id: 'layer-growth-field',
      label: 'Growth Field',
      category: 'lines',
      support: 'experimental',
      description: 'Branch-like growth network generated from layer trajectories.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'growth-field'),
    },
  {
      id: 'layer-deposition-field',
      label: 'Deposition / Erosion Field',
      category: 'surfaces',
      support: 'experimental',
      description: 'Sedimentary accumulation and erosion surface.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'deposition-field'),
    },
  {
      id: 'layer-reaction-diffusion',
      label: 'Reaction Diffusion Surface',
      category: 'surfaces',
      support: 'experimental',
      description: 'Procedural reaction-diffusion style surface.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'reaction-diffusion'),
    },
  {
      id: 'layer-reaction-diffusion-front',
      label: 'Cellular / Corrosion Front Surface',
      category: 'surfaces',
      support: 'experimental',
      description: 'Front-biased reaction surface for crawling cellular and corrosive advance patterns.',
      activeWhen: (config) => anyLayerMode(config, ['cellular_front', 'corrosion_front']),
    },
  {
      id: 'layer-reaction-diffusion-biofilm',
      label: 'Biofilm Colony Skin',
      category: 'surfaces',
      support: 'experimental',
      description: 'Wet pooled colony membrane with thicker relief and pooled highlights.',
      activeWhen: (config) => anyLayerMode(config, ['biofilm_skin']),
    },
  {
      id: 'layer-volume-fog',
      label: 'Volume Fog Stack',
      category: 'volumetric',
      support: 'heavy',
      description: 'Layered slice-based volumetric fog.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'volume-fog'),
    },
  {
      id: 'layer-crystal-aggregate',
      label: 'Crystal Aggregate',
      category: 'instanced solids',
      support: 'experimental',
      description: 'Clustered crystal formations sampled from particle motion.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'crystal-aggregate'),
    },
  {
      id: 'layer-voxel-lattice',
      label: 'Voxel Lattice',
      category: 'instanced solids',
      support: 'experimental',
      description: 'Snapped voxel or lattice-like aggregate field.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'voxel-lattice'),
    },
  {
      id: 'layer-crystal-deposition',
      label: 'Crystal Deposition Hybrid',
      category: 'instanced solids',
      support: 'experimental',
      description: 'Hybrid deposition surface with crystalline accretion.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'crystal-deposition'),
    },
  {
      id: 'layer-erosion-trails',
      label: 'Erosion Trail Network',
      category: 'lines',
      support: 'experimental',
      description: 'Runoff and gully trail lines derived from layer motion.',
      activeWhen: (config) => layerUsesProceduralSystem(config, 'erosion-trail'),
    },
  {
      id: 'layer-glyph-outline',
      label: 'Glyph Outline Lines',
      category: 'lines',
      support: 'experimental',
      description: 'Outline extraction from text or glyph luminance maps.',
      activeWhen: (config) => anyLayer(config, (layerIndex) => doesLayerRenderGlyphOutline(config, layerIndex)),
    },
  {
      id: 'layer-ghost-trails',
      label: 'Ghost Trail Copies',
      category: 'ribbons',
      support: 'experimental',
      description: 'Time-offset layer echoes that thicken motion and silhouette.',
      activeWhen: (config) => anyLayer(config, (layerIndex) => doesLayerRenderGhostTrail(config, layerIndex)),
    },
  {
      id: 'layer-text-glyph-instanced-solids',
      label: 'Text / Glyph Instanced Solids',
      category: 'instanced solids',
      support: 'experimental',
      description: 'Instanced solids sampled from text luminance with glyph-banded scale, rotation, and depth offsets.',
      activeWhen: (config) => anyLayer(config, (layerIndex) => doesLayerRenderTextInstancedSolids(config, layerIndex)),
    },
  {
      id: 'layer-instanced-solids',
      label: 'Layer Instanced Solids',
      category: 'instanced solids',
      support: 'stable',
      description: 'Layer 2 / 3 particles rendered as cubes, tetrahedra, or icosahedra.',
      activeWhen: (config) => anyLayer(config, (layerIndex) => doesLayerRenderInstancedSolids(config, layerIndex)),
    },
  {
      id: 'layer-sdf-particles',
      label: 'Layer SDF Shading',
      category: 'sdf shading',
      support: 'stable',
      description: 'Analytic particle shading for sphere/ring/star/hex styles.',
      activeWhen: (config) => Boolean(config.sdfShapeEnabled || config.layer2SdfEnabled || config.layer3SdfEnabled),
    },
];
