import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_BASE_CHUNK_01_FOUNDATIONAL: PresetRecord[] = [
  createStarterPreset('starter-simple-clean', 'Starter Clean', {
      cameraControlMode: 'hybrid',
      renderQuality: 'balanced',
      cameraDistance: 60,
      opacity: 0.85,
      contrast: 1.0,
      particleSoftness: 0.5,
      particleGlow: 0.2,
      rotationSpeedX: 0.0005,
      rotationSpeedY: 0.001,
      layer1Enabled: true,
      layer1Count: 2000,
      baseSize: 1.0,
      sphereRadius: 50,
      layer1Volume: 0.0,
      jitter: 0.0,
      pulseSpeed: 0.003,
      pulseAmplitude: 0.5,
      layer2Enabled: false,
      layer2Type: 'flow',
      layer2Source: 'sphere',
      layer2Count: 3000,
      layer2BaseSize: 0.8,
      layer2RadiusScale: 1.0,
      layer2FlowAmplitude: 20,
      layer2FlowFrequency: 1.5,
      layer2Trail: 0,
      layer2NoiseScale: 1.0,
      layer2FluidForce: 1.0,
      layer2Life: 0,
      layer2LifeSpread: 0,
      layer2Burst: 0,
      layer2Streak: 0,
      layer2Fidelity: 1,
      layer2ConnectionEnabled: false,
      layer2AuxEnabled: false,
      layer2SparkEnabled: false,
      layer3Enabled: false,
      ambientEnabled: false,
      ambientCount: 0,
      ambientBaseSize: 0.5,
      screenPersistenceIntensity: 0,
      screenNoiseIntensity: 0,
      screenInterferenceIntensity: 0,
      screenPulseIntensity: 0,
      screenBurstDrive: 0,
      depthFogEnabled: false,
    }),
  createStarterPreset('starter-fluid-curl', 'Fluid Curl Field', {
      cameraControlMode: 'hybrid',
      renderQuality: 'balanced',
      layer1Count: 18000,
      layer2Type: 'curl',
      layer2Count: 28000,
      layer2FlowAmplitude: 62,
      layer2FlowFrequency: 2.6,
      layer2Trail: 0.62,
      layer2NoiseScale: 1.25,
      layer2FluidForce: 1.4,
      layer3Enabled: true,
      layer3Type: 'smoke',
      layer3Count: 9000,
      layer3BaseSize: 0.75,
      screenPersistenceIntensity: 0.08,
    }),
  createStarterPreset('starter-chaos-lorenz', 'Chaos Lorenz Bloom', {
      cameraControlMode: 'auto',
      renderQuality: 'cinematic',
      layer1Count: 14000,
      layer2Type: 'lorenz',
      layer2Count: 32000,
      layer2FlowAmplitude: 84,
      layer2Complexity: 3.4,
      layer2Trail: 0.3,
      layer3Enabled: true,
      layer3Type: 'thomas',
      layer3Count: 12000,
      layer3FlowAmplitude: 68,
      layer3Trail: 0.52,
      screenPulseIntensity: 0.14,
      depthFogEnabled: true,
    }),
  createStarterPreset('starter-orbital-epicycle', 'Orbital Epicycle', {
      layer1Count: 12000,
      baseSize: 1.2,
      sphereRadius: 150,
      layer2Type: 'epicycle',
      layer2Count: 26000,
      layer2Source: 'ring',
      layer2FlowAmplitude: 58,
      layer2ConnectionEnabled: true,
      layer2ConnectionDistance: 34,
      layer2ConnectionOpacity: 0.18,
      layer3Enabled: true,
      layer3Type: 'orbit',
      layer3Count: 6000,
      layer3Source: 'torus',
      layer3BaseSize: 0.72,
    }),
  createStarterPreset('starter-geometry-lattice', 'Geometry Lattice', {
      viewMode: 'orthographic',
      cameraControlMode: 'manual',
      renderQuality: 'balanced',
      layer1Count: 16000,
      layer2Type: 'lattice',
      layer2Source: 'grid',
      layer2Count: 24000,
      layer2FlowAmplitude: 42,
      layer2ConnectionEnabled: true,
      layer2ConnectionDistance: 26,
      layer2ConnectionOpacity: 0.22,
      layer3Enabled: true,
      layer3Type: 'crystal',
      layer3Source: 'cube',
      layer3Count: 7000,
      screenScanlineIntensity: 0.12,
    }),
  createStarterPreset('starter-ripple-broadcast', 'Ripple Broadcast', {
      layer2Type: 'ripple_ring',
      layer2Source: 'disc',
      layer2Count: 22000,
      layer2FlowAmplitude: 74,
      layer2FlowFrequency: 4.2,
      screenScanlineIntensity: 0.38,
      screenScanlineDensity: 640,
      screenNoiseIntensity: 0.12,
      screenInterferenceIntensity: 0.16,
      screenSweepIntensity: 0.18,
      screenSequenceDriveEnabled: true,
      screenSequenceDriveStrength: 0.22,
    }),
  createStarterPreset('starter-pendulum-noir', 'Pendulum Noir', {
      particleColor: 'black',
      backgroundColor: 'white',
      layer1Count: 11000,
      layer2Type: 'pendulum',
      layer2Count: 18000,
      layer2FlowAmplitude: 52,
      layer2Trail: 0.44,
      layer3Enabled: true,
      layer3Type: 'fold',
      layer3Count: 8000,
      layer3BaseSize: 0.42,
      contrast: 1.35,
      particleSoftness: 0.2,
    }),
  createStarterPreset('starter-toroidal-gyre', 'Toroidal Gyre', {
      layer1Count: 13000,
      layer2Type: 'toroidal',
      layer2Source: 'torus',
      layer2Count: 30000,
      layer2FlowAmplitude: 66,
      layer2Trail: 0.66,
      layer3Enabled: true,
      layer3Type: 'gyre',
      layer3Count: 10000,
      layer3FlowAmplitude: 58,
      layer3Trail: 0.46,
      ambientCount: 4500,
    }),
  createStarterPreset('starter-symmetry-lissajous', 'Symmetry Lissajous', {
      layer1Count: 10000,
      layer2Type: 'lissajous',
      layer2Source: 'sphere',
      layer2Count: 21000,
      layer2FlowAmplitude: 60,
      layer2FlowFrequency: 3.8,
      layer3Enabled: true,
      layer3Type: 'rose_curve',
      layer3Count: 9000,
      layer3FlowAmplitude: 40,
      screenVignetteIntensity: 0.1,
      screenPersistenceIntensity: 0.1,
    }),
  createStarterPreset('starter-aizawa-ink', 'Aizawa Ink Spiral', {
      particleColor: 'black',
      backgroundColor: 'white',
      contrast: 1.45,
      particleSoftness: 0.12,
      layer1Count: 9000,
      layer2Type: 'aizawa',
      layer2Count: 26000,
      layer2FlowAmplitude: 88,
      layer2Complexity: 3.8,
      layer2Trail: 0.34,
      layer3Enabled: true,
      layer3Type: 'helix',
      layer3Count: 7000,
      layer3FlowAmplitude: 34,
    }),
  createStarterPreset('starter-fractal-ridged', 'Fractal Ridged Storm', {
      layer1Count: 15000,
      layer2Type: 'ridged_mf',
      layer2Count: 31000,
      layer2FlowAmplitude: 78,
      layer2NoiseScale: 1.5,
      layer2OctaveMult: 2.6,
      layer2Fidelity: 4,
      layer2Trail: 0.58,
      layer3Enabled: true,
      layer3Type: 'noise',
      layer3Count: 9000,
      layer3FlowAmplitude: 46,
      screenInterferenceIntensity: 0.08,
    }),
  createStarterPreset('starter-brownian-veil', 'Brownian Veil', {
      layer1Count: 8000,
      layer2Type: 'brownian',
      layer2Source: 'plane',
      layer2Count: 19000,
      layer2FlowAmplitude: 44,
      layer2Trail: 0.2,
      layer3Enabled: true,
      layer3Type: 'smoke',
      layer3Count: 14000,
      layer3BaseSize: 0.92,
      layer3Trail: 0.18,
      ambientCount: 6500,
      screenPersistenceIntensity: 0.18,
      screenPersistenceLayers: 4,
    }),
];
