import type { PresetRecord } from '../types';
import { buildPostFxStackPatch } from './postFxLibrary';
import { createStarterPreset } from './starterLibraryCore';
export const STARTER_PRESET_EXTENSION_CHUNK_01_ATMOSPHERIC = [
  ] = [
  createStarterPreset('starter-glass-cathedral-sphere', 'Glass Cathedral Sphere', {
      layer2Enabled: true,
      layer2Type: 'surface_shell',
      layer2Source: 'sphere',
      layer2Count: 11800,
      layer2MaterialStyle: 'glass',
      layer2HullOpacity: 0.68,
      layer2HullFresnel: 0.78,
      layer2TemporalProfile: 'resonate',
      layer2TemporalStrength: 0.26,
      layer3Enabled: true,
      layer3Type: 'volume_fog',
      layer3Source: 'sphere',
      layer3MaterialStyle: 'glass',
      layer3FogOpacity: 0.22,
      layer3FogGlow: 0.24,
    }),
  createStarterPreset('starter-resin-fossil-grid', 'Resin Fossil Grid', {
      layer2Enabled: true,
      layer2Type: 'voxel_lattice',
      layer2Source: 'grid',
      layer2Count: 9800,
      layer2MaterialStyle: 'classic',
      layer2VoxelOpacity: 0.8,
      layer2VoxelSnap: 0.84,
      layer2TemporalProfile: 'condense',
      layer2TemporalStrength: 0.28,
      layer3Enabled: true,
      layer3Type: 'deposition_field',
      layer3Source: 'plane',
      layer3DepositionOpacity: 0.78,
      layer3DepositionRelief: 0.6,
    }),
  createStarterPreset('starter-hologram-script-text', 'Hologram Script Text', {
      layer2Enabled: true,
      layer2Type: 'drift_glyph_dust',
      layer2Source: 'text',
      layer2TextMapText: 'KALOKAGATHIA',
      layer2MaterialStyle: 'hologram',
      layer2TemporalProfile: 'oscillate',
      layer2TemporalStrength: 0.24,
      layer3Enabled: true,
      layer3Type: 'rune_smoke',
      layer3Source: 'text',
      layer3TextMapText: 'VARELSER',
      layer3MaterialStyle: 'hologram',
    }),
  createStarterPreset('starter-ion-video-plume', 'Ion Video Plume', {
      layer2Enabled: true,
      layer2Type: 'charge_veil',
      layer2Source: 'video',
      layer2MaterialStyle: 'hologram',
      layer2TemporalProfile: 'ignite',
      layer2TemporalStrength: 0.34,
      layer2FogOpacity: 0.3,
      layer2FogGlow: 0.34,
      layer3Enabled: true,
      layer3Type: 'prism_smoke',
      layer3Source: 'video',
      layer3MaterialStyle: 'hologram',
    }),
  createStarterPreset('starter-ash-image-relief', 'Ash Image Relief', {
      layer2Enabled: true,
      layer2Type: 'sigil_dust',
      layer2Source: 'image',
      layer2MaterialStyle: 'halftone',
      layer2DepositionOpacity: 0.72,
      layer2DepositionErosion: 0.28,
      layer2TemporalProfile: 'shed',
      layer3Enabled: true,
      layer3Type: 'velvet_ash',
      layer3Source: 'image',
      layer3MaterialStyle: 'halftone',
    }),
  createStarterPreset('starter-cylinder-thread-prism', 'Cylinder Thread Prism', {
      layer2Enabled: true,
      layer2Type: 'prism_threads',
      layer2Source: 'cylinder',
      layer2MaterialStyle: 'chrome',
      layer2FiberLength: 1.02,
      layer2FiberDensity: 0.62,
      layer2TemporalProfile: 'resonate',
      layer3Enabled: true,
      layer3Type: 'signal_braid',
      layer3Source: 'cylinder',
      layer3MaterialStyle: 'chrome',
    }),
  createStarterPreset('starter-ring-halo-thread', 'Ring Halo Thread', {
      layer2Enabled: true,
      layer2Type: 'eclipse_halo',
      layer2Source: 'ring',
      layer2MaterialStyle: 'glass',
      layer2TemporalProfile: 'oscillate',
      layer3Enabled: true,
      layer3Type: 'aurora_threads',
      layer3Source: 'ring',
      layer3MaterialStyle: 'hologram',
    }),
  createStarterPreset('starter-grid-shell-script', 'Grid Shell Script', {
      layer2Enabled: true,
      layer2Type: 'shell_script',
      layer2Source: 'grid',
      layer2MaterialStyle: 'classic',
      layer2PatchOpacity: 0.76,
      layer2TemporalProfile: 'unravel',
      layer3Enabled: true,
      layer3Type: 'lattice_surge',
      layer3Source: 'grid',
      layer3MaterialStyle: 'chrome',
    }),
  createStarterPreset('starter-text-pollen-script', 'Text Pollen Script', {
      layer2Enabled: true,
      layer2Type: 'pollen_lattice',
      layer2Source: 'text',
      layer2TextMapText: '慈愛',
      layer2MaterialStyle: 'glass',
      layer2TemporalProfile: 'accrete',
      layer3Enabled: true,
      layer3Type: 'pollen_storm',
      layer3Source: 'text',
      layer3TextMapText: '体系',
      layer3MaterialStyle: 'glass',
    }),
  createStarterPreset('starter-plane-velvet-manuscript', 'Plane Velvet Manuscript', {
      layer2Enabled: true,
      layer2Type: 'ink_bleed',
      layer2Source: 'plane',
      layer2MaterialStyle: 'halftone',
      layer2TemporalProfile: 'evaporate',
      layer3Enabled: true,
      layer3Type: 'velvet_ash',
      layer3Source: 'plane',
      layer3MaterialStyle: 'halftone',
    })
];
