import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_BASE_CHUNK_04_CORE_RELICS: PresetRecord[] = [
  createStarterPreset('starter-membrane-pollen-orbit', 'Membrane Pollen Orbit', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'membrane_pollen',
        layer2Source: 'sphere',
        layer2Count: 6200,
        layer2TemporalProfile: 'growth',
        layer3Enabled: true,
        layer3Type: 'orbit_fracture',
        layer3Source: 'ring',
        layer3Count: 3200,
        layer3TemporalProfile: 'rupture',
        postBloomEnabled: true,
        postBloomIntensity: 0.42,
      }),
  createStarterPreset('starter-spectral-mesh-lattice', 'Spectral Mesh Lattice', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'spectral_mesh',
        layer2Source: 'text',
        layer2TextMapText: 'GRID',
        layer2Count: 8200,
        layer2FiberDensity: 164,
        layer2FlowAmplitude: 34,
        layer3Enabled: true,
        layer3Type: 'calcified_skin',
        layer3Source: 'sphere',
        layer3Count: 4200,
        layer3TemporalProfile: 'growth',
      }),
  createStarterPreset('starter-rune-smoke-script', 'Rune Smoke Script', {
        cameraControlMode: 'hybrid',
        renderQuality: 'cinematic',
        layer2Enabled: true,
        layer2Type: 'rune_smoke',
        layer2Source: 'text',
        layer2TextMapText: 'SIGIL',
        layer2Count: 9000,
        layer2FogDensity: 0.72,
        layer2TemporalProfile: 'decay',
        layer3Enabled: true,
        layer3Type: 'drift_glyph_dust',
        layer3Source: 'text',
        layer3TextMapText: 'RUNE',
        layer3Count: 3800,
        layer3TemporalProfile: 'decay',
      }),
  createStarterPreset('starter-spore-halo-bloom', 'Spore Halo Bloom', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'spore_halo',
        layer2Source: 'ring',
        layer2Count: 6400,
        layer2TemporalProfile: 'growth',
        layer3Enabled: true,
        layer3Type: 'membrane_pollen',
        layer3Source: 'sphere',
        layer3Count: 3600,
        layer3TemporalProfile: 'crystallize',
        postBloomEnabled: true,
        postBloomIntensity: 0.4,
      }),
  createStarterPreset('starter-aurora-thread-mirage', 'Aurora Thread Mirage', {
        cameraControlMode: 'hybrid',
        renderQuality: 'cinematic',
        layer2Enabled: true,
        layer2Type: 'aurora_threads',
        layer2Source: 'ring',
        layer2Count: 8600,
        layer2FiberDensity: 172,
        layer2TemporalProfile: 'oscillate',
        layer3Enabled: true,
        layer3Type: 'mirage_smoke',
        layer3Source: 'sphere',
        layer3Count: 4200,
        layer3FogDensity: 0.7,
        layer3TemporalProfile: 'evaporate',
        postBloomEnabled: true,
        postBloomIntensity: 0.44,
      }),
  createStarterPreset('starter-residue-sigil-reliquary', 'Residue Sigil Reliquary', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'residue_skin',
        layer2Source: 'cube',
        layer2Count: 6200,
        layer2TemporalProfile: 'shed',
        layer3Enabled: true,
        layer3Type: 'sigil_dust',
        layer3Source: 'text',
        layer3TextMapText: 'RELIC',
        layer3Count: 3600,
        layer3TemporalProfile: 'accrete',
      }),
  createStarterPreset('starter-frost-lattice-script', 'Frost Lattice Script', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'frost_lattice',
        layer2Source: 'sphere',
        layer2Count: 7600,
        layer2TemporalProfile: 'crystallize',
        layer3Enabled: true,
        layer3Type: 'sigil_dust',
        layer3Source: 'text',
        layer3TextMapText: 'FROST',
        layer3Count: 3400,
        layer3TemporalProfile: 'shed',
      }),
  createStarterPreset('starter-thread-smoke-reverie', 'Thread Smoke Reverie', {
        layer2Type: 'aurora_threads',
        layer2TemporalProfile: 'oscillate',
        layer2TemporalStrength: 0.72,
        layer3Enabled: true,
        layer3Type: 'mirage_smoke',
        layer3TemporalProfile: 'evaporate',
        layer3TemporalStrength: 0.66,
        layer3FogOpacity: 0.72,
        layer2FiberLength: 1.3,
      }),
];
