import type { PresetRecord } from '../types';
import { buildPostFxStackPatch } from './postFxLibrary';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_EXTENSION_CHUNK_02_TEXT_VIDEO_STUDIES: PresetRecord[] = [
  createStarterPreset('starter-text-glyph-weave-codex', 'Text Glyph Weave Codex', {
        layer2Enabled: true,
        layer2Type: 'glyph_weave',
        layer2Source: 'text',
        layer2TextMapText: 'VARELSER',
        layer2TextMapSize: 300,
        layer2MaterialStyle: 'hologram',
        layer2TemporalProfile: 'oscillate',
        layer2TemporalStrength: 0.28,
        layer2FiberOpacity: 0.82,
        layer2FiberLength: 0.94,
        layer2FiberDensity: 0.76,
        layer2FiberCurl: 0.18,
        layer2ConnectionEnabled: true,
        layer2ConnectionStyle: 'filament',
        layer2ConnectionWidth: 0.9,
        layer2ConnectionOpacity: 0.18,
        layer2GlyphOutlineEnabled: true,
        layer2GlyphOutlineWidth: 1.48,
        layer2GlyphOutlineOpacity: 0.62,
        layer3Enabled: true,
        layer3Type: 'contour_echo',
        layer3Source: 'text',
        layer3TextMapText: '慈愛体系',
        layer3TextMapSize: 292,
        layer3MaterialStyle: 'chrome',
        layer3TemporalProfile: 'resonate',
        layer3TemporalStrength: 0.24,
        layer3PatchResolution: 58,
        layer3PatchRelax: 0.18,
        layer3PatchFresnel: 0.68,
        layer3GlyphOutlineEnabled: true,
        layer3GlyphOutlineWidth: 1.38,
        layer3GlyphOutlineOpacity: 0.44,
      }),
  createStarterPreset('starter-text-glyph-weave-palimpsest', 'Text Glyph Weave Palimpsest', {
        layer2Enabled: true,
        layer2Type: 'shell_script',
        layer2Source: 'text',
        layer2TextMapText: 'VARELSER',
        layer2MaterialStyle: 'classic',
        layer2TemporalProfile: 'unravel',
        layer2TemporalStrength: 0.24,
        layer2HullOpacity: 0.82,
        layer2HullFresnel: 0.74,
        layer2HullPointBudget: 1320,
        layer3Enabled: true,
        layer3Type: 'glyph_weave',
        layer3Source: 'text',
        layer3TextMapText: '慈愛体系',
        layer3TextMapSize: 304,
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'oscillate',
        layer3TemporalStrength: 0.26,
        layer3FiberOpacity: 0.78,
        layer3FiberLength: 0.9,
        layer3FiberDensity: 0.74,
        layer3FiberCurl: 0.2,
        layer3ConnectionEnabled: true,
        layer3ConnectionStyle: 'filament',
        layer3ConnectionWidth: 0.88,
        layer3ConnectionOpacity: 0.16,
        layer3GlyphOutlineEnabled: true,
        layer3GlyphOutlineWidth: 1.42,
        layer3GlyphOutlineOpacity: 0.58,
      }),
  createStarterPreset('starter-grid-stipple-ledger', 'Grid Stipple Ledger', {
        layer2Enabled: true,
        layer2Type: 'stipple_field',
        layer2Source: 'grid',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'accrete',
        layer2TemporalStrength: 0.22,
        layer2DepositionOpacity: 0.82,
        layer2DepositionRelief: 0.56,
        layer2DepositionErosion: 0.26,
        layer2DepositionBands: 7,
        layer3Enabled: true,
        layer3Type: 'static_lace',
        layer3Source: 'grid',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'oscillate',
        layer3TemporalStrength: 0.22,
        layer3LineVelocityGlow: 0.68,
        layer3LineVelocityAlpha: 0.28,
        layer3LineBurstPulse: 0.2,
        layer3LineShimmer: 0.24,
        layer3LineFlickerSpeed: 1.44,
        layer3FiberOpacity: 0.7,
        layer3FiberLength: 0.9,
        layer3FiberDensity: 0.68,
        layer3FiberCurl: 0.14,
      }),
  createStarterPreset('starter-grid-stipple-calcify', 'Grid Stipple Calcify', {
        layer2Enabled: true,
        layer2Type: 'calcified_skin',
        layer2Source: 'grid',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'steady',
        layer2HullOpacity: 0.8,
        layer2HullFresnel: 0.48,
        layer2HullJitter: 0.05,
        layer3Enabled: true,
        layer3Type: 'stipple_field',
        layer3Source: 'grid',
        layer3MaterialStyle: 'halftone',
        layer3TemporalProfile: 'accrete',
        layer3TemporalStrength: 0.2,
        layer3DepositionOpacity: 0.8,
        layer3DepositionRelief: 0.54,
        layer3DepositionErosion: 0.3,
        layer3DepositionBands: 8,
      }),
  createStarterPreset('starter-contour-plate-echo', 'Contour Plate Echo', {
        layer2Enabled: true,
        layer2Type: 'contour_echo',
        layer2Source: 'plane',
        layer2MaterialStyle: 'chrome',
        layer2TemporalProfile: 'resonate',
        layer2PatchResolution: 56,
        layer2PatchRelax: 0.22,
        layer3Enabled: true,
        layer3Type: 'echo_rings',
        layer3Source: 'ring',
        layer3MaterialStyle: 'glass',
      }),
  createStarterPreset('starter-ember-drift-manuscript', 'Ember Drift Manuscript', {
        layer2Enabled: true,
        layer2Type: 'ember_drift',
        layer2Source: 'text',
        layer2MaterialStyle: 'hologram',
        layer2TemporalProfile: 'shed',
        layer2FogOpacity: 0.66,
        layer2FogDensity: 0.5,
        layer2FogScale: 1.06,
        layer3Enabled: true,
        layer3Type: 'shell_script',
        layer3Source: 'text',
        layer3MaterialStyle: 'hologram',
      }),
  createStarterPreset('starter-ion-rain-video', 'Ion Rain Video Veil', {
        layer2Enabled: true,
        layer2Type: 'ion_rain',
        layer2Source: 'video',
        layer2MaterialStyle: 'glass',
        layer2TemporalProfile: 'shed',
        layer2FogOpacity: 0.62,
        layer2FogDensity: 0.54,
        layer2FogSlices: 18,
        layer3Enabled: true,
        layer3Type: 'charge_veil',
        layer3Source: 'video',
        layer3MaterialStyle: 'hologram',
      }),
  createStarterPreset('starter-mesh-weave-cylinder', 'Mesh Weave Cylinder', {
        layer2Enabled: true,
        layer2Type: 'mesh_weave',
        layer2Source: 'cylinder',
        layer2MaterialStyle: 'classic',
        layer2TemporalProfile: 'resonate',
        layer2FiberLength: 0.92,
        layer2FiberDensity: 0.62,
        layer3Enabled: true,
        layer3Type: 'spectral_mesh',
        layer3Source: 'cylinder',
        layer3MaterialStyle: 'chrome',
      }),
  createStarterPreset('starter-ribbon-veil-ring', 'Ribbon Veil Ring', {
        layer2Enabled: true,
        layer2Type: 'ribbon_veil',
        layer2Source: 'ring',
        layer2MaterialStyle: 'glass',
        layer2TemporalProfile: 'oscillate',
        layer3Enabled: true,
        layer3Type: 'mist_ribbon',
        layer3Source: 'ring',
        layer3MaterialStyle: 'glass',
      }),
];
