import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_BASE_CHUNK_04_RITUAL_RELICS: PresetRecord[] = [
  createStarterPreset('starter-prismatic-storm-breathing', 'Prismatic Storm Breathing', {
        renderQuality: 'cinematic',
        layer1Count: 3200,
        layer2Enabled: true,
        layer2Type: 'charge_veil',
        layer2Source: 'ring',
        layer2Count: 7200,
        layer2MaterialStyle: 'hologram',
        layer2FogOpacity: 0.24,
        layer2FogDensity: 0.34,
        layer2FogScale: 1.22,
        layer2FogDrift: 0.42,
        layer2FogGlow: 0.42,
        layer2TemporalProfile: 'oscillate',
        layer2TemporalStrength: 0.46,
        layer2TemporalSpeed: 0.88,
        layer3Enabled: true,
        layer3Type: 'prism_smoke',
        layer3Source: 'cube',
        layer3Count: 5200,
        layer3MaterialStyle: 'glass',
        layer3FogOpacity: 0.18,
        layer3FogDensity: 0.3,
        layer3FogScale: 1.44,
        layer3FogDrift: 0.22,
        layer3FogGlow: 0.26,
        layer3TemporalProfile: 'evaporate',
        layer3TemporalStrength: 0.42,
        layer3TemporalSpeed: 0.82,
        depthFogEnabled: true,
      }),
  createStarterPreset('starter-ash-script-shedding', 'Ash Script Shedding', {
        viewMode: 'orthographic',
        renderQuality: 'balanced',
        layer1Count: 3400,
        layer2Enabled: true,
        layer2Type: 'soot_veil',
        layer2Source: 'text',
        layer2TextMapText: 'ASH',
        layer2Count: 8800,
        layer2MaterialStyle: 'halftone',
        layer2FogOpacity: 0.16,
        layer2FogDensity: 0.44,
        layer2FogScale: 0.9,
        layer2FogDrift: 0.1,
        layer2TemporalProfile: 'shed',
        layer2TemporalStrength: 0.52,
        layer2TemporalSpeed: 0.7,
        layer3Enabled: true,
        layer3Type: 'sigil_dust',
        layer3Source: 'text',
        layer3TextMapText: 'ASH',
        layer3Count: 4600,
        layer3MaterialStyle: 'halftone',
        layer3DepositionOpacity: 0.54,
        layer3DepositionRelief: 0.34,
        layer3DepositionErosion: 0.74,
        layer3DepositionBands: 7,
        layer3TemporalProfile: 'decay',
        layer3TemporalStrength: 0.5,
        layer3TemporalSpeed: 0.8,
        layer3GlyphOutlineEnabled: true,
      }),
  createStarterPreset('starter-veil-lattice-accretion', 'Veil Lattice Accretion', {
        renderQuality: 'cinematic',
        layer1Count: 3600,
        layer2Enabled: true,
        layer2Type: 'mist_ribbon',
        layer2Source: 'spiral',
        layer2Count: 7600,
        layer2MaterialStyle: 'glass',
        layer2BrushOpacity: 0.28,
        layer2BrushLayers: 6,
        layer2BrushJitter: 0.18,
        layer2TemporalProfile: 'oscillate',
        layer2TemporalStrength: 0.38,
        layer2TemporalSpeed: 0.74,
        layer3Enabled: true,
        layer3Type: 'frost_lattice',
        layer3Source: 'cube',
        layer3Count: 5200,
        layer3MaterialStyle: 'chrome',
        layer3VoxelOpacity: 0.34,
        layer3VoxelScale: 0.74,
        layer3VoxelDensity: 0.22,
        layer3TemporalProfile: 'accrete',
        layer3TemporalStrength: 0.44,
        layer3TemporalSpeed: 0.68,
        depthFogEnabled: true,
      }),
  createStarterPreset('starter-runic-smoke-evaporation', 'Runic Smoke Evaporation', {
        renderQuality: 'balanced',
        layer1Count: 3000,
        layer2Enabled: true,
        layer2Type: 'rune_smoke',
        layer2Source: 'text',
        layer2TextMapText: 'RUNE',
        layer2Count: 7000,
        layer2MaterialStyle: 'hologram',
        layer2FogOpacity: 0.18,
        layer2FogDensity: 0.36,
        layer2FogScale: 1.1,
        layer2FogDrift: 0.18,
        layer2TemporalProfile: 'evaporate',
        layer2TemporalStrength: 0.5,
        layer2TemporalSpeed: 0.86,
        layer3Enabled: true,
        layer3Type: 'drift_glyph_dust',
        layer3Source: 'text',
        layer3TextMapText: 'RUNE',
        layer3Count: 4200,
        layer3DepositionOpacity: 0.52,
        layer3DepositionRelief: 0.3,
        layer3DepositionErosion: 0.68,
        layer3DepositionBands: 6,
        layer3TemporalProfile: 'decay',
        layer3TemporalStrength: 0.46,
        layer3TemporalSpeed: 0.78,
        layer3GlyphOutlineEnabled: true,
      }),
  createStarterPreset('starter-pollen-shell-shedding', 'Pollen Shell Shedding', {
        renderQuality: 'cinematic',
        layer1Count: 3800,
        layer2Enabled: true,
        layer2Type: 'spore_halo',
        layer2Source: 'sphere',
        layer2Count: 6400,
        layer2MaterialStyle: 'glass',
        layer2HullOpacity: 0.24,
        layer2HullFresnel: 0.92,
        layer2TemporalProfile: 'shed',
        layer2TemporalStrength: 0.36,
        layer2TemporalSpeed: 0.72,
        layer3Enabled: true,
        layer3Type: 'membrane_pollen',
        layer3Source: 'sphere',
        layer3Count: 5200,
        layer3MaterialStyle: 'chrome',
        layer3HullOpacity: 0.2,
        layer3HullFresnel: 0.82,
        layer3TemporalProfile: 'growth',
        layer3TemporalStrength: 0.4,
        layer3TemporalSpeed: 0.64,
      }),
  createStarterPreset('starter-halo-bloom-equinox', 'Halo Bloom Equinox', {
        renderQuality: 'cinematic',
        layer1Count: 2800,
        layer2Enabled: true,
        layer2Type: 'halo_bloom',
        layer2Source: 'ring',
        layer2Count: 8400,
        layer2MaterialStyle: 'hologram',
        layer2HullOpacity: 0.82,
        layer2HullFresnel: 0.96,
        layer2HullPointBudget: 1600,
        layer2HullJitter: 0.1,
        layer2TemporalProfile: 'oscillate',
        layer2TemporalStrength: 0.32,
        layer2TemporalSpeed: 0.94,
        depthFogEnabled: true,
        particleGlow: 0.42,
      }),
  createStarterPreset('starter-membrane-pollen-herbarium', 'Membrane Pollen Herbarium', {
        renderQuality: 'cinematic',
        layer1Count: 3200,
        layer2Enabled: true,
        layer2Type: 'membrane_pollen',
        layer2Source: 'image',
        layer2Count: 9200,
        layer2MaterialStyle: 'glass',
        layer2HullOpacity: 0.78,
        layer2HullFresnel: 0.84,
        layer2HullPointBudget: 1480,
        layer2HullJitter: 0.12,
        layer2TemporalProfile: 'accrete',
        layer2TemporalStrength: 0.24,
        layer2TemporalSpeed: 0.76,
        depthFogEnabled: true,
        particleGlow: 0.22,
      }),
  createStarterPreset('starter-spore-halo-reliquary', 'Spore Halo Reliquary', {
        renderQuality: 'cinematic',
        layer1Count: 3000,
        layer2Enabled: true,
        layer2Type: 'spore_halo',
        layer2Source: 'sphere',
        layer2Count: 8800,
        layer2MaterialStyle: 'hologram',
        layer2HullOpacity: 0.74,
        layer2HullFresnel: 0.94,
        layer2HullPointBudget: 1520,
        layer2HullJitter: 0.1,
        layer2TemporalProfile: 'shed',
        layer2TemporalStrength: 0.28,
        layer2TemporalSpeed: 0.84,
        layer3Enabled: true,
        layer3Type: 'membrane_pollen',
        layer3Source: 'sphere',
        layer3Count: 5400,
        layer3MaterialStyle: 'glass',
        layer3HullOpacity: 0.24,
        layer3HullFresnel: 0.82,
        layer3TemporalProfile: 'growth',
        layer3TemporalStrength: 0.34,
        layer3TemporalSpeed: 0.7,
        particleGlow: 0.34,
      }),
];
