import type { PresetRecord } from '../types';
import { buildPostFxStackPatch } from './postFxLibrary';
import { createStarterPreset } from './starterLibraryCore';
export const STARTER_PRESET_EXTENSION_CHUNK_01_ATLAS = [
  createStarterPreset('starter-atlas-glass-halo-orbit', 'Glass Halo Orbit', {
      layer2Enabled: true,
      layer2Type: 'eclipse_halo',
      layer2Source: 'ring',
      layer2MaterialStyle: 'glass',
      layer2TemporalProfile: 'oscillate',
      layer2TemporalStrength: 0.24,
      layer2HullOpacity: 0.68,
      layer2HullFresnel: 0.82,
      layer3Enabled: true,
      layer3Type: 'orbit_swarm',
      layer3Source: 'ring',
      layer3MaterialStyle: 'glass',
    }),
  createStarterPreset('starter-atlas-resin-lattice-grid', 'Resin Lattice Grid', {
      layer2Enabled: true,
      layer2Type: 'frost_lattice',
      layer2Source: 'grid',
      layer2MaterialStyle: 'classic',
      layer2TemporalProfile: 'condense',
      layer2VoxelOpacity: 0.78,
      layer2VoxelSnap: 0.84,
      layer3Enabled: true,
      layer3Type: 'lattice_surge',
      layer3Source: 'grid',
      layer3MaterialStyle: 'chrome',
    }),
  createStarterPreset('starter-atlas-ash-rune-plane', 'Ash Rune Plane', {
      layer2Enabled: true,
      layer2Type: 'sigil_dust',
      layer2Source: 'plane',
      layer2MaterialStyle: 'halftone',
      layer2TemporalProfile: 'evaporate',
      layer2DepositionOpacity: 0.72,
      layer3Enabled: true,
      layer3Type: 'rune_smoke',
      layer3Source: 'plane',
      layer3MaterialStyle: 'halftone',
    }),
  createStarterPreset('starter-atlas-ion-prism-video', 'Ion Prism Video', {
      layer2Enabled: true,
      layer2Type: 'prism_smoke',
      layer2Source: 'video',
      layer2MaterialStyle: 'hologram',
      layer2TemporalProfile: 'ignite',
      layer2FogGlow: 0.34,
      layer3Enabled: true,
      layer3Type: 'charge_veil',
      layer3Source: 'video',
      layer3MaterialStyle: 'hologram',
    }),
  createStarterPreset('starter-atlas-script-text-hologram', 'Script Text Hologram', {
      layer2Enabled: true,
      layer2Type: 'shell_script',
      layer2Source: 'text',
      layer2TextMapText: 'VARELSER',
      layer2MaterialStyle: 'hologram',
      layer2TemporalProfile: 'unravel',
      layer3Enabled: true,
      layer3Type: 'glyph_weave',
      layer3Source: 'text',
      layer3TextMapText: '慈愛体系',
      layer3MaterialStyle: 'hologram',
    }),
  createStarterPreset('starter-atlas-image-relief-fossil', 'Image Relief Fossil', {
      layer2Enabled: true,
      layer2Type: 'deposition_field',
      layer2Source: 'image',
      layer2MaterialStyle: 'classic',
      layer2TemporalProfile: 'accrete',
      layer2DepositionRelief: 0.62,
      layer3Enabled: true,
      layer3Type: 'resin_shell',
      layer3Source: 'image',
      layer3MaterialStyle: 'classic',
    }),
  createStarterPreset('starter-atlas-cylinder-braid-spectral', 'Cylinder Braid Spectral', {
      layer2Enabled: true,
      layer2Type: 'spectral_mesh',
      layer2Source: 'cylinder',
      layer2MaterialStyle: 'chrome',
      layer2TemporalProfile: 'resonate',
      layer2FiberLength: 1.08,
      layer3Enabled: true,
      layer3Type: 'signal_braid',
      layer3Source: 'cylinder',
      layer3MaterialStyle: 'chrome',
    }),
  createStarterPreset('starter-atlas-sphere-crystal-bloom', 'Sphere Crystal Bloom', {
      layer2Enabled: true,
      layer2Type: 'crystal_aggregate',
      layer2Source: 'sphere',
      layer2MaterialStyle: 'chrome',
      layer2TemporalProfile: 'crystallize',
      layer2CrystalScale: 1.24,
      layer3Enabled: true,
      layer3Type: 'fracture_bloom',
      layer3Source: 'sphere',
      layer3MaterialStyle: 'chrome',
    }),
  createStarterPreset('starter-atlas-video-mirage-smoke', 'Video Mirage Smoke', {
      layer2Enabled: true,
      layer2Type: 'mirage_smoke',
      layer2Source: 'video',
      layer2MaterialStyle: 'hologram',
      layer2TemporalProfile: 'evaporate',
      layer3Enabled: true,
      layer3Type: 'static_smoke',
      layer3Source: 'video',
      layer3MaterialStyle: 'hologram',
    }),
  createStarterPreset('starter-atlas-grid-shell-script', 'Grid Shell Script', {
      layer2Enabled: true,
      layer2Type: 'shell_script',
      layer2Source: 'grid',
      layer2MaterialStyle: 'classic',
      layer2TemporalProfile: 'unravel',
      layer3Enabled: true,
      layer3Type: 'lattice_surge',
      layer3Source: 'grid',
      layer3MaterialStyle: 'chrome',
    }),
  createStarterPreset('starter-atlas-ring-thread-halo', 'Ring Thread Halo', {
      layer2Enabled: true,
      layer2Type: 'aurora_threads',
      layer2Source: 'ring',
      layer2MaterialStyle: 'hologram',
      layer2TemporalProfile: 'resonate',
      layer3Enabled: true,
      layer3Type: 'eclipse_halo',
      layer3Source: 'ring',
      layer3MaterialStyle: 'glass',
    }),
  createStarterPreset('starter-atlas-plane-velvet-manuscript', 'Plane Velvet Manuscript', {
      layer2Enabled: true,
      layer2Type: 'velvet_ash',
      layer2Source: 'plane',
      layer2MaterialStyle: 'halftone',
      layer2TemporalProfile: 'shed',
      layer3Enabled: true,
      layer3Type: 'ink_bleed',
      layer3Source: 'plane',
      layer3MaterialStyle: 'halftone',
    })
];
