import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_BASE_CHUNK_03_EVENT_STUDIES: PresetRecord[] = [
  createStarterPreset('starter-tremor-lattice-chamber', 'Tremor Lattice Chamber', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'tremor_lattice',
        layer2Source: 'grid',
        layer2Count: 11000,
        layer2FlowAmplitude: 42,
        layer2FlowFrequency: 2.3,
        layer2Trail: 0.18,
        layer3Enabled: true,
        layer3Type: 'mirror_skin',
        layer3Source: 'sphere',
        layer3Count: 3400,
        layer3BaseSize: 0.85,
        postBloomEnabled: true,
        postBloomIntensity: 0.46,
      }),
  createStarterPreset('starter-bloom-torrent-spores', 'Bloom Torrent Spores', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'bloom_torrent',
        layer2Source: 'cone',
        layer2Count: 14000,
        layer2FlowAmplitude: 58,
        layer2FlowFrequency: 1.9,
        layer2Trail: 0.42,
        layer3Enabled: true,
        layer3Type: 'bloom_spores',
        layer3Source: 'sphere',
        layer3Count: 4200,
        layer3BaseSize: 0.74,
        postBloomEnabled: true,
        postBloomIntensity: 0.58,
      }),
  createStarterPreset('starter-orbit-fracture-reliquary', 'Orbit Fracture Reliquary', {
        cameraControlMode: 'hybrid',
        renderQuality: 'cinematic',
        layer2Enabled: true,
        layer2Type: 'orbit_fracture',
        layer2Source: 'ring',
        layer2Count: 7600,
        layer2FlowAmplitude: 36,
        layer2FlowFrequency: 2.8,
        layer2Trail: 0.34,
        layer3Enabled: true,
        layer3Type: 'mirror_skin',
        layer3Source: 'text',
        layer3TextMapText: 'RIFT',
        layer3Count: 2600,
        layer3BaseSize: 0.9,
      }),
  createStarterPreset('starter-foam-soot-sanctuary', 'Foam Soot Sanctuary', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'foam_drift',
        layer2Source: 'plane',
        layer2Count: 9800,
        layer2BaseSize: 0.8,
        layer2FlowAmplitude: 32,
        layer2FlowFrequency: 1.4,
        layer3Enabled: true,
        layer3Type: 'soot_veil',
        layer3Source: 'cube',
        layer3Count: 3600,
        layer3BaseSize: 1.1,
        depthFogEnabled: true,
        depthFogNear: 420,
        depthFogFar: 2200,
      }),
  createStarterPreset('starter-signal-nerve-atlas', 'Signal Nerve Atlas', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'signal_braid',
        layer2Source: 'text',
        layer2TextMapText: 'AXON',
        layer2Count: 9000,
        layer2FlowAmplitude: 40,
        layer2FlowFrequency: 2.6,
        layer3Enabled: true,
        layer3Type: 'nerve_web',
        layer3Source: 'image',
        layer3Count: 3800,
        layer3BaseSize: 0.68,
      }),
  createStarterPreset('starter-pollen-storm-vault', 'Pollen Storm Vault', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'pollen_storm',
        layer2Source: 'sphere',
        layer2Count: 5200,
        layer2BaseSize: 0.72,
        layer2FlowAmplitude: 46,
        layer2FlowFrequency: 1.8,
        layer3Enabled: true,
        layer3Type: 'soot_veil',
        layer3Source: 'plane',
        layer3Count: 3000,
        layer3BaseSize: 1.0,
        postBloomEnabled: true,
        postBloomIntensity: 0.34,
      }),
  createStarterPreset('starter-charge-veil-nimbus', 'Charge Veil Nimbus', {
        cameraControlMode: 'hybrid',
        renderQuality: 'cinematic',
        layer2Enabled: true,
        layer2Type: 'charge_veil',
        layer2Source: 'text',
        layer2TextMapText: 'ION',
        layer2Count: 9600,
        layer2FogDensity: 0.68,
        layer2FogGlow: 0.82,
        layer2TemporalProfile: 'rupture',
        layer3Enabled: true,
        layer3Type: 'prism_smoke',
        layer3Source: 'cube',
        layer3Count: 4200,
        layer3FogDensity: 0.74,
        layer3TemporalProfile: 'melt',
      }),
  createStarterPreset('starter-cinder-web-script', 'Cinder Web Script', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'cinder_web',
        layer2Source: 'image',
        layer2Count: 8800,
        layer2FiberDensity: 156,
        layer2FiberLength: 0.42,
        layer3Enabled: true,
        layer3Type: 'drift_glyph_dust',
        layer3Source: 'text',
        layer3TextMapText: 'ASH',
        layer3Count: 3600,
        layer3DepositionBands: 10,
        layer3TemporalProfile: 'decay',
      }),
];
