import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_BASE_CHUNK_03_FIELD_STUDIES: PresetRecord[] = [
  createStarterPreset('starter-mist-ribbon-manuscript', 'Mist Ribbon Manuscript', {
        viewMode: 'orthographic',
        renderQuality: 'balanced',
        layer1Count: 2400,
        layer2Enabled: true,
        layer2Type: 'mist_ribbon',
        layer2Source: 'text',
        layer2TextMapText: 'MIST',
        layer2Count: 7000,
        layer2MaterialStyle: 'glass',
        layer2BrushOpacity: 0.26,
        layer2BrushLayers: 6,
        layer2BrushJitter: 0.18,
        layer2TemporalProfile: 'melt',
        layer2TemporalStrength: 0.36,
        layer2TemporalSpeed: 0.82,
        depthFogEnabled: true,
      }),
  createStarterPreset('starter-hybrid-plasma-skin-carapace', 'Hybrid Plasma Skin Carapace', {
        renderQuality: 'cinematic',
        layer1Count: 3200,
        layer2Enabled: true,
        layer2Type: 'plasma_thread',
        layer2Source: 'spiral',
        layer2Count: 8200,
        layer2MaterialStyle: 'hologram',
        layer2TemporalProfile: 'rupture',
        layer2TemporalStrength: 0.46,
        layer2TemporalSpeed: 0.94,
        layer3Enabled: true,
        layer3Type: 'skin_lattice',
        layer3Source: 'sphere',
        layer3Count: 9000,
        layer3MaterialStyle: 'chrome',
        layer3TemporalProfile: 'growth',
        layer3TemporalStrength: 0.38,
        layer3TemporalSpeed: 0.66,
        particleGlow: 0.38,
      }),
  createStarterPreset('starter-hybrid-ash-echo-falloff', 'Hybrid Ash Echo Falloff', {
        renderQuality: 'balanced',
        layer1Count: 2600,
        layer2Enabled: true,
        layer2Type: 'ashfall',
        layer2Source: 'cube',
        layer2Count: 6800,
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'decay',
        layer2TemporalStrength: 0.44,
        layer2TemporalSpeed: 0.74,
        layer3Enabled: true,
        layer3Type: 'echo_rings',
        layer3Source: 'text',
        layer3TextMapText: 'ASH',
        layer3Count: 6400,
        layer3MaterialStyle: 'glass',
        layer3TemporalProfile: 'rupture',
        layer3TemporalStrength: 0.24,
        layer3TemporalSpeed: 1.06,
        depthFogEnabled: true,
      }),
  createStarterPreset('starter-hybrid-mist-inscription-drift', 'Hybrid Mist Inscription Drift', {
        renderQuality: 'balanced',
        layer1Count: 2800,
        layer2Enabled: true,
        layer2Type: 'mist_ribbon',
        layer2Source: 'text',
        layer2TextMapText: 'SIGN',
        layer2Count: 7200,
        layer2MaterialStyle: 'glass',
        layer2TemporalProfile: 'melt',
        layer2TemporalStrength: 0.34,
        layer2TemporalSpeed: 0.88,
        layer3Enabled: true,
        layer3Type: 'ink_bleed',
        layer3Source: 'text',
        layer3TextMapText: 'SIGN',
        layer3Count: 7600,
        layer3MaterialStyle: 'halftone',
        layer3TemporalProfile: 'decay',
        layer3TemporalStrength: 0.28,
        layer3TemporalSpeed: 0.82,
      }),
  createStarterPreset('starter-flock-drift-choir', 'Flock Drift Choir', {
        layer1Count: 9000,
        layer2Type: 'flock_drift',
        layer2Source: 'sphere',
        layer2Count: 26000,
        layer2FlowAmplitude: 58,
        layer2Trail: 0.34,
        layer3Enabled: true,
        layer3Type: 'ember_swarm',
        layer3Source: 'cone',
        layer3Count: 7000,
        layer3FlowAmplitude: 44,
        particleGlow: 0.36,
        postBloomEnabled: true,
      }),
  createStarterPreset('starter-vortex-sheet-gate', 'Vortex Sheet Gate', {
        layer2Type: 'vortex_sheet',
        layer2Source: 'disc',
        layer2Count: 18000,
        layer2BrushLayers: 10,
        layer2BrushScale: 1.25,
        layer2BrushOpacity: 0.74,
        layer3Enabled: true,
        layer3Type: 'standing_interference',
        layer3Source: 'plane',
        layer3Count: 6000,
        layer3FlowAmplitude: 36,
        layer3PatchOpacity: 0.58,
      }),
  createStarterPreset('starter-branch-propagation-atlas', 'Branch Propagation Atlas', {
        layer2Type: 'branch_propagation',
        layer2Source: 'text',
        layer2Count: 22000,
        layer2FiberDensity: 168,
        layer2FiberLength: 0.64,
        layer2FiberCurl: 0.32,
        layer3Enabled: true,
        layer3Type: 'biofilm_skin',
        layer3Source: 'plane',
        layer3Count: 5000,
        layer3FlowAmplitude: 20,
        layer3TemporalProfile: 'growth',
      }),
  createStarterPreset('starter-seep-fracture-delta', 'Seep Fracture Delta', {
        layer2Type: 'seep_fracture',
        layer2Source: 'image',
        layer2Count: 16000,
        layer2DepositionRelief: 0.72,
        layer2DepositionBands: 9,
        layer2DepositionErosion: 0.48,
        layer3Enabled: true,
        layer3Type: 'fracture_pollen',
        layer3Source: 'sphere',
        layer3Count: 5200,
        layer3FlowAmplitude: 52,
      }),
  createStarterPreset('starter-vapor-canopy-sanctum', 'Vapor Canopy Sanctum', {
        layer2Type: 'vapor_canopy',
        layer2Source: 'sphere',
        layer2Count: 14000,
        layer2FogDensity: 0.72,
        layer2FogDepth: 54,
        layer2FogSlices: 18,
        layer2FogDrift: 0.18,
        layer3Enabled: true,
        layer3Type: 'static_lace',
        layer3Source: 'grid',
        layer3Count: 5400,
        layer3FiberDensity: 132,
        layer3FiberLength: 0.38,
      }),
];
