import type { PresetSequenceItem } from '../types';

export const STARTER_PRESET_SEQUENCE_CHUNK_02: PresetSequenceItem[] = [
  {
      id: 'starter-sequence-hybrid-shell-pulse',
      presetId: 'starter-hybrid-shell-pulse',
      label: 'Hybrid Shell Pulse Reliquary',
      holdSeconds: 2.5,
      transitionSeconds: 1.8,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-liquid-rupture',
      presetId: 'starter-hybrid-liquid-rupture',
      label: 'Hybrid Liquid Rupture Manuscript',
      holdSeconds: 2.7,
      transitionSeconds: 2.0,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-simple-clean',
      presetId: 'starter-simple-clean',
      label: 'Starter Clean',
      holdSeconds: 2.6,
      transitionSeconds: 0.9,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-fluid-curl',
      presetId: 'starter-fluid-curl',
      label: 'Fluid Curl Field',
      holdSeconds: 3.2,
      transitionSeconds: 1.3,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-chaos-lorenz',
      presetId: 'starter-chaos-lorenz',
      label: 'Chaos Lorenz Bloom',
      holdSeconds: 3.4,
      transitionSeconds: 1.6,
      transitionEasing: 'ease-in',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-orbital-epicycle',
      presetId: 'starter-orbital-epicycle',
      label: 'Orbital Epicycle',
      holdSeconds: 3,
      transitionSeconds: 1.2,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-geometry-lattice',
      presetId: 'starter-geometry-lattice',
      label: 'Geometry Lattice',
      holdSeconds: 2.8,
      transitionSeconds: 1.15,
      transitionEasing: 'linear',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 0.9,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-toroidal-gyre',
      presetId: 'starter-toroidal-gyre',
      label: 'Toroidal Gyre',
      holdSeconds: 3.1,
      transitionSeconds: 1.25,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.05,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-symmetry-lissajous',
      presetId: 'starter-symmetry-lissajous',
      label: 'Symmetry Lissajous',
      holdSeconds: 2.8,
      transitionSeconds: 1.1,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 0.95,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-aizawa-ink',
      presetId: 'starter-aizawa-ink',
      label: 'Aizawa Ink Spiral',
      holdSeconds: 3.3,
      transitionSeconds: 1.35,
      transitionEasing: 'ease-in',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-fractal-ridged',
      presetId: 'starter-fractal-ridged',
      label: 'Fractal Ridged Storm',
      holdSeconds: 3.5,
      transitionSeconds: 1.5,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-kaleido-prism',
      presetId: 'starter-kaleido-prism',
      label: 'Kaleido Prism',
      holdSeconds: 2.9,
      transitionSeconds: 1.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 0.95,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-pulse-shell',
      presetId: 'starter-pulse-shell',
      label: 'Pulse Shell',
      holdSeconds: 3,
      transitionSeconds: 1.2,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-mandala-bloom',
      presetId: 'starter-mandala-bloom',
      label: 'Mandala Bloom',
      holdSeconds: 3,
      transitionSeconds: 1.2,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-spokes-breath',
      presetId: 'starter-spokes-breath',
      label: 'Spokes Breath',
      holdSeconds: 2.9,
      transitionSeconds: 1.1,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 0.95,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-knot-flare',
      presetId: 'starter-knot-flare',
      label: 'Torus Knot Flare',
      holdSeconds: 3.1,
      transitionSeconds: 1.2,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-caustic-nebula',
      presetId: 'starter-caustic-nebula',
      label: 'Caustic Nebula',
      holdSeconds: 3.2,
      transitionSeconds: 1.3,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.05,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-pinwheel-runes',
      presetId: 'starter-pinwheel-runes',
      label: 'Pinwheel Runes',
      holdSeconds: 2.9,
      transitionSeconds: 1.15,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 0.95,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-monolith-nova',
      presetId: 'starter-monolith-nova',
      label: 'Monolith Nova',
      holdSeconds: 3.1,
      transitionSeconds: 1.25,
      transitionEasing: 'ease-in',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-orbit-swarm',
      presetId: 'starter-orbit-swarm',
      label: 'Orbit Swarm Crown',
      holdSeconds: 3.0,
      transitionSeconds: 1.15,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-braid-stream',
      presetId: 'starter-braid-stream',
      label: 'Braid Stream Filaments',
      holdSeconds: 3.1,
      transitionSeconds: 1.2,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-pulse-breathing',
      presetId: 'starter-pulse-breathing',
      label: 'Pulse Breathing Halo',
      holdSeconds: 2.9,
      transitionSeconds: 1.05,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 0.96,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-collapse-fracture',
      presetId: 'starter-collapse-fracture',
      label: 'Collapse Fracture Manuscript',
      holdSeconds: 3.2,
      transitionSeconds: 1.25,
      transitionEasing: 'ease-in',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.08,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-crawl-seep',
      presetId: 'starter-crawl-seep',
      label: 'Crawl Seep Topography',
      holdSeconds: 3.0,
      transitionSeconds: 1.15,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
]
