import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_EXTENSION_CHUNK_03_EXPRESSION: PresetRecord[] = [
  createStarterPreset('starter-aura-eclipse-reliquary', 'Aura Eclipse Reliquary', {
        layer2Enabled: true,
        layer2Type: 'aura_shell',
        layer2Source: 'sphere',
        layer2MaterialStyle: 'glass',
        layer2TemporalProfile: 'oscillate',
        layer3Enabled: true,
        layer3Type: 'eclipse_halo',
        layer3Source: 'ring',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'shed',
      }),
  createStarterPreset('starter-resin-amber-shell', 'Resin Amber Shell', {
        layer2Enabled: true,
        layer2Type: 'resin_shell',
        layer2Source: 'image',
        layer2MaterialStyle: 'glass',
        layer2TemporalProfile: 'steady',
        layer3Enabled: true,
        layer3Type: 'aura_shell',
        layer3Source: 'sphere',
        layer3MaterialStyle: 'glass',
        layer3TemporalProfile: 'condense',
      }),
  createStarterPreset('starter-eclipse-amber-codex', 'Eclipse Amber Codex', {
        layer2Enabled: true,
        layer2Type: 'eclipse_halo',
        layer2Source: 'ring',
        layer2MaterialStyle: 'hologram',
        layer2TemporalProfile: 'oscillate',
        layer3Enabled: true,
        layer3Type: 'resin_shell',
        layer3Source: 'sphere',
        layer3MaterialStyle: 'glass',
        layer3TemporalProfile: 'steady',
      }),
  createStarterPreset('starter-source-text-shell-deposition-contrast', 'Source Text Shell Deposition Contrast', {
        layer2Enabled: true,
        layer2Type: 'shell_script',
        layer2Source: 'text',
        layer2TextMapText: 'VARELSER',
        layer2MaterialStyle: 'classic',
        layer2TemporalProfile: 'unravel',
        layer2TemporalStrength: 0.24,
        layer2HullOpacity: 0.82,
        layer2HullFresnel: 0.74,
        layer2HullJitter: 0.06,
        layer3Enabled: true,
        layer3Type: 'ink_bleed',
        layer3Source: 'text',
        layer3TextMapText: '慈愛体系',
        layer3MaterialStyle: 'halftone',
        layer3TemporalProfile: 'accrete',
        layer3TemporalStrength: 0.28,
        layer3DepositionOpacity: 0.8,
        layer3DepositionRelief: 0.56,
        layer3DepositionErosion: 0.32,
        layer3DepositionBands: 6,
      }),
  createStarterPreset('starter-source-grid-shell-fog-contrast', 'Source Grid Shell Fog Contrast', {
        layer2Enabled: true,
        layer2Type: 'calcified_skin',
        layer2Source: 'grid',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'steady',
        layer2HullOpacity: 0.76,
        layer2HullFresnel: 0.44,
        layer2HullJitter: 0.04,
        layer3Enabled: true,
        layer3Type: 'static_smoke',
        layer3Source: 'grid',
        layer3MaterialStyle: 'halftone',
        layer3TemporalProfile: 'oscillate',
        layer3TemporalStrength: 0.24,
        layer3FogOpacity: 0.24,
        layer3FogDensity: 0.44,
        layer3FogDepth: 0.72,
        layer3FogScale: 0.84,
      }),
  createStarterPreset('starter-source-ring-halo-fog-contrast', 'Source Ring Halo Fog Contrast', {
        layer2Enabled: true,
        layer2Type: 'eclipse_halo',
        layer2Source: 'ring',
        layer2MaterialStyle: 'glass',
        layer2TemporalProfile: 'oscillate',
        layer2TemporalStrength: 0.24,
        layer2HullOpacity: 0.8,
        layer2HullFresnel: 0.82,
        layer2HullJitter: 0.04,
        layer3Enabled: true,
        layer3Type: 'dust_plume',
        layer3Source: 'ring',
        layer3MaterialStyle: 'classic',
        layer3TemporalProfile: 'resonate',
        layer3TemporalStrength: 0.26,
        layer3FogOpacity: 0.26,
        layer3FogDensity: 0.42,
        layer3FogDepth: 0.82,
        layer3FogScale: 0.9,
      }),
  createStarterPreset('starter-source-plane-fog-deposition-contrast', 'Source Plane Fog Deposition Contrast', {
        layer2Enabled: true,
        layer2Type: 'soot_veil',
        layer2Source: 'plane',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'steady',
        layer2FogOpacity: 0.22,
        layer2FogDensity: 0.48,
        layer2FogDepth: 0.7,
        layer2FogScale: 0.88,
        layer3Enabled: true,
        layer3Type: 'ink_bleed',
        layer3Source: 'plane',
        layer3MaterialStyle: 'halftone',
        layer3TemporalProfile: 'accrete',
        layer3TemporalStrength: 0.24,
        layer3DepositionOpacity: 0.82,
        layer3DepositionRelief: 0.58,
        layer3DepositionErosion: 0.26,
        layer3DepositionBands: 4,
      }),
  createStarterPreset('starter-static-signal-lace', 'Static Signal Lace', {
        layer2Enabled: true,
        layer2Type: 'static_lace',
        layer2Source: 'grid',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'oscillate',
        layer2TemporalStrength: 0.28,
        layer2FiberOpacity: 0.78,
        layer2FiberLength: 0.74,
        layer2FiberDensity: 0.68,
        layer2FiberCurl: 0.18,
        layer3Enabled: true,
        layer3Type: 'signal_braid',
        layer3Source: 'cylinder',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'resonate',
        layer3TemporalStrength: 0.3,
        layer3FiberOpacity: 0.82,
        layer3FiberLength: 1.16,
        layer3FiberDensity: 0.74,
        layer3FiberCurl: 0.28,
      }),
  createStarterPreset('starter-cinder-codex-web', 'Cinder Codex Web', {
        layer2Enabled: true,
        layer2Type: 'cinder_web',
        layer2Source: 'text',
        layer2TextMapText: 'VARELSER',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'shed',
        layer2TemporalStrength: 0.24,
        layer2FiberOpacity: 0.74,
        layer2FiberLength: 0.68,
        layer2FiberDensity: 0.64,
        layer2FiberCurl: 0.26,
        layer3Enabled: true,
        layer3Type: 'shell_script',
        layer3Source: 'text',
        layer3TextMapText: '慈愛体系',
        layer3MaterialStyle: 'classic',
        layer3TemporalProfile: 'steady',
        layer3PatchOpacity: 0.78,
        layer3PatchFresnel: 0.64,
      }),
  createStarterPreset('starter-spectral-braid-cylinder', 'Spectral Braid Cylinder', {
        layer2Enabled: true,
        layer2Type: 'spectral_mesh',
        layer2Source: 'cylinder',
        layer2MaterialStyle: 'hologram',
        layer2TemporalProfile: 'resonate',
        layer2TemporalStrength: 0.3,
        layer2FiberOpacity: 0.8,
        layer2FiberLength: 1.14,
        layer2FiberDensity: 0.72,
        layer2FiberCurl: 0.28,
        layer3Enabled: true,
        layer3Type: 'signal_braid',
        layer3Source: 'ring',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'oscillate',
        layer3TemporalStrength: 0.28,
        layer3FiberOpacity: 0.8,
        layer3FiberLength: 1.1,
        layer3FiberDensity: 0.7,
        layer3FiberCurl: 0.26,
      }),
  createStarterPreset('starter-velvet-ink-manuscript', 'Velvet Ink Manuscript', {
        layer2Enabled: true,
        layer2Type: 'velvet_ash',
        layer2Source: 'plane',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'shed',
        layer2TemporalStrength: 0.26,
        layer2FogOpacity: 0.26,
        layer2FogDensity: 0.42,
        layer2FogDepth: 0.78,
        layer2FogScale: 0.92,
        layer3Enabled: true,
        layer3Type: 'ink_bleed',
        layer3Source: 'plane',
        layer3MaterialStyle: 'halftone',
        layer3TemporalProfile: 'accrete',
        layer3TemporalStrength: 0.3,
        layer3DepositionOpacity: 0.8,
        layer3DepositionRelief: 0.62,
        layer3DepositionErosion: 0.3,
        layer3DepositionBands: 5,
      }),
  createStarterPreset('starter-rune-ledger-text', 'Rune Ledger Text', {
        layer2Enabled: true,
        layer2Type: 'rune_smoke',
        layer2Source: 'text',
        layer2TextMapText: 'VARELSER',
        layer2MaterialStyle: 'hologram',
        layer2TemporalProfile: 'oscillate',
        layer2TemporalStrength: 0.28,
        layer2FogOpacity: 0.28,
        layer2FogDensity: 0.38,
        layer2FogDepth: 0.72,
        layer3Enabled: true,
        layer3Type: 'drift_glyph_dust',
        layer3Source: 'text',
        layer3TextMapText: '慈愛体系',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'steady',
        layer3DepositionOpacity: 0.74,
        layer3DepositionRelief: 0.54,
        layer3DepositionErosion: 0.34,
        layer3DepositionBands: 6,
      }),
  createStarterPreset('starter-soot-ink-ledger', 'Soot Ink Ledger', {
        layer2Enabled: true,
        layer2Type: 'soot_veil',
        layer2Source: 'plane',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'steady',
        layer2FogOpacity: 0.22,
        layer2FogDensity: 0.48,
        layer2FogDepth: 0.7,
        layer2FogScale: 0.88,
        layer3Enabled: true,
        layer3Type: 'ink_bleed',
        layer3Source: 'plane',
        layer3MaterialStyle: 'halftone',
        layer3TemporalProfile: 'accrete',
        layer3TemporalStrength: 0.24,
        layer3DepositionOpacity: 0.82,
        layer3DepositionRelief: 0.58,
        layer3DepositionErosion: 0.26,
        layer3DepositionBands: 4,
      }),
];
