import type { PresetRecord } from '../types';
import { buildPostFxStackPatch } from './postFxLibrary';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_EXTENSION_CHUNK_02_CODEX_STUDIES: PresetRecord[] = [
  createStarterPreset('starter-stipple-relief-sigil', 'Stipple Relief Sigil', {
        layer2Enabled: true,
        layer2Type: 'stipple_field',
        layer2Source: 'text',
        layer2TextMapText: 'VARELSER',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'accrete',
        layer2DepositionBands: 6,
        layer3Enabled: true,
        layer3Type: 'sigil_dust',
        layer3Source: 'text',
        layer3MaterialStyle: 'halftone',
      }),
  createStarterPreset('starter-fracture-bloom-orbit', 'Fracture Bloom Orbit', {
        layer2Enabled: true,
        layer2Type: 'fracture_bloom',
        layer2Source: 'ring',
        layer2MaterialStyle: 'chrome',
        layer2TemporalProfile: 'rupture',
        layer2CrystalScale: 1.12,
        layer2CrystalDensity: 0.62,
        layer3Enabled: true,
        layer3Type: 'orbit_fracture',
        layer3Source: 'ring',
        layer3MaterialStyle: 'chrome',
      }),
  createStarterPreset('starter-surge-lattice-grid', 'Surge Lattice Grid', {
        layer2Enabled: true,
        layer2Type: 'lattice_surge',
        layer2Source: 'grid',
        layer2MaterialStyle: 'chrome',
        layer2TemporalProfile: 'oscillate',
        layer2VoxelOpacity: 0.82,
        layer2VoxelScale: 1.18,
        layer2VoxelSnap: 0.78,
        layer3Enabled: true,
        layer3Type: 'frost_lattice',
        layer3Source: 'grid',
        layer3MaterialStyle: 'glass',
      }),
  createStarterPreset('starter-pollen-fracture-codex', 'Pollen Fracture Codex', {
        layer2Enabled: true,
        layer2Type: 'pollen_lattice',
        layer2Source: 'text',
        layer2TextMapText: '慈愛体系',
        layer2MaterialStyle: 'glass',
        layer2TemporalProfile: 'shed',
        layer3Enabled: true,
        layer3Type: 'fracture_pollen',
        layer3Source: 'text',
        layer3TextMapText: 'VARELSER',
        layer3MaterialStyle: 'halftone',
      }),
  createStarterPreset('starter-resin-eclipse-shell', 'Resin Eclipse Shell', {
        layer2Enabled: true,
        layer2Type: 'resin_shell',
        layer2Source: 'sphere',
        layer2MaterialStyle: 'glass',
        layer2TemporalProfile: 'steady',
        layer3Enabled: true,
        layer3Type: 'eclipse_halo',
        layer3Source: 'ring',
        layer3MaterialStyle: 'glass',
      }),
  createStarterPreset('starter-contour-script-manuscript', 'Contour Script Manuscript', {
        layer2Enabled: true,
        layer2Type: 'contour_echo',
        layer2Source: 'text',
        layer2TextMapText: '慈愛体系',
        layer2TextMapSize: 300,
        layer2MaterialStyle: 'chrome',
        layer2TemporalProfile: 'resonate',
        layer2PatchResolution: 58,
        layer2PatchRelax: 0.18,
        layer2PatchFresnel: 0.66,
        layer3Enabled: true,
        layer3Type: 'shell_script',
        layer3Source: 'text',
        layer3TextMapText: 'VARELSER',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'unravel',
      }),
  createStarterPreset('starter-ink-glyph-palimpsest', 'Ink Glyph Palimpsest', {
        layer2Enabled: true,
        layer2Type: 'ink_bleed',
        layer2Source: 'text',
        layer2TextMapText: 'VARELSER',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'accrete',
        layer2DepositionOpacity: 0.76,
        layer2DepositionRelief: 0.48,
        layer2DepositionErosion: 0.36,
        layer2DepositionBands: 7,
        layer3Enabled: true,
        layer3Type: 'drift_glyph_dust',
        layer3Source: 'text',
        layer3TextMapText: '慈愛体系',
        layer3MaterialStyle: 'halftone',
        layer3TemporalProfile: 'condense',
      }),
  createStarterPreset('starter-sigil-shell-codex', 'Sigil Shell Codex', {
        layer2Enabled: true,
        layer2Type: 'sigil_dust',
        layer2Source: 'image',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'condense',
        layer2DepositionBands: 8,
        layer2DepositionErosion: 0.42,
        layer2DepositionRelief: 0.4,
        layer3Enabled: true,
        layer3Type: 'shell_script',
        layer3Source: 'grid',
        layer3MaterialStyle: 'classic',
        layer3TemporalProfile: 'unravel',
      }),
];
