import type { PresetRecord } from '../types';
import { buildPostFxStackPatch } from './postFxLibrary';
import { createStarterPreset } from './starterLibraryCore';
export const STARTER_PRESET_EXTENSION_CHUNK_01_OUTLINE_BIOLOGIC = [
  createStarterPreset('starter-outline-codex-trace', 'Outline Codex Trace', {
      layer2Enabled: true,
      layer2Type: 'contour_echo',
      layer2Source: 'text',
      layer2TextMapText: '慈愛体系',
      layer2TextMapSize: 320,
      layer2MaterialStyle: 'chrome',
      layer2TemporalProfile: 'resonate',
      layer2PatchResolution: 60,
      layer2PatchRelax: 0.18,
      layer2PatchFresnel: 0.68,
      layer2ConnectionEnabled: true,
      layer2ConnectionStyle: 'brush',
      layer2ConnectionWidth: 1.18,
      layer2ConnectionOpacity: 0.22,
      layer2GlyphOutlineEnabled: true,
      layer2GlyphOutlineWidth: 1.76,
      layer2GlyphOutlineOpacity: 0.68,
      layer2GlyphOutlineDepthBias: 0.06,
      layer3Enabled: true,
      layer3Type: 'shell_script',
      layer3Source: 'text',
      layer3TextMapText: 'VARELSER',
      layer3MaterialStyle: 'hologram',
      layer3TemporalProfile: 'unravel',
      layer3ConnectionEnabled: true,
      layer3ConnectionStyle: 'filament',
      layer3ConnectionWidth: 0.9,
      layer3ConnectionOpacity: 0.18,
      layer3GlyphOutlineEnabled: true,
      layer3GlyphOutlineWidth: 1.42,
      layer3GlyphOutlineOpacity: 0.54,
    }),
  createStarterPreset('starter-glyph-weave-ledger', 'Glyph Weave Ledger', {
      layer2Enabled: true,
      layer2Type: 'glyph_weave',
      layer2Source: 'text',
      layer2TextMapText: 'VARELSER',
      layer2TextMapSize: 286,
      layer2MaterialStyle: 'hologram',
      layer2TemporalProfile: 'oscillate',
      layer2FiberLength: 1.08,
      layer2FiberDensity: 0.68,
      layer2FiberCurl: 0.24,
      layer2ConnectionEnabled: true,
      layer2ConnectionStyle: 'filament',
      layer2ConnectionWidth: 0.94,
      layer2ConnectionOpacity: 0.2,
      layer2GlyphOutlineEnabled: true,
      layer2GlyphOutlineWidth: 1.54,
      layer2GlyphOutlineOpacity: 0.6,
      layer3Enabled: true,
      layer3Type: 'sigil_dust',
      layer3Source: 'text',
      layer3TextMapText: '慈愛体系',
      layer3MaterialStyle: 'halftone',
      layer3TemporalProfile: 'condense',
      layer3DepositionBands: 8,
      layer3DepositionRelief: 0.42,
      layer3DepositionErosion: 0.34,
      layer3GlyphOutlineEnabled: true,
      layer3GlyphOutlineWidth: 1.28,
      layer3GlyphOutlineOpacity: 0.48,
    }),
  createStarterPreset('starter-ink-outline-palimpsest', 'Ink Outline Palimpsest', {
      layer2Enabled: true,
      layer2Type: 'ink_bleed',
      layer2Source: 'text',
      layer2TextMapText: 'VARELSER',
      layer2MaterialStyle: 'halftone',
      layer2TemporalProfile: 'accrete',
      layer2DepositionOpacity: 0.78,
      layer2DepositionRelief: 0.48,
      layer2DepositionErosion: 0.32,
      layer2DepositionBands: 7,
      layer2GlyphOutlineEnabled: true,
      layer2GlyphOutlineWidth: 1.62,
      layer2GlyphOutlineOpacity: 0.58,
      layer3Enabled: true,
      layer3Type: 'drift_glyph_dust',
      layer3Source: 'text',
      layer3TextMapText: '慈愛体系',
      layer3MaterialStyle: 'halftone',
      layer3TemporalProfile: 'condense',
      layer3ConnectionEnabled: true,
      layer3ConnectionStyle: 'brush',
      layer3ConnectionWidth: 0.86,
      layer3ConnectionOpacity: 0.14,
      layer3GlyphOutlineEnabled: true,
      layer3GlyphOutlineWidth: 1.18,
      layer3GlyphOutlineOpacity: 0.42,
    }),
  createStarterPreset('starter-ribbon-biofilm-petri', 'Ribbon Biofilm Petri', {
      layer2Enabled: true,
      layer2Type: 'ribbon_veil',
      layer2Source: 'ring',
      layer2MaterialStyle: 'glass',
      layer2TemporalProfile: 'oscillate',
      layer2BrushOpacity: 0.76,
      layer2BrushLayers: 7,
      layer2BrushScale: 0.96,
      layer2BrushJitter: 0.22,
      layer3Enabled: true,
      layer3Type: 'biofilm_skin',
      layer3Source: 'plane',
      layer3MaterialStyle: 'glass',
      layer3TemporalProfile: 'accrete',
      layer3ReactionOpacity: 0.84,
      layer3ReactionFeed: 0.034,
      layer3ReactionKill: 0.056,
      layer3ReactionScale: 1.06,
      layer3ReactionWarp: 0.22,
    }),
  createStarterPreset('starter-liquid-smear-canvas', 'Liquid Smear Canvas', {
      layer2Enabled: true,
      layer2Type: 'liquid_smear',
      layer2Source: 'image',
      layer2MaterialStyle: 'classic',
      layer2TemporalProfile: 'melt',
      layer2BrushOpacity: 0.8,
      layer2BrushLayers: 6,
      layer2BrushScale: 0.9,
      layer2BrushJitter: 0.28,
      layer3Enabled: true,
      layer3Type: 'brush_surface',
      layer3Source: 'image',
      layer3MaterialStyle: 'halftone',
      layer3TemporalProfile: 'steady',
      layer3BrushOpacity: 0.7,
      layer3BrushLayers: 5,
      layer3BrushScale: 0.84,
      layer3BrushJitter: 0.18,
    }),
  createStarterPreset('starter-branch-arbor-growth', 'Branch Arbor Growth', {
      layer2Enabled: true,
      layer2Type: 'branch_propagation',
      layer2Source: 'sphere',
      layer2MaterialStyle: 'classic',
      layer2TemporalProfile: 'growth',
      layer2FiberOpacity: 0.72,
      layer2FiberLength: 0.96,
      layer2FiberDensity: 0.66,
      layer2FiberCurl: 0.26,
      layer3Enabled: true,
      layer3Type: 'growth_field',
      layer3Source: 'sphere',
      layer3MaterialStyle: 'classic',
      layer3TemporalProfile: 'growth',
      layer3GrowthOpacity: 0.74,
      layer3GrowthLength: 0.92,
      layer3GrowthBranches: 5,
      layer3GrowthSpread: 0.54,
    })
];
