import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_BASE_CHUNK_01_STRUCTURAL: PresetRecord[] = [
  createStarterPreset('starter-wave-shell', 'Wave Shell', {
      layer1Count: 11000,
      layer2Type: 'wave',
      layer2Source: 'spiral',
      layer2Count: 23000,
      layer2FlowAmplitude: 56,
      layer2FlowFrequency: 4.6,
      layer2Trail: 0.48,
      layer3Enabled: true,
      layer3Type: 'spiral_motion',
      layer3Source: 'spiral',
      layer3Count: 6000,
      layer3FlowAmplitude: 36,
      screenSweepIntensity: 0.14,
      screenVignetteIntensity: 0.08,
    }),
  createStarterPreset('starter-kaleido-prism', 'Kaleido Prism', {
      layer1Count: 12000,
      layer2Type: 'kaleidoscope',
      layer2Source: 'cone',
      layer2Count: 24000,
      layer2FlowAmplitude: 54,
      layer2ConnectionEnabled: true,
      layer2ConnectionDistance: 30,
      layer2ConnectionOpacity: 0.16,
      layer3Enabled: true,
      layer3Type: 'crystal',
      layer3Source: 'cube',
      layer3Count: 8000,
      screenSplitIntensity: 0.12,
    }),
  createStarterPreset('starter-braid-web', 'Braid Web', {
      layer1Count: 10000,
      layer2Type: 'braid',
      layer2Source: 'cylinder',
      layer2Count: 22000,
      layer2FlowAmplitude: 48,
      layer2Trail: 0.36,
      layer3Enabled: true,
      layer3Type: 'web',
      layer3Source: 'grid',
      layer3Count: 11000,
      layer3FlowAmplitude: 30,
      layer3ConnectionEnabled: true,
      layer3ConnectionDistance: 24,
      layer3ConnectionOpacity: 0.18,
    }),
  createStarterPreset('starter-arcwave-halo', 'Arc Wave Halo', {
      layer1Count: 9000,
      layer2Type: 'arc_wave',
      layer2Source: 'disc',
      layer2Count: 21000,
      layer2FlowAmplitude: 58,
      layer2FlowFrequency: 4.8,
      layer3Enabled: true,
      layer3Type: 'wave',
      layer3Count: 7000,
      layer3FlowAmplitude: 42,
      screenPulseIntensity: 0.18,
      screenVignetteIntensity: 0.12,
    }),
  createStarterPreset('starter-pulse-shell', 'Pulse Shell', {
      cameraControlMode: 'auto',
      renderQuality: 'cinematic',
      cameraImpulseStrength: 0.24,
      cameraImpulseSpeed: 1.45,
      cameraImpulseDrift: 0.32,
      cameraBurstBoost: 0.68,
      screenBurstDrive: 0.54,
      screenBurstNoiseBoost: 0.42,
      screenBurstFlashBoost: 0.5,
      layer1Count: 11000,
      layer2Type: 'pulse_shell',
      layer2Source: 'galaxy',
      layer2Count: 26000,
      layer2FlowAmplitude: 72,
      layer2Trail: 0.54,
      layer2Life: 64,
      layer2LifeSpread: 0.28,
      layer2LifeSizeBoost: 0.62,
      layer2LifeSizeTaper: 0.34,
      layer2Burst: 0.72,
      layer2BurstMode: 'sweep',
      layer2BurstWaveform: 'stutter',
      layer2BurstSweepSpeed: 2.1,
      layer2BurstSweepTilt: 0.42,
      layer2EmitterOrbitSpeed: 1.4,
      layer2EmitterOrbitRadius: 36,
      layer2EmitterPulseAmount: 0.18,
      layer2TrailDrag: 0.62,
      layer2TrailTurbulence: 0.48,
      layer2TrailDrift: 0.34,
      layer2VelocityGlow: 0.95,
      layer2VelocityAlpha: 0.52,
      layer2FlickerAmount: 0.34,
      layer2FlickerSpeed: 3.4,
      layer2Streak: 1.2,
      layer2SpriteMode: 'spark',
      layer2SparkEnabled: true,
      layer2SparkCount: 12000,
      layer2SparkLife: 18,
      layer2SparkDiffusion: 3.4,
      layer2SparkBurst: 1.35,
      layer2LineVelocityGlow: 0.92,
      layer2LineVelocityAlpha: 0.54,
      layer2LineBurstPulse: 0.78,
      layer2LineShimmer: 0.32,
      layer2LineFlickerSpeed: 2.9,
      layer3Enabled: true,
      layer3Type: 'orbit',
      layer3Source: 'ring',
      layer3Count: 6000,
      layer3FlowAmplitude: 38,
      layer3Life: 90,
      layer3Burst: 0.35,
      layer3SpriteMode: 'ring',
      screenPersistenceIntensity: 0.12,
      screenSweepIntensity: 0.16,
    }),
  createStarterPreset('starter-mandala-bloom', 'Mandala Bloom', {
      layer1Count: 9000,
      layer2Type: 'mandala',
      layer2Source: 'disc',
      layer2Count: 24000,
      layer2FlowAmplitude: 64,
      layer2FlowFrequency: 4.4,
      layer3Enabled: true,
      layer3Type: 'rose_curve',
      layer3Count: 8000,
      layer3FlowAmplitude: 34,
      screenPulseIntensity: 0.16,
    }),
  createStarterPreset('starter-ribbon-shear', 'Ribbon Shear', {
      layer1Count: 10000,
      layer2Type: 'ribbon',
      layer2Source: 'cylinder',
      layer2Count: 22000,
      layer2FlowAmplitude: 52,
      layer2Trail: 0.42,
      layer3Enabled: true,
      layer3Type: 'shear',
      layer3Count: 10000,
      layer3FlowAmplitude: 36,
      layer3Trail: 0.22,
    }),
  createStarterPreset('starter-spokes-breath', 'Spokes Breath', {
      layer1Count: 11000,
      layer2Type: 'spokes',
      layer2Source: 'sphere',
      layer2Count: 25000,
      layer2FlowAmplitude: 58,
      layer2ConnectionEnabled: true,
      layer2ConnectionDistance: 28,
      layer2ConnectionOpacity: 0.16,
      layer3Enabled: true,
      layer3Type: 'breathing',
      layer3Count: 7000,
      layer3FlowAmplitude: 30,
      screenPersistenceIntensity: 0.1,
    }),
  createStarterPreset('starter-knot-flare', 'Torus Knot Flare', {
      layer1Count: 10000,
      layer2Type: 'torus_knot',
      layer2Source: 'torus',
      layer2Count: 24000,
      layer2FlowAmplitude: 62,
      layer2Trail: 0.5,
      layer3Enabled: true,
      layer3Type: 'flare',
      layer3Count: 7000,
      layer3FlowAmplitude: 28,
      screenSweepIntensity: 0.18,
    }),
  createStarterPreset('starter-cellular-sheet', 'Cellular Sheet', {
      viewMode: 'orthographic',
      layer1Count: 8000,
      layer2Type: 'cellular',
      layer2Source: 'grid',
      layer2Count: 22000,
      layer2FlowAmplitude: 40,
      layer3Enabled: true,
      layer3Type: 'sheet',
      layer3Source: 'plane',
      layer3Count: 9000,
      layer3FlowAmplitude: 30,
      screenScanlineIntensity: 0.1,
    }),
];
