import type { PresetSequenceItem } from '../types';

export const STARTER_PRESET_SEQUENCE_CHUNK_03: PresetSequenceItem[] = [
  {
      id: 'starter-sequence-interference-wave',
      presetId: 'starter-interference-wave',
      label: 'Interference Wave Lattice',
      holdSeconds: 3.0,
      transitionSeconds: 1.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-mesh-weave-canopy',
      presetId: 'starter-mesh-weave-canopy',
      label: 'Mesh Weave Canopy',
      holdSeconds: 3.0,
      transitionSeconds: 1.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-halo-bloom-sanctum',
      presetId: 'starter-halo-bloom-sanctum',
      label: 'Halo Bloom Sanctum',
      holdSeconds: 3.0,
      transitionSeconds: 1.15,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-dust-plume-vault',
      presetId: 'starter-dust-plume-vault',
      label: 'Dust Plume Vault',
      holdSeconds: 3.2,
      transitionSeconds: 1.2,
      transitionEasing: 'ease-in',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.05,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-ink-bleed-manuscript',
      presetId: 'starter-ink-bleed-manuscript',
      label: 'Ink Bleed Manuscript',
      holdSeconds: 3.0,
      transitionSeconds: 1.12,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 0.96,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-contour-echo-topology',
      presetId: 'starter-contour-echo-topology',
      label: 'Contour Echo Topology',
      holdSeconds: 3.1,
      transitionSeconds: 1.18,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-crystal-bloom',
      presetId: 'starter-hybrid-crystal-bloom',
      label: 'Hybrid Crystal Bloom Reliquary',
      holdSeconds: 3.2,
      transitionSeconds: 1.2,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.02,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-inscription-fade',
      presetId: 'starter-hybrid-inscription-fade',
      label: 'Hybrid Inscription Fade Sanctuary',
      holdSeconds: 3.0,
      transitionSeconds: 1.16,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 0.98,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-accretion-lift',
      presetId: 'starter-hybrid-accretion-lift',
      label: 'Hybrid Accretion Lift Delta',
      holdSeconds: 3.15,
      transitionSeconds: 1.18,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.0,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-breathing-reliquary',
      presetId: 'starter-hybrid-breathing-reliquary',
      label: 'Hybrid Breathing Reliquary',
      holdSeconds: 2.85,
      transitionSeconds: 1.08,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.04,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-fracture-spill',
      presetId: 'starter-hybrid-fracture-spill',
      label: 'Hybrid Fracture Spill Manuscript',
      holdSeconds: 3.25,
      transitionSeconds: 1.2,
      transitionEasing: 'ease-in',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.08,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-tremor-lattice-chamber',
      presetId: 'starter-tremor-lattice-chamber',
      label: 'Tremor Lattice Chamber',
      holdSeconds: 3.15,
      transitionSeconds: 1.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.02,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-bloom-torrent-spores',
      presetId: 'starter-bloom-torrent-spores',
      label: 'Bloom Torrent Spores',
      holdSeconds: 3.05,
      transitionSeconds: 1.12,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.06,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-orbit-fracture-reliquary',
      presetId: 'starter-orbit-fracture-reliquary',
      label: 'Orbit Fracture Reliquary',
      holdSeconds: 3.2,
      transitionSeconds: 1.18,
      transitionEasing: 'ease-in',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.0,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-foam-soot-sanctuary',
      presetId: 'starter-foam-soot-sanctuary',
      label: 'Foam Soot Sanctuary',
      holdSeconds: 2.95,
      transitionSeconds: 1.08,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 0.97,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-signal-nerve-atlas',
      presetId: 'starter-signal-nerve-atlas',
      label: 'Signal Nerve Atlas',
      holdSeconds: 3.1,
      transitionSeconds: 1.16,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.03,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-pollen-storm-vault',
      presetId: 'starter-pollen-storm-vault',
      label: 'Pollen Storm Vault',
      holdSeconds: 3.0,
      transitionSeconds: 1.1,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.05,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-charge-veil-nimbus',
      presetId: 'starter-charge-veil-nimbus',
      label: 'Charge Veil Nimbus',
      holdSeconds: 3.0,
      transitionSeconds: 1.15,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.06,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-cinder-web-script',
      presetId: 'starter-cinder-web-script',
      label: 'Cinder Web Script',
      holdSeconds: 2.85,
      transitionSeconds: 1.08,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 0.98,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-membrane-pollen-orbit',
      presetId: 'starter-membrane-pollen-orbit',
      label: 'Membrane Pollen Orbit',
      holdSeconds: 3.1,
      transitionSeconds: 1.12,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.03,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-spectral-mesh-lattice',
      presetId: 'starter-spectral-mesh-lattice',
      label: 'Spectral Mesh Lattice',
      holdSeconds: 3.0,
      transitionSeconds: 1.12,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.02,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-rune-smoke-script',
      presetId: 'starter-rune-smoke-script',
      label: 'Rune Smoke Script',
      holdSeconds: 2.9,
      transitionSeconds: 1.08,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.04,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-spore-halo-bloom',
      presetId: 'starter-spore-halo-bloom',
      label: 'Spore Halo Bloom',
      holdSeconds: 3.05,
      transitionSeconds: 1.14,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.06,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-veil-script-evaporation',
      presetId: 'starter-veil-script-evaporation',
      label: 'Veil Script Evaporation',
      holdSeconds: 2.9,
      transitionSeconds: 1.1,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.03,
      keyframeConfig: null,
    },
]
