import type { PresetRecord } from '../types';
import { buildPostFxStackPatch } from './postFxLibrary';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_EXTENSION_CHUNK_02_SURFACE_STUDIES: PresetRecord[] = [
  createStarterPreset('starter-aura-eclipse-reliquary', 'Aura Eclipse Reliquary', {
        layer2Enabled: true,
        layer2Type: 'aura_shell',
        layer2Source: 'sphere',
        layer2MaterialStyle: 'glass',
        layer2TemporalProfile: 'oscillate',
        layer3Enabled: true,
        layer3Type: 'eclipse_halo',
        layer3Source: 'ring',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'shed',
      }),
  createStarterPreset('starter-resin-amber-shell', 'Resin Amber Shell', {
        layer2Enabled: true,
        layer2Type: 'resin_shell',
        layer2Source: 'image',
        layer2MaterialStyle: 'glass',
        layer2TemporalProfile: 'steady',
        layer3Enabled: true,
        layer3Type: 'aura_shell',
        layer3Source: 'sphere',
        layer3MaterialStyle: 'glass',
        layer3TemporalProfile: 'condense',
      }),
  createStarterPreset('starter-eclipse-amber-codex', 'Eclipse Amber Codex', {
        layer2Enabled: true,
        layer2Type: 'eclipse_halo',
        layer2Source: 'ring',
        layer2MaterialStyle: 'hologram',
        layer2TemporalProfile: 'oscillate',
        layer3Enabled: true,
        layer3Type: 'resin_shell',
        layer3Source: 'sphere',
        layer3MaterialStyle: 'glass',
        layer3TemporalProfile: 'steady',
      }),
  createStarterPreset('starter-dust-plume-column', 'Dust Plume Column', {
        layer2Enabled: true,
        layer2Type: 'dust_plume',
        layer2Source: 'sphere',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'growth',
        layer2FogOpacity: 0.26,
        layer2FogDensity: 0.4,
        layer2FogDepth: 0.88,
        layer2FogScale: 0.98,
        layer2FogSlices: 16,
        layer3Enabled: true,
        layer3Type: 'contour_echo',
        layer3Source: 'text',
        layer3TextMapText: 'DUST',
        layer3MaterialStyle: 'chrome',
        layer3TemporalProfile: 'accrete',
      }),
  createStarterPreset('starter-ashfall-ledger', 'Ashfall Ledger', {
        layer2Enabled: true,
        layer2Type: 'ashfall',
        layer2Source: 'plane',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'shed',
        layer2FogOpacity: 0.24,
        layer2FogDensity: 0.42,
        layer2FogDepth: 0.9,
        layer2FogScale: 1.04,
        layer2FogSlices: 15,
        layer3Enabled: true,
        layer3Type: 'shell_script',
        layer3Source: 'text',
        layer3TextMapText: 'LEDGER',
        layer3MaterialStyle: 'classic',
        layer3TemporalProfile: 'accrete',
      }),
  createStarterPreset('starter-mirage-heatfield', 'Mirage Heatfield', {
        layer2Enabled: true,
        layer2Type: 'mirage_smoke',
        layer2Source: 'video',
        layer2MaterialStyle: 'hologram',
        layer2TemporalProfile: 'evaporate',
        layer2FogOpacity: 0.22,
        layer2FogDensity: 0.28,
        layer2FogDepth: 0.8,
        layer2FogScale: 1.18,
        layer2FogSlices: 21,
        layer3Enabled: true,
        layer3Type: 'prism_threads',
        layer3Source: 'video',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'oscillate',
      }),
  createStarterPreset('starter-static-smoke-slab', 'Static Smoke Slab', {
        layer2Enabled: true,
        layer2Type: 'static_smoke',
        layer2Source: 'grid',
        layer2MaterialStyle: 'hologram',
        layer2TemporalProfile: 'oscillate',
        layer2FogOpacity: 0.28,
        layer2FogDensity: 0.4,
        layer2FogDepth: 0.72,
        layer2FogScale: 0.94,
        layer2FogSlices: 18,
        layer3Enabled: true,
        layer3Type: 'spectral_mesh',
        layer3Source: 'grid',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'oscillate',
      }),
];
