import type { PresetSequenceItem } from '../types';

export const STARTER_PRESET_SEQUENCE_CHUNK_04: PresetSequenceItem[] = [
  {
      id: 'starter-sequence-spore-halo-accretion',
      presetId: 'starter-spore-halo-accretion',
      label: 'Spore Halo Accretion',
      holdSeconds: 3.0,
      transitionSeconds: 1.16,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.05,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-lattice-smoke-shedding',
      presetId: 'starter-lattice-smoke-shedding',
      label: 'Lattice Smoke Shedding',
      holdSeconds: 2.95,
      transitionSeconds: 1.12,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.02,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-aurora-thread-mirage',
      presetId: 'starter-aurora-thread-mirage',
      label: 'Aurora Thread Mirage',
      holdSeconds: 3.0,
      transitionSeconds: 1.14,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.05,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-residue-sigil-reliquary',
      presetId: 'starter-residue-sigil-reliquary',
      label: 'Residue Sigil Reliquary',
      holdSeconds: 2.9,
      transitionSeconds: 1.08,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.01,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-frost-lattice-script',
      presetId: 'starter-frost-lattice-script',
      label: 'Frost Lattice Script',
      holdSeconds: 3.05,
      transitionSeconds: 1.16,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.04,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-thread-smoke-reverie',
      presetId: 'starter-thread-smoke-reverie',
      label: 'Thread Smoke Reverie',
      holdSeconds: 3.0,
      transitionSeconds: 1.12,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.06,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-script-accretion-skin',
      presetId: 'starter-script-accretion-skin',
      label: 'Script Accretion Skin',
      holdSeconds: 2.9,
      transitionSeconds: 1.08,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.02,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-halo-dust-shedding',
      presetId: 'starter-halo-dust-shedding',
      label: 'Halo Dust Shedding',
      holdSeconds: 3.05,
      transitionSeconds: 1.14,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.05,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-prism-charge-tempest',
      presetId: 'starter-prism-charge-tempest',
      label: 'Prism Charge Tempest',
      holdSeconds: 3.0,
      transitionSeconds: 1.14,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.08,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-rune-soot-archive',
      presetId: 'starter-rune-soot-archive',
      label: 'Rune Soot Archive',
      holdSeconds: 2.9,
      transitionSeconds: 1.06,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.0,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-ember-cinder-lace',
      presetId: 'starter-ember-cinder-lace',
      label: 'Ember Cinder Lace',
      holdSeconds: 2.95,
      transitionSeconds: 1.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.04,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-spectral-aurora-choir',
      presetId: 'starter-spectral-aurora-choir',
      label: 'Spectral Aurora Choir',
      holdSeconds: 3.1,
      transitionSeconds: 1.18,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.06,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-spore-pollen-sanctum',
      presetId: 'starter-spore-pollen-sanctum',
      label: 'Spore Pollen Sanctum',
      holdSeconds: 2.92,
      transitionSeconds: 1.12,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.02,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-sigil-frost-palace',
      presetId: 'starter-sigil-frost-palace',
      label: 'Sigil Frost Palace',
      holdSeconds: 3.04,
      transitionSeconds: 1.15,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.05,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-resonance-flux-cathedral',
      presetId: 'starter-resonance-flux-cathedral',
      label: 'Resonance Flux Cathedral',
      holdSeconds: 3.08,
      transitionSeconds: 1.16,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.06,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-thread-prism-resonance',
      presetId: 'starter-thread-prism-resonance',
      label: 'Thread Prism Resonance',
      holdSeconds: 3.02,
      transitionSeconds: 1.12,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.05,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-shell-smoke-condensation',
      presetId: 'starter-shell-smoke-condensation',
      label: 'Shell Smoke Condensation',
      holdSeconds: 2.96,
      transitionSeconds: 1.08,
      transitionEasing: 'ease-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.02,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-pollen-script-unraveling',
      presetId: 'starter-pollen-script-unraveling',
      label: 'Pollen Script Unraveling',
      holdSeconds: 2.98,
      transitionSeconds: 1.14,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.04,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-ash-lattice-ignition',
      presetId: 'starter-ash-lattice-ignition',
      label: 'Ash Lattice Ignition',
      holdSeconds: 3.06,
      transitionSeconds: 1.18,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.08,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-halo-thread-bloom',
      presetId: 'starter-halo-thread-bloom',
      label: 'Halo Thread Bloom',
      holdSeconds: 3.0,
      transitionSeconds: 1.14,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.05,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-resin-glyph-accretion',
      presetId: 'starter-resin-glyph-accretion',
      label: 'Resin Glyph Accretion',
      holdSeconds: 2.92,
      transitionSeconds: 1.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.03,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-ion-rain-orbit',
      presetId: 'starter-ion-rain-orbit',
      label: 'Ion Rain Orbit',
      holdSeconds: 2.94,
      transitionSeconds: 1.11,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.03,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-static-smoke-glyph-weave',
      presetId: 'starter-static-smoke-glyph-weave',
      label: 'Static Smoke Glyph Weave',
      holdSeconds: 2.98,
      transitionSeconds: 1.15,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.05,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-fracture-bloom-embers',
      presetId: 'starter-fracture-bloom-embers',
      label: 'Fracture Bloom Embers',
      holdSeconds: 3.04,
      transitionSeconds: 1.2,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1.09,
      keyframeConfig: null,
    },
]
