import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_BASE_CHUNK_04_WEATHER_RELICS: PresetRecord[] = [
  createStarterPreset('starter-script-accretion-skin', 'Script Accretion Skin', {
        layer2Type: 'frost_lattice',
        layer2TemporalProfile: 'accrete',
        layer2TemporalStrength: 0.7,
        layer3Enabled: true,
        layer3Type: 'sigil_dust',
        layer3TemporalProfile: 'accrete',
        layer3TemporalStrength: 0.62,
        layer3DepositionBands: 14,
      }),
  createStarterPreset('starter-halo-dust-shedding', 'Halo Dust Shedding', {
        layer2Type: 'spore_halo',
        layer2TemporalProfile: 'shed',
        layer2TemporalStrength: 0.68,
        layer3Enabled: true,
        layer3Type: 'sigil_dust',
        layer3TemporalProfile: 'evaporate',
        layer3TemporalStrength: 0.64,
        layer2HullOpacity: 0.58,
        layer3DepositionOpacity: 0.72,
      }),
  createStarterPreset('starter-prism-charge-tempest', 'Prism Charge Tempest', {
        cameraControlMode: 'hybrid',
        renderQuality: 'cinematic',
        layer2Enabled: true,
        layer2Type: 'charge_veil',
        layer2Source: 'ring',
        layer2Count: 5200,
        layer2FogDensity: 0.74,
        layer2TemporalProfile: 'oscillate',
        layer2TemporalStrength: 0.72,
        layer3Enabled: true,
        layer3Type: 'prism_smoke',
        layer3Source: 'sphere',
        layer3Count: 4800,
        layer3FogDensity: 0.82,
        layer3TemporalProfile: 'evaporate',
        layer3TemporalStrength: 0.66,
        postBloomEnabled: true,
        postBloomIntensity: 0.48,
      }),
  createStarterPreset('starter-rune-soot-archive', 'Rune Soot Archive', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'rune_smoke',
        layer2Source: 'text',
        layer2TextMapText: 'ARCHIVE',
        layer2Count: 3600,
        layer2TemporalProfile: 'shed',
        layer2TemporalStrength: 0.58,
        layer3Enabled: true,
        layer3Type: 'soot_veil',
        layer3Source: 'sphere',
        layer3Count: 4200,
        layer3TemporalProfile: 'decay',
        layer3TemporalStrength: 0.62,
      }),
  createStarterPreset('starter-ember-cinder-lace', 'Ember Cinder Lace', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'ember_lace',
        layer2Source: 'ring',
        layer2Count: 7800,
        layer2TemporalProfile: 'oscillate',
        layer3Enabled: true,
        layer3Type: 'cinder_web',
        layer3Source: 'cube',
        layer3Count: 6600,
        layer3TemporalProfile: 'accrete',
      }),
  createStarterPreset('starter-spectral-aurora-choir', 'Spectral Aurora Choir', {
        cameraControlMode: 'hybrid',
        renderQuality: 'cinematic',
        layer2Enabled: true,
        layer2Type: 'spectral_mesh',
        layer2Source: 'sphere',
        layer2Count: 7200,
        layer2TemporalProfile: 'oscillate',
        layer3Enabled: true,
        layer3Type: 'aurora_threads',
        layer3Source: 'ring',
        layer3Count: 8600,
        layer3TemporalProfile: 'growth',
        postBloomEnabled: true,
        postBloomIntensity: 0.42,
      }),
  createStarterPreset('starter-spore-pollen-sanctum', 'Spore Pollen Sanctum', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer2Enabled: true,
        layer2Type: 'spore_halo',
        layer2Source: 'sphere',
        layer2Count: 4800,
        layer2TemporalProfile: 'growth',
        layer2TemporalStrength: 0.64,
        layer3Enabled: true,
        layer3Type: 'membrane_pollen',
        layer3Source: 'sphere',
        layer3Count: 4200,
        layer3TemporalProfile: 'accrete',
        layer3TemporalStrength: 0.6,
      }),
  createStarterPreset('starter-sigil-frost-palace', 'Sigil Frost Palace', {
        cameraControlMode: 'hybrid',
        renderQuality: 'cinematic',
        layer2Enabled: true,
        layer2Type: 'sigil_dust',
        layer2Source: 'text',
        layer2TextMapText: 'PALACE',
        layer2Count: 3400,
        layer2TemporalProfile: 'shed',
        layer3Enabled: true,
        layer3Type: 'frost_lattice',
        layer3Source: 'sphere',
        layer3Count: 7600,
        layer3TemporalProfile: 'crystallize',
      }),
];
