import type { PresetRecord } from '../types';
import { buildPostFxStackPatch } from './postFxLibrary';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_EXTENSION_CHUNK_04: PresetRecord[] = [
  createStarterPreset('starter-reaction-plate-labyrinth', 'Reaction Plate Labyrinth', { layer2Enabled: true, layer2Type: 'reaction_diffusion', layer2Source: 'text', layer2TextMapText: 'LABYRINTH', layer2TextMapSize: 292, layer2TextMapPadding: 42, layer2TextMapWeight: 700, layer2MaterialStyle: 'glass', layer2TemporalProfile: 'phase_shift', layer2TemporalStrength: 0.28, layer2Count: 9800, layer2BaseSize: 0.8, layer2RadiusScale: 1.02, layer2ReactionOpacity: 0.82, layer2ReactionFeed: 0.027, layer2ReactionKill: 0.053, layer2ReactionScale: 1.06, layer2ReactionWarp: 0.18, layer2GeomMode3D: 'icosa', layer2GeomScale3D: 0.86 }),
  createStarterPreset('starter-biofilm-colony-skin', 'Biofilm Colony Skin', { layer2Enabled: true, layer2Type: 'biofilm_skin', layer2Source: 'image', layer2MaterialStyle: 'glass', layer2TemporalProfile: 'accrete', layer2TemporalStrength: 0.28, layer2Count: 9600, layer2BaseSize: 0.86, layer2RadiusScale: 1.06, layer2ReactionOpacity: 0.84, layer2ReactionFeed: 0.034, layer2ReactionKill: 0.057, layer2ReactionScale: 0.98, layer2ReactionWarp: 0.14, layer2GeomMode3D: 'icosa', layer2GeomScale3D: 0.92, layer3Enabled: true, layer3Type: 'glyph_weave', layer3Source: 'text', layer3TextMapText: 'COLONY', layer3TextMapSize: 288, layer3TextMapPadding: 40, layer3TextMapWeight: 700, layer3MaterialStyle: 'hologram', layer3TemporalProfile: 'accrete', layer3TemporalStrength: 0.22, layer3GlyphOutlineEnabled: true, layer3GlyphOutlineWidth: 1.42, layer3GlyphOutlineOpacity: 0.5, layer3FiberOpacity: 0.72, layer3FiberLength: 0.9, layer3FiberDensity: 0.68, layer3FiberCurl: 0.16 }),
  createStarterPreset('starter-review-grid-relief-shell-split', 'Review Grid Relief Shell Split', {
      layer2Enabled: true,
      layer2Type: 'contour_echo',
      layer2Source: 'grid',
      layer2MaterialStyle: 'halftone',
      layer2TemporalProfile: 'resonate',
      layer2TemporalStrength: 0.24,
      layer2PatchResolution: 58,
      layer2PatchRelax: 0.16,
      layer2PatchFresnel: 0.7,
      layer3Enabled: true,
      layer3Type: 'calcified_skin',
      layer3Source: 'grid',
      layer3MaterialStyle: 'chrome',
      layer3TemporalProfile: 'steady',
      layer3HullOpacity: 0.78,
      layer3HullFresnel: 0.52,
      layer3HullJitter: 0.05,
    }),
  createStarterPreset('starter-cloth-membrane-sail', 'Cloth Membrane Sail', {
      layer2Enabled: true,
      layer2Type: 'cloth_membrane',
      layer2Source: 'plane',
      layer2MaterialStyle: 'glass',
      layer2TemporalProfile: 'inhale',
      layer2TemporalStrength: 0.24,
      layer2Count: 9600,
      layer2BaseSize: 0.9,
      layer2RadiusScale: 1.08,
      layer2SheetOpacity: 0.66,
      layer2SheetFresnel: 0.68,
      layer2SheetAudioReactive: 0.12,
      layer2SheetWireframe: false,
    }),
  createStarterPreset('starter-viscous-flow-ledger', 'Viscous Flow Ledger', {
      layer2Enabled: true,
      layer2Type: 'viscous_flow',
      layer2Source: 'image',
      layer2MaterialStyle: 'classic',
      layer2TemporalProfile: 'phase_shift',
      layer2TemporalStrength: 0.28,
      layer2Count: 9400,
      layer2BaseSize: 0.86,
      layer2RadiusScale: 1.0,
      layer2BrushOpacity: 0.84,
      layer2BrushLayers: 6,
      layer2BrushScale: 1.12,
      layer2BrushJitter: 0.2,
      layer2BrushAudioReactive: 0.08,
    }),
  createStarterPreset('starter-granular-fall-pile', 'Granular Fall Pile', {
      layer2Enabled: true,
      layer2Type: 'granular_fall',
      layer2Source: 'sphere',
      layer2MaterialStyle: 'halftone',
      layer2TemporalProfile: 'accumulate',
      layer2TemporalStrength: 0.26,
      layer2Count: 10400,
      layer2BaseSize: 0.72,
      layer2RadiusScale: 1.0,
      layer2CrystalOpacity: 0.74,
      layer2CrystalScale: 0.9,
      layer2CrystalDensity: 0.78,
      layer2CrystalSpread: 0.26,
    }),
  createStarterPreset('starter-fracture-grammar-plate', 'Fracture Grammar Plate', {
      layer2Enabled: true,
      layer2Type: 'fracture_grammar',
      layer2Source: 'grid',
      layer2MaterialStyle: 'classic',
      layer2TemporalProfile: 'phase_shift',
      layer2TemporalStrength: 0.28,
      layer2Count: 8600,
      layer2BaseSize: 0.76,
      layer2RadiusScale: 1.0,
      layer2GrowthOpacity: 0.76,
      layer2GrowthBranches: 6,
      layer2GrowthLength: 0.88,
      layer2GrowthSpread: 0.34,
    }),
  createStarterPreset('starter-growth-grammar-arbor', 'Growth Grammar Arbor', {
      layer2Enabled: true,
      layer2Type: 'growth_grammar',
      layer2Source: 'sphere',
      layer2MaterialStyle: 'hologram',
      layer2TemporalProfile: 'rewrite',
      layer2TemporalStrength: 0.28,
      layer2Count: 9000,
      layer2BaseSize: 0.78,
      layer2RadiusScale: 1.08,
      layer2GrowthOpacity: 0.8,
      layer2GrowthBranches: 8,
      layer2GrowthLength: 1.02,
      layer2GrowthSpread: 0.48,
      layer3Enabled: true,
      layer3Type: 'shell_script',
      layer3Source: 'text',
      layer3TextMapText: 'ARBOR',
      layer3MaterialStyle: 'hologram',
      layer3TemporalProfile: 'rewrite',
      layer3TemporalStrength: 0.24,
      layer3HullOpacity: 0.8,
      layer3HullFresnel: 0.74,
      layer3PatchResolution: 52,
    }),
  createStarterPreset('starter-temporal-rewrite-cycle', 'Temporal Rewrite Cycle', {
      layer2Enabled: true,
      layer2Type: 'ink_bleed',
      layer2Source: 'text',
      layer2TextMapText: 'REWRITE',
      layer2MaterialStyle: 'halftone',
      layer2TemporalProfile: 'rewrite',
      layer2TemporalStrength: 0.28,
      layer2DepositionOpacity: 0.82,
      layer2DepositionRelief: 0.54,
      layer2DepositionErosion: 0.22,
      layer2DepositionBands: 6,
      layer3Enabled: true,
      layer3Type: 'glyph_weave',
      layer3Source: 'text',
      layer3TextMapText: '慈愛体系',
      layer3MaterialStyle: 'hologram',
      layer3TemporalProfile: 'rewrite',
      layer3TemporalStrength: 0.28,
      layer3GlyphOutlineEnabled: true,
      layer3GlyphOutlineWidth: 1.48,
      layer3GlyphOutlineOpacity: 0.54,
      layer3FiberOpacity: 0.78,
      layer3FiberLength: 0.96,
      layer3FiberDensity: 0.74,
      layer3FiberCurl: 0.18,
    }),
  createStarterPreset('starter-elastic-sheet-span', 'Elastic Sheet Span', { layer2Type: 'elastic_sheet', layer2Source: 'plane', layer2MaterialStyle: 'glass', layer2TemporalProfile: 'anneal', layer2TemporalStrength: 0.24, layer2Count: 9800, layer2BaseSize: 0.92, layer2RadiusScale: 1.1, layer2SheetOpacity: 0.66, layer2SheetFresnel: 0.76, layer2SheetAudioReactive: 0.14, layer2Enabled: true }),
  createStarterPreset('starter-capillary-sheet-ledger', 'Capillary Sheet Ledger', { layer2Type: 'capillary_sheet', layer2Source: 'text', layer2TextMapText: 'LEDGER', layer2MaterialStyle: 'halftone', layer2TemporalProfile: 'saturate', layer2TemporalStrength: 0.28, layer2Count: 9800, layer2BaseSize: 0.8, layer2DepositionOpacity: 0.84, layer2DepositionRelief: 0.5, layer2DepositionErosion: 0.18, layer2DepositionBands: 7, layer2Enabled: true }),
  createStarterPreset('starter-sediment-stack-dune', 'Sediment Stack Dune', { layer2Type: 'sediment_stack', layer2Source: 'plane', layer2MaterialStyle: 'halftone', layer2TemporalProfile: 'delaminate', layer2TemporalStrength: 0.24, layer2Count: 10400, layer2BaseSize: 0.68, layer2CrystalOpacity: 0.76, layer2CrystalScale: 0.82, layer2CrystalDensity: 0.82, layer2CrystalSpread: 0.18, layer2Enabled: true }),
  createStarterPreset('starter-cellular-front-grid', 'Cellular Front Grid', { layer2Type: 'cellular_front', layer2Source: 'grid', layer2MaterialStyle: 'classic', layer2TemporalProfile: 'bifurcate', layer2TemporalStrength: 0.26, layer2Count: 9000, layer2BaseSize: 0.82, layer2ReactionOpacity: 0.82, layer2ReactionFeed: 0.03, layer2ReactionKill: 0.046, layer2ReactionScale: 1.04, layer2ReactionWarp: 0.16, layer2Enabled: true }),
  createStarterPreset('starter-elastic-lattice-span', 'Elastic Lattice Span', { layer2Type: 'elastic_lattice', layer2Source: 'grid', layer2MaterialStyle: 'glass', layer2TemporalProfile: 'anneal', layer2TemporalStrength: 0.22, layer2Count: 9400, layer2BaseSize: 0.8, layer2VoxelOpacity: 0.78, layer2VoxelScale: 1.06, layer2VoxelDensity: 0.46, layer2VoxelSnap: 0.46, layer2Enabled: true }),
  createStarterPreset('starter-temporal-recur-codex', 'Temporal Recur Codex', { layer2Type: 'growth_grammar', layer2Source: 'text', layer2TextMapText: 'RECUR', layer2MaterialStyle: 'hologram', layer2TemporalProfile: 'recur', layer2TemporalStrength: 0.28, layer2Count: 9000, layer2GrowthOpacity: 0.8, layer2GrowthBranches: 8, layer2GrowthLength: 1.0, layer2GrowthSpread: 0.46, layer2Enabled: true, layer3Enabled: true, layer3Type: 'glyph_weave', layer3Source: 'text', layer3TextMapText: 'VARELSER', layer3MaterialStyle: 'classic', layer3TemporalProfile: 'recur', layer3TemporalStrength: 0.28, layer3GlyphOutlineEnabled: true, layer3GlyphOutlineWidth: 1.46, layer3GlyphOutlineOpacity: 0.54, layer3FiberOpacity: 0.78, layer3FiberLength: 0.94, layer3FiberDensity: 0.74, layer3FiberCurl: 0.18 }),
  createStarterPreset('starter-viscoelastic-memory-sheet', 'Viscoelastic Memory Sheet', { layer2Enabled: true, layer2Type: 'viscoelastic_membrane', layer2Source: 'plane', layer2MaterialStyle: 'glass', layer2TemporalProfile: 'rebound', layer2TemporalStrength: 0.26, layer2Count: 9800, layer2BaseSize: 0.94, layer2RadiusScale: 1.1, layer2SheetOpacity: 0.68, layer2SheetFresnel: 0.78, layer2SheetAudioReactive: 0.16 }),
  createStarterPreset('starter-percolation-ledger-flow', 'Percolation Ledger Flow', { layer2Enabled: true, layer2Type: 'percolation_sheet', layer2Source: 'text', layer2TextMapText: 'FLOW', layer2MaterialStyle: 'halftone', layer2TemporalProfile: 'percolate', layer2TemporalStrength: 0.28, layer2Count: 9600, layer2BaseSize: 0.82, layer2DepositionOpacity: 0.84, layer2DepositionRelief: 0.58, layer2DepositionErosion: 0.16, layer2DepositionBands: 8 }),
  createStarterPreset('starter-talus-heap-slope', 'Talus Heap Slope', { layer2Enabled: true, layer2Type: 'talus_heap', layer2Source: 'plane', layer2MaterialStyle: 'halftone', layer2TemporalProfile: 'slump', layer2TemporalStrength: 0.24, layer2Count: 10800, layer2BaseSize: 0.68, layer2CrystalOpacity: 0.76, layer2CrystalScale: 0.78, layer2CrystalDensity: 0.84, layer2CrystalSpread: 0.16 }),
  createStarterPreset('starter-corrosion-front-etch', 'Corrosion Front Etch', { layer2Enabled: true, layer2Type: 'corrosion_front', layer2Source: 'grid', layer2MaterialStyle: 'chrome', layer2TemporalProfile: 'fissure', layer2TemporalStrength: 0.26, layer2Count: 9200, layer2BaseSize: 0.8, layer2ReactionOpacity: 0.8, layer2ReactionFeed: 0.023, layer2ReactionKill: 0.044, layer2ReactionScale: 1.08, layer2ReactionWarp: 0.24 }),
  createStarterPreset('starter-creep-lattice-span', 'Creep Lattice Span', { layer2Enabled: true, layer2Type: 'creep_lattice', layer2Source: 'grid', layer2MaterialStyle: 'glass', layer2TemporalProfile: 'rebound', layer2TemporalStrength: 0.22, layer2Count: 9400, layer2BaseSize: 0.82, layer2VoxelOpacity: 0.8, layer2VoxelScale: 1.12, layer2VoxelDensity: 0.42, layer2VoxelSnap: 0.34 }),
  createStarterPreset('starter-ossify-corrosion-cycle', 'Ossify Corrosion Cycle', { layer2Enabled: true, layer2Type: 'talus_heap', layer2Source: 'plane', layer2MaterialStyle: 'halftone', layer2TemporalProfile: 'ossify', layer2TemporalStrength: 0.24, layer2Count: 10800, layer2BaseSize: 0.68, layer2CrystalOpacity: 0.76, layer2CrystalScale: 0.78, layer2CrystalDensity: 0.84, layer2CrystalSpread: 0.16, layer3Enabled: true, layer3Type: 'corrosion_front', layer3Source: 'grid', layer3MaterialStyle: 'chrome', layer3TemporalProfile: 'fissure', layer3TemporalStrength: 0.24, layer3ReactionOpacity: 0.8, layer3ReactionFeed: 0.023, layer3ReactionKill: 0.044, layer3ReactionScale: 1.08, layer3ReactionWarp: 0.24 }),
  createStarterPreset('starter-advection-flow-ledger', 'Advection Flow Ledger', { layer2Enabled: true, layer2Type: 'advection_flow', layer2Source: 'plane', layer2MaterialStyle: 'classic', layer2TemporalProfile: 'intermittent', layer2TemporalStrength: 0.24, layer2Count: 9400, layer2BaseSize: 0.88, layer2BrushOpacity: 0.8, layer2BrushLayers: 5, layer2BrushScale: 1.02, layer2BrushJitter: 0.12 }),
  createStarterPreset('starter-vortex-transport-column', 'Vortex Transport Column', { layer2Enabled: true, layer2Type: 'vortex_transport', layer2Source: 'sphere', layer2MaterialStyle: 'glass', layer2TemporalProfile: 'erupt', layer2TemporalStrength: 0.24, layer2Count: 7600, layer2BaseSize: 1.18, layer2RadiusScale: 1.16, layer2FogOpacity: 0.3, layer2FogDensity: 0.38, layer2FogDepth: 0.86, layer2FogScale: 1.0, layer2FogDrift: 0.34, layer2FogSlices: 22, layer2FogGlow: 0.2, layer2FogAnisotropy: 0.56 }),
  createStarterPreset('starter-pressure-cells-basin', 'Pressure Cells Basin', { layer2Enabled: true, layer2Type: 'pressure_cells', layer2Source: 'grid', layer2MaterialStyle: 'halftone', layer2TemporalProfile: 'hysteresis', layer2TemporalStrength: 0.24, layer2Count: 7200, layer2BaseSize: 1.12, layer2FogOpacity: 0.28, layer2FogDensity: 0.44, layer2FogDepth: 0.62, layer2FogScale: 0.84, layer2FogDrift: 0.12, layer2FogSlices: 20, layer2FogGlow: 0.08, layer2FogAnisotropy: 0.18 }),
  createStarterPreset('starter-avalanche-field-slope', 'Avalanche Field Slope', { layer2Enabled: true, layer2Type: 'avalanche_field', layer2Source: 'plane', layer2MaterialStyle: 'halftone', layer2TemporalProfile: 'fatigue', layer2TemporalStrength: 0.24, layer2Count: 11200, layer2BaseSize: 0.66, layer2CrystalOpacity: 0.74, layer2CrystalScale: 0.82, layer2CrystalDensity: 0.92, layer2CrystalSpread: 0.34 }),
  createStarterPreset('starter-jammed-pack-cube', 'Jammed Pack Cube', { layer2Enabled: true, layer2Type: 'jammed_pack', layer2Source: 'cube', layer2MaterialStyle: 'classic', layer2TemporalProfile: 'recover', layer2TemporalStrength: 0.22, layer2Count: 9800, layer2BaseSize: 0.78, layer2CrystalOpacity: 0.82, layer2CrystalScale: 1.02, layer2CrystalDensity: 1.0, layer2CrystalSpread: 0.14 }),
  createStarterPreset('starter-advection-pressure-cycle', 'Advection Pressure Cycle', { layer2Enabled: true, layer2Type: 'advection_flow', layer2Source: 'plane', layer2MaterialStyle: 'classic', layer2TemporalProfile: 'intermittent', layer2TemporalStrength: 0.24, layer2Count: 9400, layer2BaseSize: 0.88, layer2BrushOpacity: 0.8, layer2BrushLayers: 5, layer2BrushScale: 1.02, layer2BrushJitter: 0.12, layer3Enabled: true, layer3Type: 'pressure_cells', layer3Source: 'grid', layer3MaterialStyle: 'halftone', layer3TemporalProfile: 'hysteresis', layer3TemporalStrength: 0.24, layer3FogOpacity: 0.28, layer3FogDensity: 0.44, layer3FogDepth: 0.62, layer3FogScale: 0.84, layer3FogDrift: 0.12, layer3FogSlices: 20, layer3FogGlow: 0.08, layer3FogAnisotropy: 0.18 }),
  createStarterPreset('starter-melt-front-film', 'Melt Front Film', { layer2Enabled: true, layer2Type: 'melt_front', layer2Source: 'plane', layer2MaterialStyle: 'classic', layer2TemporalProfile: 'collapse', layer2TemporalStrength: 0.24, layer2Count: 9000, layer2BaseSize: 0.92, layer2BrushOpacity: 0.82, layer2BrushLayers: 5, layer2BrushScale: 1.08, layer2BrushJitter: 0.18 }),
  createStarterPreset('starter-freeze-skin-shell', 'Freeze Skin Shell', { layer2Enabled: true, layer2Type: 'freeze_skin', layer2Source: 'sphere', layer2MaterialStyle: 'glass', layer2TemporalProfile: 'invert', layer2TemporalStrength: 0.22, layer2Count: 7600, layer2BaseSize: 1.0, layer2RadiusScale: 1.08, layer2HullOpacity: 0.72, layer2HullFresnel: 0.92, layer2HullPointBudget: 1600, layer2HullJitter: 0.05 }),
  createStarterPreset('starter-condense-field-basin', 'Condense Field Basin', { layer2Enabled: true, layer2Type: 'condense_field', layer2Source: 'plane', layer2MaterialStyle: 'glass', layer2TemporalProfile: 'emerge', layer2TemporalStrength: 0.24, layer2Count: 7600, layer2BaseSize: 1.06, layer2FogOpacity: 0.3, layer2FogDensity: 0.48, layer2FogDepth: 0.7, layer2FogScale: 0.9, layer2FogDrift: 0.14, layer2FogSlices: 22, layer2FogGlow: 0.12, layer2FogAnisotropy: 0.22 }),
]
