import type { PresetSequenceItem } from '../types';

export const STARTER_PRESET_SEQUENCE_CHUNK_01: PresetSequenceItem[] = [
  {
      id: 'starter-sequence-halo-bloom-equinox',
      presetId: 'starter-halo-bloom-equinox',
      label: 'Halo Bloom Equinox',
      holdSeconds: 2.8,
      transitionSeconds: 2.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-membrane-pollen-herbarium',
      presetId: 'starter-membrane-pollen-herbarium',
      label: 'Membrane Pollen Herbarium',
      holdSeconds: 2.8,
      transitionSeconds: 2.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-spore-halo-reliquary',
      presetId: 'starter-spore-halo-reliquary',
      label: 'Spore Halo Reliquary',
      holdSeconds: 2.9,
      transitionSeconds: 2.2,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-prismatic-storm-breathing',
      presetId: 'starter-prismatic-storm-breathing',
      label: 'Prismatic Storm Breathing',
      holdSeconds: 2.8,
      transitionSeconds: 2.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-ash-script-shedding',
      presetId: 'starter-ash-script-shedding',
      label: 'Ash Script Shedding',
      holdSeconds: 2.7,
      transitionSeconds: 2.0,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-veil-lattice-accretion',
      presetId: 'starter-veil-lattice-accretion',
      label: 'Veil Lattice Accretion',
      holdSeconds: 3.0,
      transitionSeconds: 2.2,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-runic-smoke-evaporation',
      presetId: 'starter-runic-smoke-evaporation',
      label: 'Runic Smoke Evaporation',
      holdSeconds: 2.6,
      transitionSeconds: 2.0,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-pollen-shell-shedding',
      presetId: 'starter-pollen-shell-shedding',
      label: 'Pollen Shell Shedding',
      holdSeconds: 2.9,
      transitionSeconds: 2.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-flock-drift-choir',
      presetId: 'starter-flock-drift-choir',
      label: 'Flock Drift Choir',
      holdSeconds: 2.7,
      transitionSeconds: 2.0,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-vortex-sheet-gate',
      presetId: 'starter-vortex-sheet-gate',
      label: 'Vortex Sheet Gate',
      holdSeconds: 2.5,
      transitionSeconds: 1.9,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-branch-propagation-atlas',
      presetId: 'starter-branch-propagation-atlas',
      label: 'Branch Propagation Atlas',
      holdSeconds: 2.9,
      transitionSeconds: 2.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-seep-fracture-delta',
      presetId: 'starter-seep-fracture-delta',
      label: 'Seep Fracture Delta',
      holdSeconds: 2.6,
      transitionSeconds: 2.0,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-vapor-canopy-sanctum',
      presetId: 'starter-vapor-canopy-sanctum',
      label: 'Vapor Canopy Sanctum',
      holdSeconds: 2.8,
      transitionSeconds: 2.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-plasma-thread-cathedral',
      presetId: 'starter-plasma-thread-cathedral',
      label: 'Plasma Thread Cathedral',
      holdSeconds: 2.7,
      transitionSeconds: 2.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-ashfall-vault',
      presetId: 'starter-ashfall-vault',
      label: 'Ashfall Vault',
      holdSeconds: 2.6,
      transitionSeconds: 2.0,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-echo-rings-reliquary',
      presetId: 'starter-echo-rings-reliquary',
      label: 'Echo Rings Reliquary',
      holdSeconds: 2.4,
      transitionSeconds: 1.8,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-skin-lattice-vessel',
      presetId: 'starter-skin-lattice-vessel',
      label: 'Skin Lattice Vessel',
      holdSeconds: 2.8,
      transitionSeconds: 2.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-mist-ribbon-manuscript',
      presetId: 'starter-mist-ribbon-manuscript',
      label: 'Mist Ribbon Manuscript',
      holdSeconds: 2.6,
      transitionSeconds: 2.0,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-plasma-skin-carapace',
      presetId: 'starter-hybrid-plasma-skin-carapace',
      label: 'Hybrid Plasma Skin Carapace',
      holdSeconds: 2.8,
      transitionSeconds: 2.2,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-ash-echo-falloff',
      presetId: 'starter-hybrid-ash-echo-falloff',
      label: 'Hybrid Ash Echo Falloff',
      holdSeconds: 2.5,
      transitionSeconds: 2.0,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-mist-inscription-drift',
      presetId: 'starter-hybrid-mist-inscription-drift',
      label: 'Hybrid Mist Inscription Drift',
      holdSeconds: 2.6,
      transitionSeconds: 2.0,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-membrane-crystal',
      presetId: 'starter-hybrid-membrane-crystal',
      label: 'Hybrid Membrane Crystal Shrine',
      holdSeconds: 2.8,
      transitionSeconds: 2.2,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-fog-glyph',
      presetId: 'starter-hybrid-fog-glyph',
      label: 'Hybrid Fog Glyph Sanctuary',
      holdSeconds: 2.7,
      transitionSeconds: 2.1,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
  {
      id: 'starter-sequence-hybrid-deposition-growth',
      presetId: 'starter-hybrid-deposition-growth',
      label: 'Hybrid Deposition Growth Delta',
      holdSeconds: 2.6,
      transitionSeconds: 2.0,
      transitionEasing: 'ease-in-out',
      screenSequenceDriveMode: 'inherit',
      screenSequenceDriveStrengthMode: 'inherit',
      screenSequenceDriveStrengthOverride: null,
      screenSequenceDriveMultiplier: 1,
      keyframeConfig: null,
    },
]
