import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_BASE_CHUNK_02_HYBRID: PresetRecord[] = [
  createStarterPreset('starter-hybrid-membrane-crystal', 'Hybrid Membrane Crystal Shrine', {
        renderQuality: 'cinematic',
        layer1Count: 4200,
        layer2Enabled: true,
        layer2Type: 'surface_shell',
        layer2Source: 'sphere',
        layer2Count: 9400,
        layer2MaterialStyle: 'glass',
        layer2HullOpacity: 0.28,
        layer2HullPointBudget: 1536,
        layer2HullFresnel: 0.88,
        layer2TemporalProfile: 'growth',
        layer2TemporalStrength: 0.42,
        layer2TemporalSpeed: 0.72,
        layer3Enabled: true,
        layer3Type: 'crystal_aggregate',
        layer3Source: 'sphere',
        layer3Count: 5600,
        layer3MaterialStyle: 'chrome',
        layer3CrystalOpacity: 0.74,
        layer3CrystalScale: 1.36,
        layer3CrystalDensity: 0.52,
        layer3CrystalSpread: 0.22,
        layer3TemporalProfile: 'crystallize',
        layer3TemporalStrength: 0.48,
        layer3TemporalSpeed: 0.66,
        depthFogEnabled: true,
      }),
  createStarterPreset('starter-hybrid-fog-glyph', 'Hybrid Fog Glyph Sanctuary', {
        cameraControlMode: 'auto',
        renderQuality: 'cinematic',
        layer1Count: 3400,
        layer2Enabled: true,
        layer2Type: 'volume_fog',
        layer2Source: 'cube',
        layer2Count: 7200,
        layer2MaterialStyle: 'glass',
        layer2FogOpacity: 0.16,
        layer2FogDensity: 0.26,
        layer2FogDepth: 0.84,
        layer2FogScale: 1.34,
        layer2FogSlices: 24,
        layer2TemporalProfile: 'melt',
        layer2TemporalStrength: 0.26,
        layer2TemporalSpeed: 0.58,
        layer3Enabled: true,
        layer3Type: 'reaction_diffusion',
        layer3Source: 'text',
        layer3TextMapText: 'PRAYER',
        layer3Count: 9800,
        layer3MaterialStyle: 'hologram',
        layer3ReactionOpacity: 0.74,
        layer3ReactionFeed: 0.028,
        layer3ReactionKill: 0.057,
        layer3ReactionScale: 1.06,
        layer3ReactionWarp: 0.22,
        layer3GlyphOutlineEnabled: true,
        layer3TemporalProfile: 'rupture',
        layer3TemporalStrength: 0.22,
        layer3TemporalSpeed: 0.92,
        depthFogEnabled: true,
      }),
  createStarterPreset('starter-hybrid-deposition-growth', 'Hybrid Deposition Growth Delta', {
        viewMode: 'orthographic',
        renderQuality: 'balanced',
        layer1Count: 3800,
        layer2Enabled: true,
        layer2Type: 'deposition_field',
        layer2Source: 'plane',
        layer2Count: 11600,
        layer2MaterialStyle: 'chrome',
        layer2DepositionOpacity: 0.68,
        layer2DepositionRelief: 0.64,
        layer2DepositionBands: 7,
        layer2DepositionErosion: 0.12,
        layer2TemporalProfile: 'growth',
        layer2TemporalStrength: 0.38,
        layer2TemporalSpeed: 0.74,
        layer3Enabled: true,
        layer3Type: 'growth_field',
        layer3Source: 'plane',
        layer3Count: 6800,
        layer3MaterialStyle: 'halftone',
        layer3GrowthOpacity: 0.58,
        layer3GrowthBranches: 10,
        layer3GrowthLength: 0.86,
        layer3GrowthSpread: 0.32,
        layer3TemporalProfile: 'growth',
        layer3TemporalStrength: 0.44,
        layer3TemporalSpeed: 0.82,
      }),
  createStarterPreset('starter-hybrid-shell-pulse', 'Hybrid Shell Pulse Reliquary', {
        renderQuality: 'cinematic',
        layer1Count: 4600,
        layer2Enabled: true,
        layer2Type: 'aura_shell',
        layer2Source: 'sphere',
        layer2Count: 8800,
        layer2MaterialStyle: 'glass',
        layer2HullOpacity: 0.22,
        layer2HullPointBudget: 1408,
        layer2HullFresnel: 0.94,
        layer2TemporalProfile: 'steady',
        layer3Enabled: true,
        layer3Type: 'pulse_breathing',
        layer3Source: 'ring',
        layer3Count: 12400,
        layer3FlowAmplitude: 34,
        layer3FlowFrequency: 1.18,
        layer3Burst: 0.22,
        layer3Trail: 0.28,
        layer3TemporalProfile: 'melt',
        layer3TemporalStrength: 0.26,
        layer3TemporalSpeed: 0.84,
        screenPulseIntensity: 0.14,
      }),
  createStarterPreset('starter-hybrid-liquid-rupture', 'Hybrid Liquid Rupture Manuscript', {
        viewMode: 'orthographic',
        renderQuality: 'balanced',
        layer1Count: 3600,
        layer2Enabled: true,
        layer2Type: 'liquid_smear',
        layer2Source: 'text',
        layer2TextMapText: 'TEAR',
        layer2Count: 7600,
        layer2MaterialStyle: 'halftone',
        layer2BrushOpacity: 0.34,
        layer2BrushLayers: 5,
        layer2BrushJitter: 0.28,
        layer2TemporalProfile: 'melt',
        layer2TemporalStrength: 0.44,
        layer2TemporalSpeed: 0.76,
        layer3Enabled: true,
        layer3Type: 'collapse_fracture',
        layer3Source: 'text',
        layer3TextMapText: 'TEAR',
        layer3Count: 16600,
        layer3FlowAmplitude: 62,
        layer3FlowFrequency: 1.32,
        layer3Trail: 0.4,
        layer3NoiseScale: 1.18,
        layer3TemporalProfile: 'rupture',
        layer3TemporalStrength: 0.48,
        layer3TemporalSpeed: 0.92,
        depthFogEnabled: true,
      }),
];
