import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_EXTENSION_CHUNK_03_REVIEW_SPLIT: PresetRecord[] = [
  createStarterPreset('starter-review-text-inscription-split', 'Review Text Inscription Split', {
        layer2Enabled: true,
        layer2Type: 'shell_script',
        layer2Source: 'text',
        layer2TextMapText: 'VARELSER',
        layer2MaterialStyle: 'classic',
        layer2TemporalProfile: 'unravel',
        layer2TemporalStrength: 0.26,
        layer2HullOpacity: 0.82,
        layer2HullFresnel: 0.74,
        layer2HullPointBudget: 1320,
        layer3Enabled: true,
        layer3Type: 'ink_bleed',
        layer3Source: 'text',
        layer3TextMapText: '慈愛体系',
        layer3MaterialStyle: 'halftone',
        layer3TemporalProfile: 'accrete',
        layer3TemporalStrength: 0.24,
        layer3DepositionOpacity: 0.8,
        layer3DepositionRelief: 0.6,
        layer3DepositionErosion: 0.3,
        layer3DepositionBands: 5,
      }),
  createStarterPreset('starter-review-grid-architectonic-split', 'Review Grid Architectonic Split', {
        layer2Enabled: true,
        layer2Type: 'calcified_skin',
        layer2Source: 'grid',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'steady',
        layer2HullOpacity: 0.76,
        layer2HullFresnel: 0.46,
        layer2HullJitter: 0.04,
        layer3Enabled: true,
        layer3Type: 'static_smoke',
        layer3Source: 'grid',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'oscillate',
        layer3TemporalStrength: 0.22,
        layer3FogOpacity: 0.24,
        layer3FogDensity: 0.46,
        layer3FogDepth: 0.72,
        layer3FogScale: 0.9,
      }),
  createStarterPreset('starter-review-ring-orbit-split', 'Review Ring Orbit Split', {
        layer2Enabled: true,
        layer2Type: 'eclipse_halo',
        layer2Source: 'ring',
        layer2MaterialStyle: 'hologram',
        layer2TemporalProfile: 'oscillate',
        layer2TemporalStrength: 0.28,
        layer2HullOpacity: 0.82,
        layer2HullFresnel: 0.8,
        layer2HullJitter: 0.04,
        layer3Enabled: true,
        layer3Type: 'spectral_mesh',
        layer3Source: 'ring',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'resonate',
        layer3TemporalStrength: 0.3,
        layer3FiberOpacity: 0.8,
        layer3FiberLength: 1.12,
        layer3FiberDensity: 0.72,
        layer3FiberCurl: 0.28,
      }),
  createStarterPreset('starter-review-plane-ledger-split', 'Review Plane Ledger Split', {
        layer2Enabled: true,
        layer2Type: 'soot_veil',
        layer2Source: 'plane',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'shed',
        layer2TemporalStrength: 0.2,
        layer2FogOpacity: 0.24,
        layer2FogDensity: 0.48,
        layer2FogDepth: 0.72,
        layer2FogScale: 0.88,
        layer3Enabled: true,
        layer3Type: 'ink_bleed',
        layer3Source: 'plane',
        layer3MaterialStyle: 'halftone',
        layer3TemporalProfile: 'accrete',
        layer3TemporalStrength: 0.24,
        layer3DepositionOpacity: 0.82,
        layer3DepositionRelief: 0.58,
        layer3DepositionErosion: 0.28,
        layer3DepositionBands: 4,
      }),
  createStarterPreset('starter-review-text-local-residual-split', 'Review Text Local Residual Split', {
        layer2Enabled: true,
        layer2Type: 'shell_script',
        layer2Source: 'text',
        layer2TextMapText: 'VARELSER',
        layer2MaterialStyle: 'classic',
        layer2TemporalProfile: 'unravel',
        layer2TemporalStrength: 0.28,
        layer2HullOpacity: 0.84,
        layer2HullFresnel: 0.78,
        layer2HullPointBudget: 1380,
        layer3Enabled: true,
        layer3Type: 'drift_glyph_dust',
        layer3Source: 'text',
        layer3TextMapText: '慈愛体系',
        layer3MaterialStyle: 'halftone',
        layer3TemporalProfile: 'accrete',
        layer3TemporalStrength: 0.22,
        layer3DepositionOpacity: 0.76,
        layer3DepositionRelief: 0.46,
        layer3DepositionErosion: 0.34,
        layer3DepositionBands: 5,
      }),
  createStarterPreset('starter-review-grid-local-residual-split', 'Review Grid Local Residual Split', {
        layer2Enabled: true,
        layer2Type: 'calcified_skin',
        layer2Source: 'grid',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'steady',
        layer2HullOpacity: 0.8,
        layer2HullFresnel: 0.5,
        layer2HullJitter: 0.05,
        layer3Enabled: true,
        layer3Type: 'static_lace',
        layer3Source: 'grid',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'oscillate',
        layer3TemporalStrength: 0.24,
        layer3LineVelocityGlow: 0.72,
        layer3LineVelocityAlpha: 0.32,
        layer3LineBurstPulse: 0.28,
        layer3LineShimmer: 0.3,
        layer3LineFlickerSpeed: 1.58,
        layer3FiberOpacity: 0.74,
        layer3FiberLength: 0.92,
        layer3FiberDensity: 0.72,
        layer3FiberCurl: 0.16,
      }),
  createStarterPreset('starter-review-text-plate-weave-split', 'Review Text Plate Weave Split', {
        layer2Enabled: true,
        layer2Type: 'contour_echo',
        layer2Source: 'text',
        layer2TextMapText: 'VARELSER',
        layer2MaterialStyle: 'chrome',
        layer2TemporalProfile: 'resonate',
        layer2TemporalStrength: 0.28,
        layer2PatchResolution: 58,
        layer2PatchRelax: 0.16,
        layer2PatchFresnel: 0.72,
        layer2GlyphOutlineEnabled: true,
        layer2GlyphOutlineWidth: 1.5,
        layer2GlyphOutlineOpacity: 0.58,
        layer3Enabled: true,
        layer3Type: 'glyph_weave',
        layer3Source: 'text',
        layer3TextMapText: '慈愛体系',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'oscillate',
        layer3TemporalStrength: 0.28,
        layer3GlyphOutlineEnabled: true,
        layer3GlyphOutlineWidth: 1.42,
        layer3GlyphOutlineOpacity: 0.5,
        layer3FiberOpacity: 0.78,
        layer3FiberLength: 0.94,
        layer3FiberDensity: 0.74,
        layer3FiberCurl: 0.18,
      }),
  createStarterPreset('starter-review-grid-relief-line-split', 'Review Grid Relief Line Split', {
        layer2Enabled: true,
        layer2Type: 'tremor_lattice',
        layer2Source: 'grid',
        layer2MaterialStyle: 'halftone',
        layer2TemporalProfile: 'oscillate',
        layer2TemporalStrength: 0.24,
        layer2PatchResolution: 56,
        layer2PatchRelax: 0.18,
        layer2PatchFresnel: 0.68,
        layer3Enabled: true,
        layer3Type: 'static_lace',
        layer3Source: 'grid',
        layer3MaterialStyle: 'hologram',
        layer3TemporalProfile: 'resonate',
        layer3TemporalStrength: 0.24,
        layer3LineVelocityGlow: 0.7,
        layer3LineVelocityAlpha: 0.32,
        layer3LineBurstPulse: 0.24,
        layer3LineShimmer: 0.3,
        layer3LineFlickerSpeed: 1.52,
        layer3FiberOpacity: 0.72,
        layer3FiberLength: 0.92,
        layer3FiberDensity: 0.72,
        layer3FiberCurl: 0.14,
      }),
];
