import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_BASE_CHUNK_03_HYBRID_STUDIES: PresetRecord[] = [
  createStarterPreset('starter-hybrid-crystal-bloom', 'Hybrid Crystal Bloom Reliquary', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer1Enabled: true,
        layer1Count: 4200,
        layer2Enabled: true,
        layer2Type: 'surface_shell',
        layer2Source: 'sphere',
        layer2Color: '#9be7ff',
        layer2TemporalProfile: 'growth',
        layer2TemporalStrength: 0.72,
        layer2TemporalSpeed: 0.82,
        layer3Enabled: true,
        layer3Type: 'crystal_aggregate',
        layer3Source: 'sphere',
        layer3Color: '#f7fbff',
        layer3TemporalProfile: 'crystallize',
        layer3TemporalStrength: 0.84,
        layer3TemporalSpeed: 0.78,
        depthFogEnabled: true,
        depthFogNear: 460,
        depthFogFar: 2200,
        particleGlow: 0.36,
      }),
  createStarterPreset('starter-hybrid-inscription-fade', 'Hybrid Inscription Fade Sanctuary', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer1Enabled: true,
        layer1Count: 3600,
        layer3TextMapText: 'VARELSER',
        layer2Enabled: true,
        layer2Type: 'dust_plume',
        layer2Color: '#9dd8ff',
        layer2TemporalProfile: 'decay',
        layer2TemporalStrength: 0.7,
        layer2TemporalSpeed: 0.9,
        layer3Enabled: true,
        layer3Type: 'brush_surface',
        layer3Color: '#f3f1ff',
        layer3Source: 'text',
        layer3TemporalProfile: 'melt',
        layer3TemporalStrength: 0.64,
        layer3TemporalSpeed: 0.86,
        depthFogEnabled: true,
        depthFogNear: 380,
        depthFogFar: 1800,
        particleGlow: 0.3,
      }),
  createStarterPreset('starter-hybrid-accretion-lift', 'Hybrid Accretion Lift Delta', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer1Enabled: true,
        layer1Count: 4000,
        layer2Enabled: true,
        layer2Type: 'deposition_field',
        layer2Color: '#a7d0ff',
        layer2TemporalProfile: 'growth',
        layer2TemporalStrength: 0.78,
        layer2TemporalSpeed: 0.74,
        layer3Enabled: true,
        layer3Type: 'growth_field',
        layer3Color: '#eef6ff',
        layer3TemporalProfile: 'growth',
        layer3TemporalStrength: 0.76,
        layer3TemporalSpeed: 0.8,
        particleGlow: 0.18,
      }),
  createStarterPreset('starter-hybrid-breathing-reliquary', 'Hybrid Breathing Reliquary', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer1Enabled: true,
        layer1Count: 2800,
        layer2Enabled: true,
        layer2Type: 'halo_bloom',
        layer2Color: '#b6d7ff',
        layer2TemporalProfile: 'melt',
        layer2TemporalStrength: 0.62,
        layer2TemporalSpeed: 0.92,
        layer3Enabled: true,
        layer3Type: 'pulse_breathing',
        layer3Color: '#ffffff',
        layer3TemporalProfile: 'rupture',
        layer3TemporalStrength: 0.58,
        layer3TemporalSpeed: 1.05,
        particleGlow: 0.4,
      }),
  createStarterPreset('starter-hybrid-fracture-spill', 'Hybrid Fracture Spill Manuscript', {
        cameraControlMode: 'hybrid',
        renderQuality: 'balanced',
        layer1Enabled: true,
        layer1Count: 3200,
        layer2Enabled: true,
        layer2Type: 'liquid_smear',
        layer2Color: '#d5d8ff',
        layer2TemporalProfile: 'melt',
        layer2TemporalStrength: 0.7,
        layer2TemporalSpeed: 0.84,
        layer3Enabled: true,
        layer3Type: 'shard_debris',
        layer3Color: '#f5fbff',
        layer3TemporalProfile: 'rupture',
        layer3TemporalStrength: 0.82,
        layer3TemporalSpeed: 1.1,
        particleGlow: 0.22,
      }),
  createStarterPreset('starter-plasma-thread-cathedral', 'Plasma Thread Cathedral', {
        renderQuality: 'cinematic',
        layer1Count: 3600,
        layer2Enabled: true,
        layer2Type: 'plasma_thread',
        layer2Source: 'spiral',
        layer2Count: 8200,
        layer2MaterialStyle: 'hologram',
        layer2FiberOpacity: 0.62,
        layer2FiberLength: 0.92,
        layer2FiberDensity: 0.58,
        layer2FiberCurl: 0.42,
        layer2TemporalProfile: 'rupture',
        layer2TemporalStrength: 0.38,
        layer2TemporalSpeed: 0.88,
        depthFogEnabled: true,
        particleGlow: 0.42,
      }),
  createStarterPreset('starter-ashfall-vault', 'Ashfall Vault', {
        renderQuality: 'balanced',
        layer1Count: 3000,
        layer2Enabled: true,
        layer2Type: 'ashfall',
        layer2Source: 'cube',
        layer2Count: 7600,
        layer2MaterialStyle: 'halftone',
        layer2FogOpacity: 0.18,
        layer2FogDensity: 0.34,
        layer2FogDepth: 0.92,
        layer2FogScale: 1.26,
        layer2FogSlices: 20,
        layer2TemporalProfile: 'decay',
        layer2TemporalStrength: 0.42,
        layer2TemporalSpeed: 0.72,
        depthFogEnabled: true,
      }),
  createStarterPreset('starter-echo-rings-reliquary', 'Echo Rings Reliquary', {
        viewMode: 'orthographic',
        renderQuality: 'balanced',
        layer1Count: 2800,
        layer2Enabled: true,
        layer2Type: 'echo_rings',
        layer2Source: 'text',
        layer2TextMapText: 'ECHO',
        layer2Count: 6400,
        layer2MaterialStyle: 'glass',
        layer2PatchOpacity: 0.42,
        layer2PatchResolution: 48,
        layer2PatchRelax: 0.68,
        layer2TemporalProfile: 'rupture',
        layer2TemporalStrength: 0.28,
        layer2TemporalSpeed: 1.08,
      }),
  createStarterPreset('starter-skin-lattice-vessel', 'Skin Lattice Vessel', {
        renderQuality: 'cinematic',
        layer1Count: 3400,
        layer2Enabled: true,
        layer2Type: 'skin_lattice',
        layer2Source: 'sphere',
        layer2Count: 9400,
        layer2MaterialStyle: 'chrome',
        layer2VoxelOpacity: 0.26,
        layer2VoxelSnap: 0.74,
        layer2VoxelScale: 0.88,
        layer2VoxelDensity: 0.54,
        layer2TemporalProfile: 'growth',
        layer2TemporalStrength: 0.32,
        layer2TemporalSpeed: 0.64,
      }),
];
