import type { PresetRecord } from '../types';
import { createStarterPreset } from './starterLibraryCore';

export const STARTER_PRESET_BASE_CHUNK_02_MOTION: PresetRecord[] = [
  createStarterPreset('starter-orbit-swarm', 'Orbit Swarm Crown', {
        layer1Count: 10000,
        layer2Enabled: true,
        layer2Type: 'orbit_swarm',
        layer2Source: 'ring',
        layer2Count: 22000,
        layer2FlowAmplitude: 54,
        layer2FlowFrequency: 1.8,
        layer2Trail: 0.28,
        layer2NoiseScale: 0.9,
        layer3Enabled: true,
        layer3Type: 'helio',
        layer3Source: 'sphere',
        layer3Count: 6400,
        layer3FlowAmplitude: 32,
        layer3FlowFrequency: 1.15,
        depthFogEnabled: true,
      }),
  createStarterPreset('starter-braid-stream', 'Braid Stream Filaments', {
        layer2Enabled: true,
        layer2Type: 'braid_stream',
        layer2Source: 'spiral',
        layer2Count: 18000,
        layer2FlowAmplitude: 48,
        layer2FlowFrequency: 1.65,
        layer2Trail: 0.52,
        layer2ConnectionEnabled: true,
        layer2ConnectionOpacity: 0.12,
        layer3Enabled: true,
        layer3Type: 'filament',
        layer3Source: 'cylinder',
        layer3Count: 5200,
        layer3Trail: 0.44,
      }),
  createStarterPreset('starter-pulse-breathing', 'Pulse Breathing Halo', {
        layer2Enabled: true,
        layer2Type: 'pulse_breathing',
        layer2Source: 'sphere',
        layer2Count: 16000,
        layer2FlowAmplitude: 38,
        layer2FlowFrequency: 1.2,
        layer2Burst: 0.24,
        layer2Trail: 0.24,
        layer3Enabled: true,
        layer3Type: 'beacon',
        layer3Source: 'ring',
        layer3Count: 4200,
        screenPulseIntensity: 0.12,
      }),
  createStarterPreset('starter-collapse-fracture', 'Collapse Fracture Manuscript', {
        layer2Enabled: true,
        layer2Type: 'collapse_fracture',
        layer2Source: 'text',
        layer2Count: 20000,
        layer2FlowAmplitude: 66,
        layer2FlowFrequency: 1.4,
        layer2Trail: 0.38,
        layer2NoiseScale: 1.1,
        layer3Enabled: true,
        layer3Type: 'explosion',
        layer3Source: 'text',
        layer3Count: 5600,
        layer3FlowAmplitude: 44,
        layer3Burst: 0.28,
      }),
  createStarterPreset('starter-crawl-seep', 'Crawl Seep Topography', {
        layer2Enabled: true,
        layer2Type: 'crawl_seep',
        layer2Source: 'image',
        layer2Count: 17000,
        layer2FlowAmplitude: 26,
        layer2FlowFrequency: 1.05,
        layer2Trail: 0.34,
        layer2NoiseScale: 1.3,
        layer3Enabled: true,
        layer3Type: 'crosscurrent',
        layer3Source: 'plane',
        layer3Count: 4600,
        layer3Trail: 0.42,
      }),
  createStarterPreset('starter-interference-wave', 'Interference Wave Lattice', {
        layer2Enabled: true,
        layer2Type: 'interference_wave',
        layer2Source: 'grid',
        layer2Count: 21000,
        layer2FlowAmplitude: 30,
        layer2FlowFrequency: 1.95,
        layer2Trail: 0.22,
        layer3Enabled: true,
        layer3Type: 'grid_wave',
        layer3Source: 'plane',
        layer3Count: 6800,
        layer3FlowAmplitude: 22,
        layer3FlowFrequency: 1.65,
      }),
];
